### ISSUE TITLE
[Bug]: playing 100GB moive Spirited Away, audio and video lag

### ISSUE THREAD

**Issue by alonginwind** [nova-video-player/aos-AVP#1005]
### Problem description

When playing 100GB moive Spirited Away via webdav on my Mi11, the audio and video lag. Sounds like the code rate is low. The network speed is enough, 20MB/s.
100GB Tatanic same issue.

### Steps to reproduce the issue

when playing that movie, the issue shows up.

### Expected behavior

the movie plays smoothly

### Your phone/tablet/androidTV model

XiaoMi 11

### Operating system version

Android 13

### Application version and app store

6.2.38 from github

**Comment by haoyuzhang98** [comment]
I have encountered the same issue, watching high rate movies on webdav will get stuck after a while, while watching low rate movies seems to have no issue

**Comment by alonginwind** [comment]
i download the movie, then everything is ok. maybe the net speed is not very well.

**Comment by courville** [comment]
@alonginwind, perhaps you could try to use either sshj (for sftp) or smbj (for smb) for network share access that are faster than the default implementations (sftp/jcifs-ng).
