### ISSUE TITLE
[Bug]: slow video on firetv

### ISSUE THREAD

**Issue by Celes1989** [nova-video-player/aos-AVP#1007]
### Problem description

Since today when I launch a video on firetv the sound is normal but the video is slow
When I use vlc I don't have the problem. 

### Steps to reproduce the issue

No

### Your phone/tablet/androidTV model

Firetv 4k max

### Operating system version

Last firetv os

**Comment by Celes1989** [comment]
Solved

I restarted the firetv and now it's ok

**Comment by Pentaphon** [comment]
Please close the issue if solved.
