### ISSUE TITLE
[Bug]: Download subtitles select screen disappearing instantly.

### ISSUE THREAD

**Issue by persidis** [nova-video-player/aos-AVP#1017]
### Problem description

Finally, using newest version of the player and new opensubtitles REST API, the player is able to find subtitles when pressing find subtitles on the internet. The problem is that the window that opens up with the results found **auto closes instantly**, not giving me time to select the subs I want! I can see the results for a split second, but I can't select the ones I want. If I smash the select button then I'm able to download the first subs found, so the whole trhing works fine, the only problem being that I can't select the ones I need.

### Steps to reproduce the issue

Open player through stremio, then press find subtitles on the internet.

### Your phone/tablet/androidTV model

H96 MAX - S905x4 TV Box

### Operating system version

Android TV 11

### Application version and app store

6.2.38 from github

**Comment by courville** [comment]
Yes I noticed this as well, must be a regression. Thanks for the heads up.
