### ISSUE TITLE
[FEAT]: WebDAV 302 redirects

### ISSUE THREAD

**Issue by lmrsdn** [nova-video-player/aos-AVP#1018]
### Description

Add support for WebDAV 302 redirects

Reference: http://www.webdav.org/specs/rfc4437.html#overview

Nova v6.2.38 (20231127.2120
Android TKQ1.221114.001

Currently Nova Player shows "Did not manage to access the file" error.

![Screenshot_2023-12-12-09-21-32-092_org courville nova](https://github.com/nova-video-player/aos-AVP/assets/64835505/6841d3d3-8401-4894-a728-996354e4dfbd)

**Comment by courville** [comment]
We are "dumb users" of https://github.com/thegrizzlylabs/sardine-android relying on https://github.com/lookfirst/sardine

I checked and sardine seems to support WebDAVs 302 redirect. 
We "just" need to process 302 response providing new destination address.

Thanks for the heads up.

Proposal is to use in WebdavUtils a custom OkHttpClient that follows redirects:
```
            OkHttpClient.Builder builder = new OkHttpClient.Builder();
            builder.followRedirects(true);
            builder.followSslRedirects(true); // Handle SSL redirect
            // Set the custom client to the Sardine instance
            sardine = new OkHttpSardine(builder.build());
```

**Comment by courville** [comment]
@lmrsdn would it be possible to get a test account or link to check if the implementation is correct?

**Comment by courville** [comment]
@lmrsdn or a test build for you to check https://drive.google.com/file/d/16xDTGuVHahBOh4QYNhTZClgNJkWvpDiJ/view?usp=sharing (arm64 build)

**Comment by lmrsdn** [comment]
Hi I installed and tested the above build v6.2.40-20231222.2220 and get the same error. I will try to setup a debrid test account for you and/or in the meantime if you have another build then I can test that also.

**Comment by courville** [comment]
OK thanks for the testing and report.
Note to self: some related reading https://stackoverflow.com/questions/24575356/java-webdav-file-synchronization and https://stackoverflow.com/questions/3658721/httpclient-4-error-302-how-to-redirect and https://github.com/lookfirst/sardine/issues/74
See as well src/main/java/com/github/sardine/impl/SardineRedirectStrategy.java in sardine

EDIT: to merge the lines in one in the logs use `awk '/^[0-9]/{if (line) print line; line=$0; next} {line = line " " $0} END{print line}'`

**Comment by lmrsdn** [comment]
I have emailed you directly with a RealDebrid test account WebDAV details for you to test this :)

**Comment by courville** [comment]
OK with the test account a quick test reveals that ffmpeg that parses the file when displaying information reports:
```
avos_player               org.courville.nova    D  FFMPEG: cannot open file
avos_player               org.courville.nova    D  [http @ 0xb4000070b9de6910] HTTP error 416 Range not satisfiable 
avos_player               org.courville.nova    D  FFMPEG: cannot open file
```
meaning that it tries to access file on a range that cannot be server by the server.

**Comment by lmrsdn** [comment]
If I mount the RealDebrid WebDAV url via Nemo file manager in Linux Mint which creates mount point  /run/user/1000/gvfs/dav:host=dav.real-debrid.com,ssl=true,user=######## the test movies will play successfully using either gui Celluloid (MPV based) or in terminal with ffplay "ffplay Big.Buck.Bunny.2008.x264.BDRip.1080p.mkv" as shown.

Nemo 5.8.5
gvfs 1.48.2-0ubuntu1
ffplay version 4.4.2-0ubuntu0.22.04.1
Celluloid 0.21

![Selection_346](https://github.com/nova-video-player/aos-AVP/assets/64835505/25ea0c93-4d64-4ec3-acb8-f29aa33520df)

**Comment by lmrsdn** [comment]
If I use davfs2 and mount the url to a mount point via terminal instead of gvfs in Nemo then playing fails and outputs an error, so I think its possible to do this but probably depends how the WebDAV client library handles the 302 redirects.

**Comment by courville** [comment]
Getting back on the issue finally. It seems that the redirect works but for some reason ffmpeg is upset:
```
I/okhttp.OkHttpClient(22140): <-- 206 Partial Content https://20.download.real-debrid.com/d/REDACTED/Big.Buck.Bunny.2008.x264.BDRip.1080p.mkv (235ms)
I/okhttp.OkHttpClient(22140): Server: Lity 2.0
I/okhttp.OkHttpClient(22140): Accept-Ranges: bytes
I/okhttp.OkHttpClient(22140): Content-Length: 648602823
I/okhttp.OkHttpClient(22140): Content-Range: bytes 0-648602822/648602823
I/okhttp.OkHttpClient(22140): Content-Disposition: attachment
I/okhttp.OkHttpClient(22140): Content-Type: application/force-download
I/okhttp.OkHttpClient(22140): Connection: close
I/okhttp.OkHttpClient(22140): <-- END HTTP
D/avos_player(22140): [http @ 0xb400007b5dc77810] HTTP error 416 Range not satisfiable
D/avos_player(22140): FFMPEG: cannot open file
```

**Comment by courville** [comment]
Please check this build and provide feedback if it fixes the issue on your side: https://drive.google.com/file/d/1ezS66RFPcZMOOjXV7DwwCGUsl21oNYNf/view?usp=sharing

Kudos to @phhusson for the fix.
Note that performance has been observed to be degraded compared to a "classical" webdavs server.

**Comment by lmrsdn** [comment]
Apologies for the late reply, I tried the test build and it works great😃. Well done @courville many thanks for taking the time to look into this and also to @phhusson for your contribution! 👍
