### ISSUE TITLE
[Bug]: lock player button not work properly

### ISSUE THREAD

**Issue by alonginwind** [nova-video-player/aos-AVP#1024]
### Problem description

when the lock player button is clicked, the lock icon shows on the sreen. but when i keep touching the screen or swipe on the screen,  ether the video is fast forwarding or rewinding, or the sound gets lower or louder.

### Steps to reproduce the issue

play a video every time

### Expected behavior

when locked, nothing can happen when touching screen.

### Your phone/tablet/androidTV model

Xiaomi 11

### Operating system version

Android 13

### Application version and app store

6.2.38 from github

**Comment by courville** [comment]
Indeed, gestures should not be enabled when lock mode engaged. I will fix it. Thanks for reporting.
