### ISSUE TITLE
[Bug]:  OpenSubtitle credentials

### ISSUE THREAD

**Issue by Quaap70** [nova-video-player/aos-AVP#1030]
### Problem description

After installing version v6.2.40, when I click the button 'get subtitles online' I get the message: 'Provide your opensubtitle credentials in settings to be able to download more subtitles' It may of course be that the password has to be entered again with the new installation, but when I enter the credentials in settings it gives: 'Incorrect opensubtitle credentials'. But my opensubtitle password has not been changed, and I can still log in to the opensubtitles.org website with it.

Before I installed this version, it simply retrieved a list of available subtitles, with the same login details that I used now. Do I need to create a new account somewhere, or do you need a different account for the REST API?

### Steps to reproduce the issue

when I click the button 'get subtitles online'

### Expected behavior

Provides a list of available subtitles

### Your phone/tablet/androidTV model

Google TV 4K Chromecast

### Operating system version

Android 12   Kernel 4.9.269

### Application version and app store

6.2.40

### Additional system information

 'Use new OpenSubtitle API' selected or not selected makes no difference in this case

**Comment by courville** [comment]
@Quaap70 thanks for bringing it up. I realize that I did not provided enough information about this change.
Unfortunately this is not a regression but addressing https://github.com/nova-video-player/aos-AVP/issues/852
opensubtitles.org will end supporting XML-RPC access for apps and requests to migrate to REST-API starting January using opensubtitles.com.
Old logins will not work and you need to get an opensubtitles.com account.

**Comment by Quaap70** [comment]
I had looked under the help/FAQ button in Nova to see if additional information was listed here. So I dug into the opensubtitle API documentation myself and immediately created an account there. I do see that the API version does have some limitations. Binge-watching series is no longer an option, at least not with endless subtitle support from open subtitles. unless you become a VIP member.

But fortunately the Nova app does give the API response back how many downloads are still available today ;-)

But thanks for your quick response!!

Je vous souhaite une célébration de la Saint-Sylvestre sûre et saine !

**Comment by courville** [comment]
FTR when I clicked on "check your status" on the VIP web page https://www.opensubtitles.com/fr/users/vip it granted me 20 subs download per day (I think I had 10 before).

Bonne Saint-Sylvestre aussi.

**Comment by courville** [comment]
EDIT: you need to click on "IF YOUR DOWNLOAD LIMIT IS WRONG, CLICK HERE TO FIX IT"  https://www.opensubtitles.com/fr/users/profile to get 20 subs download per day quota instead of 10 if this is your current limit.

**Comment by joanmam** [comment]
Hello. Apparently the system for opensubtitles does not work. I introduce proper credentials and it says "incorrect credentials or service unavailable". Thanks

**Comment by courville** [comment]
> Hello. Apparently the system for opensubtitles does not work. I introduce proper credentials and it says "incorrect credentials or service unavailable". Thanks

Just to be sure, are you using opensubtitles.org or opensubtitles.com credentials?

**Comment by Quaap70** [comment]
I just tested this... for me the subtitle download works fine.

**Comment by joanmam** [comment]
Hi. Thanks for the answer. I am using opensubtitles.com credentials.

Regards
Joan

El dl., 17 de febr. 2025, 18:58, Eric Heins ***@***.***> va
escriure:
