### ISSUE TITLE
[Bug]: Minor subtitle bug

### ISSUE THREAD

**Issue by Quaap70** [nova-video-player/aos-AVP#1032]
### Problem description

When you try to retrieve subtitles with the new REST-API, and there are no versions available in the languages you specified, the Nova app will notify you. When this notification disappears, but the Nova screen is then stuck. You must first press the back button to be able to operate the screen again and scroll up to play the video or perform another action.

The same also applies if you want to retrieve subtitles while playing the video and they are not found. Here you now have to press the back button once to be able scroll to the right for the other playback options, or twice to go back to the video.

Not a big problem, you can still use the app, but it seems like a minor bug. Unfortunately, the REST-API version does not always appear to find subtitles where the XML-RPC did. But that will be an opensubtitle issue, not Nova's

### Steps to reproduce the issue

click the "get subtitles online" button

### Expected behavior

If no subtitles are found for the video, you should be able to scroll up to play the video without subtitles.

### Your phone/tablet/androidTV model

Google TV 4K Chromecast

### Operating system version

Android 12 Kernel 4.9.269

### Application version and app store

6.2.40

**Comment by courville** [comment]
Damn I thought I fixed this one while debugging the new API. Ok thanks for the heads up. Will investigate.

**Comment by courville** [comment]
Strangely enough, I cannot reproduce with the current version I have. Could you please try the 6.2.41 on github to be sure?

**Comment by Quaap70** [comment]
I tried putting the APK of version 6.2.41 on the Google TV 4K. Unfortunately, the "send files to TV" app is not available on the Apple ecosystem, and I don't have any Android at my disposal. I've tried some other options, but Google and Apple don't really make that easy. If you have any suggestions, after all, you deal with this more often, I would love to hear them. I would be happy to test it out for you.

**Comment by ralves58** [comment]
> I tried putting the APK of version 6.2.41 on the Google TV 4K. Unfortunately, the "send files to TV" app is not available on the Apple ecosystem, and I don't have any Android at my disposal. 

.

Read this "How To" Guide (but I'm not sure they have tips for Apple iOS):
https://www.androidpolice.com/how-to-sideload-any-application-on-android-tv/

For me, I have a Chromecast WGTV 4K dongle and I install the Nova APK on the Chromecast from a Windows desktop computer (not a cell phone, I find it easier to use the computer), using the Android Debug Bridge (or ADB for short).

ADB comes with Android Platform Tools. You can download it for Windows, Mac-OS or Linux here:
https://developer.android.com/tools/releases/platform-tools

.

**Comment by Quaap70** [comment]
Thanks for the web links @ralves58 !

I tested version 6.2.41 and the bug when no subtitles could be found no longer occurred. I can now use the menu normally, without having to press the back button an extra time.
