### ISSUE TITLE
[Bug]: Play mode not working on SSD connected to TV

### ISSUE THREAD

**Issue by goevexx** [nova-video-player/aos-AVP#1033]
### Problem description

I've connected an SSD to my TV and I am going to play all videos in the same folder. Turning on play mode folder won't make the player play the next video. Instead, it's finished and I'm back on the detail screen.

### Steps to reproduce the issue

1. Play video
2. Change play mode to folder
3. Wait or forward to the end of the video

### Expected behavior

The next video of the folder in order should be played.

### Your phone/tablet/androidTV model

BRAVIA VH1

### Operating system version

Android TV 10

### Application version and app store

6.2.40-20231222.2306, Google Playstore

**Comment by courville** [comment]
Can you please recheck on 6.2.54? I applied some fixes earlier on some related parts of nova.

**Comment by goevexx** [comment]
> Can you please recheck on 6.2.54? I applied some fixes earlier on some related parts of nova.

I've installed 6.2.54 manually. The update didn't solve it.
