### ISSUE TITLE
Google Chromecast tv 4k [Bug]: 

### ISSUE THREAD

**Issue by porfavorhelp** [nova-video-player/aos-AVP#1035]
### Problem description

Latest update problem. It can not open the app in Google Chromecast tv 4k

### Steps to reproduce the issue

None

### Your phone/tablet/androidTV model

Google chromecast tv 4k

### Operating system version

Android 12

### Additional system information

None

### Debug logs

I don't know

**Comment by mschumacher69** [comment]
Try force stopping the app or reboot your Chromecast.

**Comment by courville** [comment]
If reboot does not work.
Could you please let me know if you have installed the application via google play or via github?
If this is via github, please install the **armeabi-v7a** release found [here](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.42) and let me know if it fixes your issue.

Cf. [discussion](https://www.reddit.com/r/NovaVideoPlayer/comments/18uvxyd/urgent_probl%C3%A8me_application_nova_vid%C3%A9o_player/)

**Comment by porfavorhelp** [comment]
I always install via Github. I installed this one v6.2.42 pre-release and
.41 but does not work. I did reboot but doesn't work too. Only .40 works

**Comment by courville** [comment]
@porfavorhelp please reinstall v6.2.42 **armeabi-v7a** and let me know if it works. I suppressed problematic releases (armeabi). If you did already please let me know.

**Comment by porfavorhelp** [comment]
Ok I will try

**Comment by porfavorhelp** [comment]
Thank you very much! Now is working!
