### ISSUE TITLE
[Bug]: dav勾选了保存密码依然无法保存密码

### ISSUE THREAD

**Issue by Mackerly** [nova-video-player/aos-AVP#1036]
### Problem description

NOVA Video Player_6.2.40-20231222.2308，can't save password when selected sava password in dav setting.

### Steps to reproduce the issue

**

### Expected behavior

==

### Your phone/tablet/androidTV model

mate 20 pro

### Operating system version

Android

### Additional system information

=

### Debug logs

=

**Comment by youring** [comment]
NOVA的操作逻辑有点不同寻常，
以下为安卓端添加webdav操作流程：
网络快捷方式--浏览网络共享--填入webdav信息，确定后，确保访问远端webdav正常--右上角菜单--添加为快捷方式
后续访问快捷方式即可。
