### ISSUE TITLE
[Bug]: external SRT not loaded when the source is network multimedia server

### ISSUE THREAD

**Issue by ponzaro** [nova-video-player/aos-AVP#1037]
### Problem description

Hi,
I am using my FritzBox 7590 AX also also as NAS with the embedded functionality. I have an USB drive attached to it. This is all being correctly recognized by Nova but the SRT file with subtitles is not being loaded, even if it has the same name of the video file. The subtitles are not recognized at all as they are not appearing pickable in the screen where you can start the playing.
If I try to open the same movie+SRT from a USB device everything is working fine and the subtitles are recognized and displayed.

### Steps to reproduce the issue

- Put the movie and SRT file in the same folder on a network multimedia server and try to enable subtitles

### Expected behavior

The SRT file should be recognized and enabled if requested, as it works when the files are on a USB device

### Your phone/tablet/androidTV model

Sony BRAVIA 4K VH2

### Operating system version

Android TV 10

**Comment by courville** [comment]
Which network share protocol are you using (e.g. UPnP or SMB)?

**Comment by ponzaro** [comment]
UPnP

**Comment by courville** [comment]
Cf. https://home.courville.org/nova_video_player-faq/index.html comment about "Which network shares are supported?":

> Nova has UPnP support but issues can be experienced with remote subtitles support (UPnP has no native support for srt files). Nova is reported not to be compatible with Serviio media server;

Please try to use SMB network share for good integration with nova.
