### ISSUE TITLE
[Bug]: Nova is unable to passthrough Multichannel PCM on Android 12

### ISSUE THREAD

**Issue by branches78** [nova-video-player/aos-AVP#1041]
### Problem description

My device (Homatics Box R 4K Plus) is connected directly to a Samsung TV with EARC support and the TV is connected to an AV receiver with EARC support as well, however, with recent releases, the Nova app is unable to detect that the TV has multichannel PCM passthrough support and it's downmixing it to stereo, other apps I use (Emby and Jellyfin) are able to detect it and passthrough the audio correctly.

This is happening only on Android 12 because with Android 11 the Nova app is able to passthrough multichannel PCM to the AV receiver correctly when the device I use (Realme 4K stick) is also connected directly to the same TV.

### Steps to reproduce the issue

N/A

### Your phone/tablet/androidTV model

Homatics Box R 4K Plus

### Operating system version

Android 12

### Application version and app store

v6.2.47

**Comment by phhusson** [comment]
Could you give us the result of `adb shell dumpsys media.audio_policy`
?

**Comment by branches78** [comment]
@phhusson I'm not an expert in ADB so I don't know what to do to run that command.

The app really needs a log section where we can extract a file and attach it here,

**Comment by courville** [comment]
There are logs that can be enabled but still need to be retrieved by adb...

Please refer to: https://github.com/nova-video-player/aos-AVP/wiki/Debugging and if need be use chatgpt.
Many of the issue reporters never used adb before and managed to take the leap of faith.

**Comment by courville** [comment]
@branches78, I do not have a EARC TV but I connected a Chromecast Google TV ("sabrina", Android 12) to my Samsung AV receiver via HDMI and with Android 12, nova is able to output multichannel PCM (EAC3, AAC 5.1 sources).
I know this is not the same setup as you.
Could you please try the same with your Homatics Box R 4K Plus and see if you get multichannel PCM output (i.e. not using passthrough with nova and being sure that downmixing to stereo is not forced in nova settings)?
If it does then this is due to EARC for some reasons and we will try to progress from there.

**Comment by branches78** [comment]
Hello @courville I forgot to clarify that I'm obviously getting multichannel PCM with the Nova app when the box is connected directly to the AV receiver but for some reason, the app stopped detecting that the TV also has multichannel PCM support on Android 12, I remember it was working with previous versions but I didn't pay attention on what version stopped working since I've been sideloading every single update you post on github.

Another thing I'm suspecting is that the box has been receiving security patches since it's still on beta, but I believe that doesn't have anything to do, still, I will try to discard or confirm that theory.

I will have to test old versions of Nova to see which one works but I will try to do that on the weekend.

**Comment by branches78** [comment]
I didn't have to wait until the weekend 🤭

I tested an old version (6.1.6) and it was the same, so I imagine something changed in the firmware of the device that renders the app unable to detect multichannel PCM, the thing is, Emby and Jellyfin are able to passthrough multichannel PCM so Nova should be able to do the same since it uses Exoplayer, correct?

The device is under the november 2023 security patch, however, the Realme stick on Android 11 has a security patch dated october 2023 and it's able to passthrough multichannel PCM as well.

Please let me know if you need anything else.

**Comment by branches78** [comment]
Turns out this problem is also present when the box is connected directly to the AV receiver, but as I already stated, it happens only on Android 12 with recent security patches, probably since the october 2023 security patch.

By the way @courville , the CCwGTV received a recent update to the december 2023 patch, could you please check again to see if you can still passthrough multichannel PCM the same way you did the other day?

**Comment by branches78** [comment]
I renamed the title of this bug report to link two issues with Android 12 on the same device, but I've been unable to get the logs with ADB.

**Comment by branches78** [comment]
> There are logs that can be enabled but still need to be retrieved by adb...
> 
> Please refer to: https://github.com/nova-video-player/aos-AVP/wiki/Debugging and if need be use chatgpt. Many of the issue reporters never used adb before and managed to take the leap of faith.

Can someone please help me to extract the logs, I tried to follow the instructions in the above link but they are somewhat confusing, Dolby TrueHD is still not passing through and multichannel PCM is still being downmixed to stereo.

**Comment by branches78** [comment]
So I was able to find out that Dolby TrueHD is passing through when the "force passtrough audio" is turned ON but it doesn't passthrough when it's OFF by decoding the audio to stereo PCM, therefore, I was finally able to get a log so you can finally fix this problem for good.

[Dolby TrueHD not working on Nova.log](https://github.com/nova-video-player/aos-AVP/files/15264226/Dolby.TrueHD.not.working.on.Nova.log)

**Comment by branches78** [comment]
I was able to get a log where Multichannel PCM it's still getting downmixed to stereo on latest versions of the app, please fix it.

[Multichannel PCM not working on Nova.txt](https://github.com/nova-video-player/aos-AVP/files/15264444/Multichannel.PCM.not.working.on.Nova.txt)

**Comment by branches78** [comment]
> Could you give us the result of `adb shell dumpsys media.audio_policy` ?

Answering to your request, there you have:

[dumpsys media.audio_policy.log](https://github.com/nova-video-player/aos-AVP/files/15264810/dumpsys.media.audio_policy.log)

**Comment by xitwid** [comment]
same problem

Device: Ugoos AM8
OS: Android 11
Nova Ver: 6.2.73

**Comment by branches78** [comment]
Will this issue be fixed for good?

I provided the requested logs so I just hope you guys pay attention to this issue.

Thank you.

**Comment by piter-pit** [comment]
Similar case for TCL tv on Android 12 and despite selected force passthrough it down mix 5.1 AAC to stereo. I believe even if avr does not support AAC it should be silence, tv itself down mix it? As a walk-around I suggested solution from wimu player where you can select what type of surround codecs you want to convert to AC3 or eAC3 which helped, but you need second player

**Comment by branches78** [comment]
The Homatics Box R 4K Plus has recently received Android 14 in the form of an alpha/beta version since I am part of the testers program they have and I still see that multichannel PCM is being downmixed to stereo by Nova, I'm attaching a new log so please try to fix this problem for good 🙏

[Nova log on Android 14 on Homatics Box R 4K Plus.log](https://github.com/user-attachments/files/18040175/Nova.log.on.Android.14.on.Homatics.Box.R.4K.Plus.log)

**Comment by branches78** [comment]
Multichannel PCM is finally working on version 6.3.10, in case that it breaks in future versions I will reopen this ticket.

Thank you for fixing this up!.
