### ISSUE TITLE
[Bug]: There is no network buffering when calling another player (mxplayerpro)

### ISSUE THREAD

**Issue by ksiwmwd** [nova-video-player/aos-AVP#1060]
### Problem description

There is no network when calling VLC and MXPLAYER player, and it can play normally when using nova.

### Steps to reproduce the issue

It can be reproduced every time you call another player.

### Your phone/tablet/androidTV model

Huawei mate40

### Operating system version

Hongmeng 3.0

### Application version and app store

6.2.52

**Comment by Parbler** [comment]
Similar issue with Phicomm N1(Android TV Box), CPU:  AArch64 : Cortex-A53 x 4.

Third party player(VLC/MPV/MXPlayer) not found in player selection. Only Nova and pre-installed player.

**Comment by courville** [comment]
@ksiwmwd,  can you please clarify what you mean by "there is no network" (what network protocol etc.)?

I can launch just player or mpv-android via nova and play remote network videos.

@Parbler, when enabling external video player in nova settings, I do have external players proposed on many certified android boxes. Note that it is the android framework that makes the player selection proposal. Perhaps the issue comes from your specific android firmware.

**Comment by rianjskis** [comment]
> @ksiwmwd，您能否澄清一下“没有网络”的含义（什么网络协议等）？
> 
> 我可以通过 nova 启动播放器或 mpv-android 并播放远程网络视频。
> 
> @Parbler，当在 nova 设置中启用外部视频播放器时，我确实在许多经过认证的 Android 盒子上建议了外部播放器。 请注意，是 android 框架提出了玩家选择建议。 也许问题来自于您特定的 Android 固件。

I use nova WebDAV protocol to play remote video using mxplayerpro,vlc without network buffering. With nova direct playback it's fine

**Comment by rianjskis** [comment]
> @ksiwmwd，您能否澄清一下“没有网络”的含义（什么网络协议等）？
> 
> 我可以通过 nova 启动播放器或 mpv-android 并播放远程网络视频。
> 
> @Parbler，当在 nova 设置中启用外部视频播放器时，我确实在许多经过认证的 Android 盒子上建议了外部播放器。 请注意，是 android 框架提出了玩家选择建议。 也许问题来自于您特定的 Android 固件。


In version 6.2.53 as well, after scraping the webdav movies and TVs, choosing to call an external player to play them will have no network, while using nova to play them directly will have no problem.

**Comment by rianjskis** [comment]
> @ksiwmwd,  can you please clarify what you mean by "there is no network" (what network protocol etc.)?
> 
> I can launch just player or mpv-android via nova and play remote network videos.
> 
> @Parbler, when enabling external video player in nova settings, I do have external players proposed on many certified android boxes. Note that it is the android framework that makes the player selection proposal. Perhaps the issue comes from your specific android firmware.

Reproduction method when not check the box: processing ". nfo" file scraping is completed, you can call the external player to play normally, if the scraping is completed after checking: processing ". nfo" file second scraping will appear to call the external player without network

**Comment by courville** [comment]
OK thus the problem is when using webdav protocol, external player is unable to play stream.

**Comment by rianjskis** [comment]
> 好的，问题是当使用 webdav 协议时，外部播放器无法播放流。
Hello. Did you fix it?

**Comment by courville** [comment]
I checked that on my pixel phone and on android tv, I can use external players such as just player and vlc to play videos on network smb or webdav shares.

Thus I might not understand the real issue you are experiencing.

**Comment by rianjskis** [comment]
> I checked that on my pixel phone and on android tv, I can use external players such as just player and vlc to play videos on network smb or webdav shares.
> 
> Thus I might not understand the real issue you are experiencing.

Using nova to mount the webdav protocol, there is no network buffering through the external player mxplayerpro, but there is no problem with direct playback using nova.

**Comment by courville** [comment]
@rianjskis, thanks for the clarification.
When using an external player, Nova exposes the video as an http stream to the external player.
It is up to the player to implement the right network buffering strategy to cope with this.
It seems that mxplayerpro is not up to the challenge of this task.
I am afraid that it is not on nova side to provide a remedy. Please contact mxplayerpro support about this issue.
It would be sad that a paid app could not handle it.
