### ISSUE TITLE
[Bug]: Minor Bug? Resuming Issue on Google TV

### ISSUE THREAD

**Issue by Quaap70** [nova-video-player/aos-AVP#1062]
### Problem description

When I binge-watch multiple episodes of a TV series and have to pause the player due to other commitments, it restarts from the first episode of that viewing session upon resuming. This issue **only** occurs if the Google TV has entered screen saver mode in the meantime; otherwise, it continues from where it was paused. In essence, if you leave the player paused for too long, allowing the Google TV to activate its screen saver, this problem arises. I'm unsure whether this is a bug with Nova or a limitation of Google TV.

### Steps to reproduce the issue

Watching multiple episodes back-to-back, pausing the player, and then resuming the video after a half hour break.

### Expected behavior

The player always resumes playback from where it was last stopped."

### Your phone/tablet/androidTV model

Google TV

### Operating system version

Android 12 Kernel 4.9.269

### Application version and app store

6.2.50

### Additional system information

This bug is not unique to this version of Nova; the same issue was also present in version 5. Therefore, I'm wondering if it might be a limitation of the Google TV Ambient Mode.

**Comment by courville** [comment]
I think this is a duplicate, that needs indeed attention (I can reproduce but failed so far to fix it). Let's close this issue and follow progress here https://github.com/nova-video-player/aos-AVP/issues/674
