### ISSUE TITLE
[Bug]: Nova is not present in the "open with" dialog

### ISSUE THREAD

**Issue by ansilent** [nova-video-player/aos-AVP#1095]
### Problem description

On Android TV 12 Nova is not present in the "open with" dialog in apps like Lampa TV, NUM. I think the problem is with the file association.

### Steps to reproduce the issue

I solved this problem by editing AndroidManifest.xml :
this code:

            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="file"/>
                <data android:scheme="content"/>
                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:host="*"/>
                <data android:mimeType="video/*"/>
                <data android:mimeType="application/sdp"/>
                <data android:mimeType="application/mp4"/>
                <data android:mimeType="application/vnd.apple.mpegurl"/>
                <data android:mimeType="application/vnd.apple.mpegurl.audio"/>
                <data android:mimeType="application/vnd.rn-realmedia"/>
                <data android:mimeType="application/vnd.rn-realmedia-vbr"/>
                <data android:mimeType="application/mpegurl"/>
                <data android:mimeType="application/x-mpegurl"/>
                <data android:mimeType="application/ogg"/>
                <data android:mimeType="application/x-ogg"/>
                <data android:mimeType="audio/mpegurl"/>
                <data android:mimeType="audio/x-mpegurl"/>
                <data android:mimeType="application/x-shockwave-flash"/>
                <data android:mimeType="application/x-bittorrent"/>
            </intent-filter>

replace to this:

            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="file"/>
                <data android:scheme="content"/>
                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:mimeType="video/*"/>
                <data android:mimeType="application/sdp"/>
                <data android:mimeType="application/mp4"/>
                <data android:mimeType="application/vnd.apple.mpegurl"/>
                <data android:mimeType="application/vnd.apple.mpegurl.audio"/>
                <data android:mimeType="application/vnd.rn-realmedia"/>
                <data android:mimeType="application/vnd.rn-realmedia-vbr"/>
                <data android:mimeType="application/mpegurl"/>
                <data android:mimeType="application/x-mpegurl"/>
                <data android:mimeType="application/ogg"/>
                <data android:mimeType="application/x-ogg"/>
                <data android:mimeType="audio/mpegurl"/>
                <data android:mimeType="audio/x-mpegurl"/>
                <data android:mimeType="application/x-shockwave-flash"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="file"/>
                <data android:scheme="content"/>
                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:host="*"/>
                <data android:mimeType="video/*"/>
                <data android:mimeType="application/sdp"/>
                <data android:mimeType="application/mp4"/>
                <data android:mimeType="application/vnd.apple.mpegurl"/>
                <data android:mimeType="application/vnd.apple.mpegurl.audio"/>
                <data android:mimeType="application/vnd.rn-realmedia"/>
                <data android:mimeType="application/vnd.rn-realmedia-vbr"/>
                <data android:mimeType="application/mpegurl"/>
                <data android:mimeType="application/x-mpegurl"/>
                <data android:mimeType="application/ogg"/>
                <data android:mimeType="application/x-ogg"/>
                <data android:mimeType="audio/mpegurl"/>
                <data android:mimeType="audio/x-mpegurl"/>
                <data android:mimeType="application/x-shockwave-flash"/>
                <data android:mimeType="application/x-bittorrent"/>
            </intent-filter>

The problem is in the line  `<data android:host="*"/>` in first block

### Your phone/tablet/androidTV model

Mecool KM2

### Operating system version

Android TV 12

**Comment by courville** [comment]
Thanks for proposing a solution to the problem.
Perhaps a better way would be to collapse the two via a special host data element for http/https only:
```
<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="file"/>
    <data android:scheme="content"/>
    <data android:mimeType="video/*"/>
    <data android:mimeType="application/sdp"/>
    <data android:mimeType="application/mp4"/>
    <data android:mimeType="application/vnd.apple.mpegurl"/>
    <data android:mimeType="application/vnd.apple.mpegurl.audio"/>
    <data android:mimeType="application/vnd.rn-realmedia"/>
    <data android:mimeType="application/vnd.rn-realmedia-vbr"/>
    <data android:mimeType="application/mpegurl"/>
    <data android:mimeType="application/x-mpegurl"/>
    <data android:mimeType="application/ogg"/>
    <data android:mimeType="application/x-ogg"/>
    <data android:mimeType="audio/mpegurl"/>
    <data android:mimeType="audio/x-mpegurl"/>
    <data android:mimeType="application/x-shockwave-flash"/>
    <data android:mimeType="application/x-bittorrent"/>
    <data android:scheme="http" android:host="*"/>
    <data android:scheme="https" android:host="*"/>
</intent-filter>
```
You can do a PR if you want that I will approve, or I can do the modification.

**Comment by ansilent** [comment]
Thenks for reply.

<intent-filter>
    <action android:name="android.intent.action.VIEW"/>
    <category android:name="android.intent.category.DEFAULT"/>
    <category android:name="android.intent.category.BROWSABLE"/>
    <data android:scheme="file"/>
    <data android:scheme="content"/>
    <data android:mimeType="video/*"/>
    <data android:mimeType="application/sdp"/>
    <data android:mimeType="application/mp4"/>
    <data android:mimeType="application/vnd.apple.mpegurl"/>
    <data android:mimeType="application/vnd.apple.mpegurl.audio"/>
    <data android:mimeType="application/vnd.rn-realmedia"/>
    <data android:mimeType="application/vnd.rn-realmedia-vbr"/>
    <data android:mimeType="application/mpegurl"/>
    <data android:mimeType="application/x-mpegurl"/>
    <data android:mimeType="application/ogg"/>
    <data android:mimeType="application/x-ogg"/>
    <data android:mimeType="audio/mpegurl"/>
    <data android:mimeType="audio/x-mpegurl"/>
    <data android:mimeType="application/x-shockwave-flash"/>
    <data android:mimeType="application/x-bittorrent"/>
    <data android:scheme="http" android:host="*"/>
    <data android:scheme="https" android:host="*"/>
</intent-filter>

Unfortunately it doesn't work for me.

**Comment by courville** [comment]
Indeed, will make the modifs and test.
