### ISSUE TITLE
[Bug]: Opensubtitles ERR 200

### ISSUE THREAD

**Issue by Mandrake1er** [nova-video-player/aos-AVP#1114]
### Problem description

Unvalaible service (ERR 200) when trying to download ST from opensubtitles

### Steps to reproduce the issue

Just try to download ST.
- first answer from opensubtitles is unvailable service
- after that (and until I kill and relaunch the app), Nova doesn't seem to ask opensubtitles and answer directly unvailable service (ERR 200).

### Expected behavior

Get the list of downloadable ST.

### Your phone/tablet/androidTV model

TV Sharp

### Operating system version

Android TV 11

### Application version and app store

6.2.55 & 6.2.56 from Github

**Comment by courville** [comment]
Thank you @Mandrake1er, it is indeed an issue and somehow it was working before. It could be a change of behavior on opensubtitles.com login json response inducing the issue.

Fixed by https://github.com/nova-video-player/aos-Video/commit/cdfd66e3904c9aef7d3f6dcf8d530471a8e37070

**Comment by courville** [comment]
6.2.57 https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.57 should fix the issue.
Reopen if not the case please.

**Comment by Mandrake1er** [comment]
Yes. This release fixed the issue. Thanks a lot.
