### ISSUE TITLE
[Bug]: error retrieving subtitles

### ISSUE THREAD

**Issue by Quaap70** [nova-video-player/aos-AVP#1115]
### Problem description

I've been encountering an issue for the past few days where I receive an error message: Subtitle web service outage (ERR200) indicating a failure with the subtitle web service when I try to retrieve subtitles. This problem appears to have begun following the most recent update to Nova v6.2.55. Occasionally, I also receive notifications that opensubtitles.**org** is currently offline, which I believe led us to transition to opensubtitles.**com** at the beginning of this year. 

Since I'm able to log in manually to opensubtitles.com without issues, it seems the service itself is functioning properly. Could the problem be related to the API?

### Steps to reproduce the issue

Click button: Get subtitles online

### Expected behavior

Get subtitles online

### Your phone/tablet/androidTV model

Google TV 4K

### Operating system version

Android 12 Kernel 4.9.269

### Application version and app store

v6.2.55 from Google Play Store

**Comment by courville** [comment]
Thanks for pointing this out. See https://github.com/nova-video-player/aos-AVP/issues/1114
I think it has just been fixed in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.57 rolling out.

**Comment by Quaap70** [comment]
Thanks for your answer! I previously looked to see if this bug had already been reported, but couldn't find it. It seems that you have recently started using an automated system for reporting bugs, as the list seems longer than before. I now see that's Sentry.
