### ISSUE TITLE
[Bug]: TMDB scapper - Series not found

### ISSUE THREAD

**Issue by JGomsss** [nova-video-player/aos-AVP#1128]
### Problem description

Hi,

The "orphan black echoes" series is not found on TMDB although it is there :
https://www.themoviedb.org/tv/206916-orphan-black-echoes

Thanks,

### Steps to reproduce the issue

Check for new files or manually
![image](https://github.com/nova-video-player/aos-AVP/assets/28355812/cb711f70-0490-45bb-8076-982e9768661b)

### Your phone/tablet/androidTV model

HP Chromebook x360 12

### Operating system version

Android 11 on ChromeOS 121

### Application version and app store

6.2.57

**Comment by courville** [comment]
Thanks for reporting: what I see in the debug logs is that the show is found but discarded because of missing airdate:
```
SearchShowParser org.courville.nova D getSearchShowParserResult: set aside Orphan Black: Echoes because air date is missing
```

**Comment by courville** [comment]
Turns out that nova was not considering videos with empty air date reported by tmdb. This is fixed now. Next release should identify Orphan Black Echoes tvshow.

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.61

**Comment by JGomsss** [comment]
It works on manual search on each files but doesn't work on global indexing

**Comment by JGomsss** [comment]
> https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.61

@courville It works on manual search on each files but doesn't work on global indexing

**Comment by courville** [comment]
On my side it works if I rescan the non indexed folder and also adding new Orphan Black Echoes videos.
