### ISSUE TITLE
[Bug]: Unable to download subtitles

### ISSUE THREAD

**Issue by lichengxun** [nova-video-player/aos-AVP#1137]
### Problem description

I can't download subtitles in nova. Have registered for an account at opensubtitles.com and use a login and password instead of an email address, and I've changed versions of nova, neither of which will download the subtitles. And I've also tried using v6.2.57 and still can't download subtitles.
It is possible to download subtitles in opensubtitles.com through the web page without logging in, so why can't I log in after using an account instead? Is it possible to optimize the code so that if there is a problem with the account or something, the download is not done through the account (I can't be sure if I'm logged in properly even after entering my account password in nova, can there be a test button to check if the account and the service are working properly, and the priority is to ensure that the subtitles are downloaded.

### Steps to reproduce the issue

Download v6.2.57 then log in to opensubtitles.com with your account password. Find a movie that is confirmed to have subtitles and download the subtitles.

### Your phone/tablet/androidTV model

honor tv

### Operating system version

android

### Application version and app store

v6.2.57 and others

**Comment by mschumacher69** [comment]
@courville I'm having the same issue, is this supposed to be working?

**Comment by mschumacher69** [comment]
Never mind, the subtitle language wasn't set in settings, it's working now.

**Comment by courville** [comment]
It should be working now. And due to transient of releases there were issues like @mschumacher69 noticed. Closing the issue and please comment if not solved.

**Comment by okey2k** [comment]
For Chinese users, don't be confused in the subtitles setting, you should chose Chinese(Sim) or Chinese(Trad) in the second half of the language list instead of Chinese at the Top, which will give you nothing for most subtitles.

**Comment by zhangmax66** [comment]
我还是同样的问题，登录不了，也下载不了字幕
