### ISSUE TITLE
[Bug]: Random names are listed for subtitles in subtitles list

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#1144]
### Problem description

In the subtitles selection list the SRT subtitles sometimes get listed with strange random 3 letter names.
For example: god, Ntb, Atm ...

### Steps to reproduce the issue

I do not see any particular reason for this so far, but it seems to happen in movies with integrated subtitles.

### Expected behavior

The subtitle extension should be listed - SRT, SUB etc.

### Your phone/tablet/androidTV model

TCL C845

### Operating system version

Google TV 12

### Application version and app store

Latest from Google Playstore

### Additional system information

This happens on all my devices and is not related to the hardware.

**Comment by courville** [comment]
Should be fixed now in 6.2.72 (I think). Now logic for identifying language is based on subtracting from sub filename the video filename without extension with a "." added which would lead to SRT if result is empty or the language inferred from the resulting string (e.g. video.mkv + video.srt -> SRT, video.mkv + video.eng.srt -> English or video.eng.HI.srt -> Engligh (HI) for hearing impaired). Please reopen if it is not the case.

**Comment by JJD2K** [comment]
@courville 
Thank you for your fix. This was a minor issue which does not impact usage.
I am looking forward to an important fix: https://github.com/nova-video-player/aos-AVP/issues/1177
Cheers.
