### ISSUE TITLE
[Bug]: External srt subtitles not displaying

### ISSUE THREAD

**Issue by vikingloudmouth** [nova-video-player/aos-AVP#1146]
### Problem description

This is a duplicate of [https://github.com/moneytoo/Player/issues/490](https://github.com/moneytoo/Player/issues/490). I'm unclear if the problem is in this app or Just (Video) Player, but thought I'd try here as it has got no attention.

When using Just (Video) Player to do the playback via the "Allow using another video player", external subtitles (srt) are shown in the list of subtitles and selected, but don't display onscreen

### Steps to reproduce the issue

1. Open a video (from a network source, tested using both smb and webdav) with external subtitles through Nova Video Player using the "Allow using another video player" option set to Just (Video) Player.
2. Confirmed that external subtitle track is shown and selected in list of subtitles in Just (Video) Player
3. Subtitles don't display onscreen

### Expected behavior

The selected subtitles displays onscreen.

### Your phone/tablet/androidTV model

Sony X90J

### Operating system version

Google TV

### Application version and app store

6.2.57 via play store

**Comment by mitz1** [comment]
Hello!
Look here:
https://github.com/nova-video-player/aos-AVP/issues/1162 

https://github.com/nova-video-player/aos-AVP/issues/897

**Comment by courville** [comment]
A better support for passing subs to just player is available in 6.2.72 please try and reopen if not ok. JustPlayer might have difficulties detecting subtitle encoding though.
