### ISSUE TITLE
Auto select external subtitle works only when the movie has no embedded subtitles. If there are built-in it selects English, which doesn't make sense if you put external subtitles with the same name in the folder.

### ISSUE THREAD

**Issue by mitz1** [nova-video-player/aos-AVP#1152]
Auto select external subtitle works only when the movie has no embedded subtitles. If there are built-in it selects English, which doesn't make sense if you put external subtitles with the same name in the folder.
Tested on many Android / Fireos devices with v6.2.63 with SMB from router.

_Originally posted by @mitz1 in https://github.com/nova-video-player/aos-AVP/issues/897#issuecomment-1982643604_

**Comment by courville** [comment]
#897 has not been closed thus I assume this is a duplicate. But thanks for reminding me of the issue.
