### ISSUE TITLE
[Bug]: External storage not scanned (permanent access permission not available)

### ISSUE THREAD

**Issue by leogh73** [nova-video-player/aos-AVP#1159]
### Problem description

Hello.
I was using Nova player to watch content from an USB HDD drive on an old TV Box with Android 8, zero problems. But now I'm trying to do the same with an Nvidia Shield on Android 11. I granted the file access permission, Nova scans for media files for 2 seconds and stops. It shows my HDD drive and I can access the folders but it shows no files.
I tried other 2 players and a file explorer: **I had to grant permanent access permission for them to read the external storage properly. But I can't grant permanent access to Nova Player**, I can grant only the permission to access the files while the app it's open, which clearly it's not enough.
I hope it can be fixed soon. I really like my Nvidia Shield and I loved this player, but now I can't use it anymore.
Kind regards.

### Steps to reproduce the issue

When Nova starts for the first time, I grant the file access permission, it scans for media files for 2 seconds, it stops and that's it.

### Expected behavior

It should read the external storage and get the info for the media from the internet.

### Your phone/tablet/androidTV model

Nvidia Shield Pro 2019

### Operating system version

Android 11

**Comment by courville** [comment]
Nova is not granted `MANAGE_EXTERNAL_STORAGE` permission by Google.
Please refer to https://home.courville.org/nova_video_player-faq/index.html section "Visibility of external USB drive on Nvidia Shield" and "Some files located on local/USB storage are not seen by nova a.k.a. API31 debacle".
Note that media files visibility on local storage is thus the one provided by Android media database.
You thus need to allow Android to index external USB drives for nova to access and see these files.
This is feasible on nvidia shield as explained in the FAQ.

**Comment by leogh73** [comment]
> Nova is not granted `MANAGE_EXTERNAL_STORAGE` permission by Google. Please refer to https://home.courville.org/nova_video_player-faq/index.html section "Visibility of external USB drive on Nvidia Shield" and "Some files located on local/USB storage are not seen by nova a.k.a. API31 debacle". Note that media files visibility on local storage is thus the one provided by Android media database. You thus need to allow Android to index external USB drives for nova to access and see these files. This is feasible on nvidia shield as explained in the FAQ.

It's weird that other players can access the HDD by just granting the permission when they start for the first time, but not Nova. It was like that on Android 8, but not on 11. Anyway, I'l try that and comment again. Thanks a lot. :)

**Comment by leogh73** [comment]
> Nova is not granted `MANAGE_EXTERNAL_STORAGE` permission by Google. Please refer to https://home.courville.org/nova_video_player-faq/index.html section "Visibility of external USB drive on Nvidia Shield" and "Some files located on local/USB storage are not seen by nova a.k.a. API31 debacle". Note that media files visibility on local storage is thus the one provided by Android media database. You thus need to allow Android to index external USB drives for nova to access and see these files. This is feasible on nvidia shield as explained in the FAQ.

It works. I don't understand why other players don't need that option enabled to read the HDD but Nova does. Anyway, thank you very much. :)

**Comment by leogh73** [comment]
> Nova is not granted `MANAGE_EXTERNAL_STORAGE` permission by Google. Please refer to https://home.courville.org/nova_video_player-faq/index.html section "Visibility of external USB drive on Nvidia Shield" and "Some files located on local/USB storage are not seen by nova a.k.a. API31 debacle". Note that media files visibility on local storage is thus the one provided by Android media database. You thus need to allow Android to index external USB drives for nova to access and see these files. This is feasible on nvidia shield as explained in the FAQ.

Another question: where are the playback speed controls?? There's some content that I watch at 1.5x. Nova says it has the option to change the playback speed. But once enabled, the options menu on the video, it's exactly the same as before, I thought the playback speed controls would be there. I can't find them anywhere. It's that feature only available on some devices or what?? Cheers.

**Comment by courville** [comment]
Playback speed only works when not in passthrough.

**Comment by leogh73** [comment]
> Playback speed only works when not in passthrough.

I'm not sure what that is, but it doesn't matter. I have other 2 video players installed. I can watch that content at 1.5x perfectly fine on one of them. Anyway, your video player it's amazing. Keep up the good work. :)

**Comment by Patrick-Ze** [comment]
I understand the unfair treatment you have experienced regarding the `MANAGE_EXTERNAL_STORAGE` permission. I hope you will soon regain the necessary permissions to restore full functionality to your app.
For those looking to use a version with this permission, you can download version [v6.2.25](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.25)
