### ISSUE TITLE
[FEAT]: Please add the ability for PIP. (Picture in picture)

### ISSUE THREAD

**Issue by joewilliams007** [nova-video-player/aos-AVP#1171]
### Description

A miniplayer for picture in picture (pip) would be great, allowing for writing notes or doing anything while watching a movie.

**Comment by phhusson** [comment]
It already supports windowed mode if that's the question?
It doesn't support playing two videos at the same time (which is usually what PIP refers to), but that doesn't seem to be your question

**Comment by joewilliams007** [comment]
oh your right i didnt notice that. i expected it to be as in youtube or netflix, opening automatically ones going to your home launcher.
