### ISSUE TITLE
[Bug]: Subtitle display issue

### ISSUE THREAD

**Issue by oditian** [nova-video-player/aos-AVP#1178]
### Problem description

1. Captions in H265 format cannot be displayed
![Snipaste_2024-04-20_21-41-48](https://github.com/nova-video-player/aos-AVP/assets/37031727/756f61fe-0651-4f9f-a2de-804524da2bda)

2. Bilingual subtitles cannot be displayed side by side
![Snipaste_2024-04-20_21-44-38](https://github.com/nova-video-player/aos-AVP/assets/37031727/73faa1e4-b957-4348-93f9-62fec07002b3)

### Steps to reproduce the issue

nova vs nplayer

### Your phone/tablet/androidTV model

XiaoMi

### Operating system version

Android13

**Comment by CompactNet** [comment]
这个播放器暂不支持pgs格式的字幕，也不支持ass特殊样式。

**Comment by courville** [comment]
PGS subtitles are not yet supported cf. https://github.com/nova-video-player/aos-AVP/issues/47
