### ISSUE TITLE
[Bug]: Subtitles always on when defualt is off

### ISSUE THREAD

**Issue by Cowboy1968** [nova-video-player/aos-AVP#1181]
### Problem description

Hi,
My Nova on a stock NVIDIA Shield pro 2019 was updated to the newest version 6.2.69.  Everything appears to be working great except for the subtitles.  I have hide subtitles by default checked as always , but subtitles now always show (this settings always worked previously). Additionally, when I go to settings and select no subtitles while watching a show, just selecting the no subtitles radio button does not register a click, I have to go to the selected subtitle first, click it, then I can go back to the no subtitles and select it.  

This is also happening on my Chromecast HD running Android 12 ver STTL240206.002

### Steps to reproduce the issue

This always happens in this version, hide subtitles is checked in settings, but subtitles show Tested it on both shields and a Chromecast HD all have this issue

### Expected behavior

No subtitles should show except for any hard coded into the video stream

### Your phone/tablet/androidTV model

Nvidia Shield Pro 2019

### Operating system version

Android 11 

### Application version and app store

6.2.69 Playstore Version

### Additional system information

Android 11 9.2.0(33.2.0.201)

**Comment by courville** [comment]
Should be fixed in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.70

**Comment by Cowboy1968** [comment]
> Should be fixed in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.70

Awesome Thank You, I will install and try it out later tonight!

**Comment by Cowboy1968** [comment]
> Should be fixed in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.70

Hi,
I just installed the newest version on my Shield by updating Nova but nothing changed.  Should I do a clean install?

**Comment by courville** [comment]
No need to clean, it should work...
Quick question: did you test embedded subs (I check on external subs)?
I will investigate.

**Comment by Cowboy1968** [comment]
Hi,

I don’t use external subs ( I assume you mean the ones that you can download within the app?).  I just use whatever subs are included with the tv show or movie, when you go to subs and it will show a list of included subs automatically.  Not all movies/shows have them, but some do.

Thanks

**Comment by Cowboy1968** [comment]
Hi, just to add there seems to be an issue when scanning in new shows.  They scan in fine but do not show in the newley added section, they do show up in the appropriate section though (tv/movies).

Also, the subs don't seem to be appearing anymore (still double checking that as not all shows I download have them) but the radio button is still highlighted on the first sub in the list.

Thanks so Much

**Comment by courville** [comment]
Please try https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.71

**Comment by Cowboy1968** [comment]
> Please try https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.71

Hi,
Thank you ,its working great now!  Have a Great Day
