### ISSUE TITLE
Folder in Google TV

### ISSUE THREAD

**Issue by aszksbdje** [nova-video-player/aos-AVP#1196]
### Description

Foldered serial is messed. We have serial movie and the folder management need some improvement.

1. May be we can change info for the whole folder not just for per episode files.
![PXL_20240519_180015362](https://github.com/nova-video-player/aos-AVP/assets/16359705/e4446119-0e78-47a7-809b-28b8af5ee52f)
2. Add name in source so we can see what episode we play. For now it only show resolution, audio, and size. 
![PXL_20240519_180028635](https://github.com/nova-video-player/aos-AVP/assets/16359705/fbe2691f-ca3f-4077-b942-877ad3fc3efb)
3. Add short option for source. The movie order is messed episode.
4. And how to add movie info while there is not exist in the search. Or maybe this video player is not serial able. In my case there is no Larva Animation. My number 1 issue may be can fix this

**Comment by phhusson** [comment]
Can you share the name of the files and the name of the folder they're in?

**Comment by aszksbdje** [comment]
My name file is larva 1, 2, etc. and the folder is LARVA.

And one more. There is no folder play. Maybe can add folder play too. Like when I want to play tom jerry. It stopped and not going to play next episode. There is Folder option in Play Mode but doesn't work.

Folder name "Tom and Jerry Collection", file name  "001 Title" etc.

![17161174460603702943626741031640](https://github.com/nova-video-player/aos-AVP/assets/16359705/bebcbe60-eb02-4b0c-b675-1a4347e77dc6)

**Comment by aszksbdje** [comment]
> My name file is larva 1, 2, etc. and the folder is LARVA.
> 
> And one more. There is no folder play. Maybe can add folder play too. Like when I want to play tom jerry. It stopped and not going to play next episode.
> 
> Folder name "Tom and Jerry Collection", file name "001 Title" etc.
> 
> ![17161174460603702943626741031640](https://private-user-images.githubusercontent.com/16359705/331867143-bebcbe60-eb02-4b0c-b675-1a4347e77dc6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMTgwNzAsIm5iZiI6MTcxNjExNzc3MCwicGF0aCI6Ii8xNjM1OTcwNS8zMzE4NjcxNDMtYmViY2JlNjAtZWIwMi00YjBjLWI2NzUtMWE0MzQ3ZTc3ZGM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDExMjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyNjFkYmQxNDA0NTBkYTFlMjk0NmZhN2Y0OGNiMzEzMDIyMjBhMGUxNGM2Yzg0Y2RhYTQyOWQyNjVjODlhOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1umagDm4s4UvWUbkO0xjD9OL0OBMi8oDu1v4io5dROk)

At least show movie thumbnail will be awesome. 🙈

**Comment by Philofil92** [comment]
For Tom and Jerry, it's normal, you simply don't respect the naming of the TMDB database, and even more so if you add a 001 with 2 spaces plus file name!!! For example, rename your 1st Tom to 001. Puss gets the boots (1940).mp4 and I guarantee you that he will find it! For series like Larva, you must also strictly respect the information in the TMDB database

**Comment by aszksbdje** [comment]
Ohh.. Now I know the problem. Thank You.
