### ISSUE TITLE
[Bug]: Scraped the wrong show for Eric 2024

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#1217]
### Problem description

The filenames are Eric.2024.S01E01, Eric.2024.S01E02, etc... but it scraped it as Eric Emmanuel Schmitt Bungalow 21 (2024) for some reason. If I try to change info for all episodes, it also detects it as Eric Emmanuel Schmitt Bungalow 21 (2024) in the search bar, I have to manually type Eric in the search bar for it to find the correct show (Eric 2024).

Here are some screenshots for your reference:
![PXL_20240601_171225558](https://github.com/nova-video-player/aos-AVP/assets/461871/5a0f2579-1391-4ef4-ab1c-5a6c1f71f210)
![PXL_20240601_171233977](https://github.com/nova-video-player/aos-AVP/assets/461871/4477c191-ad20-439b-8add-749e7248aa39)
![PXL_20240601_171253855](https://github.com/nova-video-player/aos-AVP/assets/461871/7a7059db-0c3a-4aef-b60c-c217f927d362)

### Steps to reproduce the issue

As described above.

### Your phone/tablet/androidTV model

CCwGTV

### Operating system version

Android 12

### Application version and app store

v6.2.79 from GitHub

**Comment by Philofil92** [comment]
Hello, Nova has nothing to do with your problem!
The naming of your file does not respect the "name SXXEXX.XXX" rule of the TMDB database.
In the event of a problem with the "film" or "series" description, the first thing to do is not to open an incident with Nova, but rather to check the exact name of the film or series in the TMDB database and do copy/paste the file name. If for films, it's easy to do...For series, it's particularly annoying...(you already have to be able to find the series! and that's not always the case!)

I will give you the exact name of your series which will allow you to have the exact description...I guarantee that it will work!!!

Eric S01E01 (2024).MKV
Eric S01E02 (2024).MKV
Eric S01E03 (2024).MKV
etc...etc...etc...

**Comment by Philofil92** [comment]
You have to tell your friend "KONTRAST" to be careful with the naming of his files...Everyone will save time... !!!

**Comment by mschumacher69** [comment]
There's nothing wrong with the filename, all scene releases use this filename format (Title.Year.SXX.EXX.XXX) and they all work fine except Eric.2024.S01E0X...

**Comment by Philofil92** [comment]
You don't understand anything... What is authentic is not what you believe works, or what worked, what is authentic is respecting the naming rule of the TMDB database ! Open an incident on TMDB, they will answer you the same thing...

**Comment by mschumacher69** [comment]
Lol you're clueless. This is obviously not a filename issue because the filename is clear, it has the series title and series year which is all you need to scrape from TMDB. If you search manually and type Eric 2024, you would find it. But for some reason, when Nova parses the file name, it is sending Eric Emmanuel Schmitt Bungalow 21 (2024) instead of Eric (2024) as can be seen by the 3rd screenshot above.

FYI, Nova processes the file names before sending them over to TMDB, Nova doesn't send the file name as it is, it parses it first and converts it into the string that TMDB understands in the format that you mentioned above, but for some reason, it is not parsing Eric.2024.S01E0X correctly.

**Comment by Philofil92** [comment]
If you're convinced of your stupidity, I shouldn't have helped... I bet you didn't even bother to test what I told you. You prefer to trust your pirated files that you recover from who knows where...

**Comment by phhusson** [comment]
@Philofil92 Seriously stfu. Is the filename correct? Yes. Is the recognized show incorrect? Yes.

So yes there is a bug.

Also insulting people is never okay.

**Comment by Philofil92** [comment]
Here is the proof in pictures...And I didn't insult anyone! I just said he was stupid...

![Serie Eric](https://github.com/nova-video-player/aos-AVP/assets/116804123/a7f83574-c1ef-4327-9aee-c8c62bb5506d)
![Serie 2](https://github.com/nova-video-player/aos-AVP/assets/116804123/bf4293ed-c32e-47bd-82d8-43980b16b5f4)
![Serie 3](https://github.com/nova-video-player/aos-AVP/assets/116804123/f01a51ee-93fa-46f6-b234-70089ba23c00)

**Comment by phhusson** [comment]
The proof... of what? That there is a bug? Yeah we already established that before.

The file naming convention used by @mschumacher69 is the standard naming convention from the scene, which keeps the information of the provenance of the file, unlike the one you're using.

**Comment by courville** [comment]
Logs show regression in terms of year matching perhaps linked with recent code refactoring.
The search result for "Eric 2024" is correct and matches tmdb response https://www.themoviedb.org/search/tv?query=Eric%202024

**Comment by courville** [comment]
Turns out that only year between parenthesis was processed not to interfere with filename of tvshows that contains years (yes it exists: https://www.imdb.com/search/keyword/?keywords=year-in-title&sort=moviemeter,asc&mode=detail&page=1&title_type=tvSeries&ref_=kw_ref_typ).
The solution to get both treated is to add after filename cleaning, year between parenthesis extraction to check if there is a year 19xx or 20xx at the very end of the resulting string. This should do the job and make it work with standard scene naming. I will push something tonight along this strategy.

**Comment by Philofil92** [comment]
Et bien, je suis bien content ! La solution que j'ai donné n'est pas la mienne...Mais celle que m'a donnée le Team TMDB pour ne pas avoir de soucis de description avec les séries (Nom de série avec des noms identiques ou année communes (Nom de série S01E01 (année).xxx etc...etc...)). Je n'ai jamais dit que c'était la solution ultime! Il y en a sans doute d'autres et peut-être meilleurs. Et Nova doit gérer cela à sa manière et plus large et doit prendre en compte sans doute plus de paramètres.

J'en ai dépanné pas mal ici avec cette solution et ils m'ont toujours remercier!

Avec le temps, je dois être susceptible ou j'ai l'esprit bien Français!...Mais c'est la 1ere fois qu'un participant me rie au nez et ne prend même pas la peine de tester une solution que je donne et partage très amicalement!

Y a au moins mon "ami" qui va devoir se taper la traduction dans sa langue maternel...

**Comment by courville** [comment]
Please test https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.80
This should do with torrent downloaded tvshow episodes not renamed like it should be with year between parenthesis.

**Comment by mschumacher69** [comment]
> J'en ai dépanné pas mal ici avec cette solution et ils m'ont toujours remercier!
> 
> Avec le temps, je dois être susceptible ou j'ai l'esprit bien Français!...Mais c'est la 1ere fois qu'un participant me rie au nez et ne prend même pas la peine de tester une solution que je donne et partage très amicalement!
> 

Maybe next time don't call other people stupid... Anyway, no one ever said that your "solution" doesn't work, it's just that it's not a solution, it's just a workaround. No one is gonna go rename all their files as you suggested. The real solution it to update Nova to handle those filenames properly, which is what @courville did, thanks for that.
