### ISSUE TITLE
[Bug]: when searching "暗河传" in tmdb, program exits unexpectedly

### ISSUE THREAD

**Issue by alonginwind** [nova-video-player/aos-AVP#1223]
### Problem description

6.2.81 when searching "暗河传" in tmdb, program exits unexpectedly
6.2.69 does not have this issue

### Steps to reproduce the issue

searching "暗河传" in changing group or openning a tv show named "暗河传-S01E18.mp4"

### Your phone/tablet/androidTV model

xiaomi 11

### Operating system version

android 14

### Application version and app store

6.2.81 from github

**Comment by alonginwind** [comment]
6.2.78 is ok, 6.2.79, 6.2.80 and 6.2.81 have same issue.

**Comment by courville** [comment]
I just tried with french locale setting and it works on my side with video on local storage.
Could you please let me know which locale you use (I guess Chinese) and also where the files are located (local storage, remote network share type)?

**Comment by alonginwind** [comment]
Yes, I use chinese. My files are located on remote network(alist). I use webdavs method.

**Comment by yaoyao5128** [comment]
v6.2.79 release
Use jupnp 3.0.2 for UPnP stack instead of deprecated cling
v6.2.74 release
Revert from jupnp to cling because of errors seen on sentry
v6.2.72 release
Use jupnp 3.0.2 instead of cling for UPnP

**errors seen on sentry with v6.2.79~v6.2.82**

**Comment by courville** [comment]
I have carefully checked the difference in all the repos between v6.2.78 (ok version) and v6.2.79 (nok version) and there is really very little difference and none justifying a change of behavior.
Would you be able to take a adb logcat when the app is crashing to report crash logs?

However I see that just before there is the sardine-android update for webdavs (this could be the issue).

**Comment by courville** [comment]
Could you please try this test build with previous sardine-android version: https://drive.google.com/file/d/13BzyYqbsqap7VUA8XJqWshEX0oTJJqmq/view?usp=sharing ?

**Comment by alonginwind** [comment]
> Could you please try this test build with previous sardine-android version: https://drive.google.com/file/d/13BzyYqbsqap7VUA8XJqWshEX0oTJJqmq/view?usp=sharing ?

This version works very well.

**Comment by courville** [comment]
Thanks for the confirmation this is thus indeed sardine-android upstep. Let's revert this for now.
