### ISSUE TITLE
[Bug]: Subtitles always on when defualt is off  Like in Report #1181

### ISSUE THREAD

**Issue by Cowboy1968** [nova-video-player/aos-AVP#1234]
### Problem description

Hi,
My Nova on a stock NVIDIA Shield pro 2019 was updated to the newest version 6.2.87. Everything appears to be working great except for the subtitles. I have hide subtitles by default checked as always , but subtitles now always show (this settings always worked previously). 

This is similar to Bug Report 1181 but now when I go to settings, it shows that No Subtitles radio button is selected (but subtitles are still being shown, and I have to then select the first subtitles in the list, then go back to No Subtitles to turn off Subtitles.

This is also happening on my Chromecast HD running Android 12 ver STTL240206.002

### Steps to reproduce the issue

This always happens in this version, hide subtitles is checked in settings and no Subtitles radio button is selected in each individual video file when playing, but subtitles show Tested it on both shields and a Chromecast HD all have this issue

### Expected behavior

No subtitles should show except for any hard coded into the video stream

### Your phone/tablet/androidTV model

Nvidia Shield Pro 2019

### Operating system version

Android 11

### Application version and app store

6.2.87 Playstore Version

### Additional system information

Android 11 9.2.0(33.2.0.201)

**Comment by courville** [comment]
You are right and I noticed it too: this is a regression that I will fix that comes from multiple refactoring of the subtitles code I did. I need to re-re-fix it.

**Comment by courville** [comment]
It should be fixed with https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.88
