### ISSUE TITLE
Unable to login opensubtitles when providing correct credentials 

### ISSUE THREAD

**Issue by AmirYa412** [nova-video-player/aos-AVP#1249]
### Problem description

I am unable to download subtitles from opensubtitles more than 5 times. I went to the settings, provided my open subtitles account credentials, but it just doesn’t work. 

I am able to login fine with the same credentials on web, but on Nova player I get the error “incorrect credentials or service not available.”

### Steps to reproduce the issue

Try to login opensubs user in Nova player settings.

### Your phone/tablet/androidTV model

GoTV

### Operating system version

Android

![image](https://github.com/user-attachments/assets/e59a949c-c57f-43a7-a874-91d555e26a3c)

**Comment by courville** [comment]
Are you using opensubtitles.com credentials (opensubtitles.org is not valid any longer due to API evolution constraints on opensubtitles cf. https://home.courville.org/nova_video_player-faq/index.html)?

**Comment by AmirYa412** [comment]
@courville I was using .org credentials.

I exceeded the quota today, after your comment I went ahead and created a user on .com host. I logged in(didn't saw the error I've seen before so I assume it worked).

When I try to download a subtitle, I still get the message exceeded quota.

**Comment by AmirYa412** [comment]
Update: after quota reset I can download 20 subs. I guess this is normal for free users, @courville thanka for your help, can close this issue.
