### ISSUE TITLE
[Regression?] PiP does not work in 6.2.90

### ISSUE THREAD

**Issue by knight-ryu12** [nova-video-player/aos-AVP#1252]
### Problem description

When I tries to grant permission of Overlay window, it does not appear in the setting intent window.

### Steps to reproduce the issue

1. Open any video.
2. Press burger list button (three dots on top right)
3. Press `Window mode` button
4. Press Allow
5. Setting intent opens
6. It does not appear in the list of apps to grant permission to

### Expected behavior

It should be able to (let alone list) grant permission.

### Your phone/tablet/androidTV model

Pixel 7

### Operating system version

Android 14

### Application version and app store

6.2.90 Appstore

**Comment by knight-ryu12** [comment]
Noticed that in the AndroidManifest.xml, SYSTEM_ALERT_WINDOW permission is missing.

Also, it does work on 6.2.5x... maybe a missing permission declaration?

**Comment by knight-ryu12** [comment]
Just compiled and added that permission; permission appeared... Hmm.
It shouldn't be necessary, should it?

**Comment by courville** [comment]
@knight-ryu12, thanks for the hint. I thought that SYSTEM_ALERT_WINDOW was not required in the AndroidManifest.xml and that `android:supportsPictureInPicture="true"` was enough. But I removed this permission which explains the regression. Let's add it back.

**Comment by knight-ryu12** [comment]
Thanks, will see the new release when it happens ;)
