### ISSUE TITLE
[Bug]: Videos run slow, with no sound, when Passthrough (mode 2) is active

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#1286]
### Problem description

Videos run slow + no sound when a track (in my case AC3 and DTS, which are the only ones supported) is played and Passthrough mode 2 is active

### Steps to reproduce the issue

Play a track supported by your amp or soundbar, with passthrough mode 2 active

### Expected behavior

Video should run normally

### Your phone/tablet/androidTV model

Freebox Pop (player)

### Operating system version

Android 10

### Application version and app store

Nova 6.3.2/6.3.3 from Github

### Additional system information

I use SPDIF to passthrough the sound from my TV to my soundbar.
And passthrough is also active on my Freebox Pop. 

So the sound travels this way: 

Freebox (HDMI) -> TV (SPDIF) -> Yamaha SRT 1000 Soundbar

_No response_

**Comment by DeMonsRO** [comment]
No sound on mine too, and no image for Dolby Vision (still bug). HDR works but no sound. (Dolby ATMOS or DTS)
Passthrough (mode 2) - Sony Bravia A95L with Samsung HW Q990C 11.1.4 Soundbar

**Comment by mitch133** [comment]
Hi, is there a reason why the passthrough mode (2) is not working properly anymore?

**Comment by courville** [comment]
> Hi, is there a reason why the passthrough mode (2) is not working properly anymore?

passthrough is broken in 6.3.x versions due to ffmpeg upstep, a new version is available reverting to ffmpeg 4.4.5.
