### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Lucky390163** [nova-video-player/aos-AVP#1287]
### Description

Can you add default audio language and default subtitles selection option.Please

**Comment by courville** [comment]
Should be there already.

**Comment by Lucky390163** [comment]
No its not there.I can't set it manually to my choice.And audio change is not permanent it automatically changes when app is on recents or when we go to video again
![Screenshot_20241001_075451_mpv](https://github.com/user-attachments/assets/4153b457-892f-4313-8801-9a5e50bacd8e)

**Comment by courville** [comment]
The screenshot you show is not nova settings. I guess you are using an external video player that is not nova.

**Comment by Lucky390163** [comment]
Yes it is mpv player.This feature iam requesting which is not present in nova settings In which we can set default language of audio and subtitle before playing a video.

Nova only switch to English default it changes everytime even if you set it to different.

**Comment by courville** [comment]
There is audio preferred langage and subtitle reading languages in settings.

**Comment by Lucky390163** [comment]
Yes this what i requesting.

**Comment by courville** [comment]
It exists

**Comment by Lucky390163** [comment]
Got it.

But there is no option to change next and previous button for video.

And i cannot change rotation of video I have to enable auto rotation to change it and nova rotation feature is buggy.
