### ISSUE TITLE
[Bug]: Breakpoint resume function/memory time function is invalid~

### ISSUE THREAD

**Issue by gkeiko** [nova-video-player/aos-AVP#1304]
### Problem description

Is the breakpoint resume function/memory time function disabled?  
Or maybe the router has been changed recently and BE85 doesn’t support it??

### Steps to reproduce the issue

Unable to resume video playback

### Your phone/tablet/androidTV model

PHILIP OLED808

### Operating system version

androidTV 12

### Application version and app store

v6.3.3

### Additional system information

路由器 DECO BE85

**Comment by courville** [comment]
Where are your video files stored (USB HDD, NAS SMB, ...) ?
Resume points are stored in .video.xml file.

**Comment by gkeiko** [comment]
> Where are your video files stored (USB HDD, NAS SMB, ...) ? Resume points are stored in .video.xml file.

My storage location is USB HDD via router
Restore points are stored in the .video.xml file

Does this mean that this file will be automatically generated after reading it?

If it does not occur, what is the problem? Or is there a setting that is not set properly?

**Comment by courville** [comment]
I will try to reproduce on a setup this weekend.
Another thing to check as advised in the FAQ is to verify that you have not enabled private mode in the UI (this is persistent and disables bookmarks).

**Comment by gkeiko** [comment]
> I will try to reproduce on a setup this weekend. Another thing to check as advised in the FAQ is to verify that you have not enabled private mode in the UI (this is persistent and disables bookmarks).

Understood, I hope you can find out where the problem lies? ,Thanks

**Comment by gkeiko** [comment]
It turns out that the problem is really caused by turning on the privacy mode. 
After turning off the privacy mode, you can remember the time! Thank you~ 
I really didn’t notice that the privacy mode was turned on! XD

**Comment by courville** [comment]
Glad it solved the issue. Please read the FAQ when experiencing an issue since I try to collect there all the major issues faced by users.
