### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by dheerajgattupalli** [nova-video-player/aos-AVP#137]
cannot build the provided docker image

Operation system Windows 10 

Docker Desktop Version 2.0.0.2

Error :  Unable to locate package openjdk-8-jdk

first i was getting Unable to locate package wget .... solved by removing semi colon after sudo .....
then getting this openjdk not found error ....

**Comment by courville** [comment]
Indeed thx for the heads up!
See https://github.com/nova-video-player/aos-AVP/commit/baae6eaff51da0e9fde647079a421162964f17dc

**Comment by dheerajgattupalli** [comment]
But what about the openjdk-8-jdk .... it needs some repositories to be added to the apt to install .... 
@courville

**Comment by dheerajgattupalli** [comment]
adding this dockerfile before apt update fixes the issue ....

RUN echo "deb http://ftp.de.debian.org/debian stretch main" >> /etc/apt/sources.list

**Comment by courville** [comment]
> adding this dockerfile before apt update fixes the issue ....
> 
> RUN echo "deb http://ftp.de.debian.org/debian stretch main" >> /etc/apt/sources.list

Thx
