### ISSUE TITLE
Background loop?

### ISSUE THREAD

**Issue by phhusson** [nova-video-player/aos-AVP#14]
On Android Pie, Nova is running and looping on:
09-17 11:47:00.019  6081  6081 D Clock   : onReceive Intent { act=android.intent.action.TIME_TICK flg=0x50200014 (has extras) }
09-17 11:47:00.022  6081  6081 I chatty  : uid=10106(u0_a106) org.courville.nova identical 1 line
09-17 11:47:00.024  6081  6081 D Clock   : onReceive Intent { act=android.intent.action.TIME_TICK flg=0x50200014 (has extras) }
09-17 11:47:00.132  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:00.360  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:00.538  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:00.765  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:00.948  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:01.166  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:01.358  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:01.567  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:01.765  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:01.985  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:02.178  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:02.398  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:02.592  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:02.804  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:02.992  6081  6690 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1
09-17 11:47:03.208  6081  6567 I pnpServiceConfiguration: Thread pool rejected execution of class org.eclipse.jetty.io.nio.SelectorManager$SelectSet$1

**Comment by courville** [comment]
Not reproduced.
