### ISSUE TITLE
MPAA film rating

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#142]
@courville do you have any plans for a new UI for Nova, that UI has been there for as long as I could remember.

**Comment by courville** [comment]
UI for phones and tablet is not really changing.
However there are many changes underway for the leanback (AndroidTV) UI on the androidx upcoming branches for version 4.x. I will put some beta on github release for people interested to try out.

**Comment by bronnel** [comment]
@courville thanks for the feedback , I'm interested in the in adding some minor features to the video overview like MPAA rating  like when a movie is rated R and so on, I have looked at the code and it looks like it is already available in the scraper I'm not sure though but I don't know how to implement it because I'm not a developer but I like playing around with the code so If you can give me a hand with it that would be great.

**Comment by bronnel** [comment]
@courville

**Comment by bronnel** [comment]
@courville please reply

**Comment by courville** [comment]
First step is to compile the apk from the source code starting with the instructions available here https://github.com/nova-video-player/aos-AVP
Once this first step is completed, let's tackle the code modification itself.

**Comment by bronnel** [comment]
@courville Thanks I just finished building successfully under kubuntu, and using Android studio 3.4.1 and with my own api keys, it is now running on my device.
Now can you please help to add the MPAA film rating to the video info??
I have good Linux  expierence dating back to 2013, I also love manipulating with code, I was a skin modifier for Kodi (XBMC ) skin Aeon MQ on kodi forums.
Your help is appreciated

**Comment by courville** [comment]
You could have a look at various contributions i.e. adding audio badges https://github.com/nova-video-player/aos-Video/commit/6983857fa065d4b474ede2e0657b09d80d1fb8e2 and https://github.com/nova-video-player/aos-Video/commit/c63bd41ad7128af663af543f1baa4298fa90d23d

**Comment by bronnel** [comment]
@courville let me clear something out, the audio badge for example is a kind of information that is taken from the video file directly , while the MPAA rating is a metadata info that is taken from metadata provider aka the scraper from themoviedb website through the api key, can you clarify a bit. and thank you

**Comment by bronnel** [comment]
@courville I think film rating that I want to add is already located in **~/aos/MediaLib/src/com/archos/mediaprovider/video/ScraperStore.java**

it is defined as **CONTENT_RATING** which is further defined again for movie it is **m_content_rating** for series it is **s_content_rating**  , it is also available in 

> ~/aos/MediaLib/src/com/archos/mediaprovider/video/ScraperTables.java

but I don't know which file to modify 
should I only play around with this file ??

> ~/aos/Video/src/leanback/java/com/archos/mediacenter/video/leanback/details/VideoDetailsDescriptionPresenter.java

does the **leanback** mean TV mode ??

> ~/aos/Video/src/leanback/

if  so then **main** means Tablet/Phone mode 

> ~/aos/Video/src/main/

should I edit this file??

> /home/dragon/aos/Video/src/main/java/com/archos/mediacenter/video/browser/presenter/ScrapedVideoDetailedPresenter.java

**Comment by courville** [comment]
You have identified the various tables where the information is stored after scraping.
Leanback is the code related to AndroidTV and indeed the rest is more for phones/tablets though some parts are common.
If you take back the audioBadge example I provided the files modified were:
```
ag AudioBadge
Video/src/leanback/java/com/archos/mediacenter/video/leanback/details/VideoDetailsDescriptionPresenter.java
63:        final ImageView mAudioBadge;
81:            mAudioBadge = (ImageView) view.findViewById(R.id.badge_audio);
365:                mSingleViewHolder.mAudioBadge.setImageResource(audioBadgeResId);
366:                mSingleViewHolder.mAudioBadge.setVisibility(View.VISIBLE);
369:                mSingleViewHolder.mAudioBadge.setVisibility(View.GONE);

Video/src/leanback/java/com/archos/mediacenter/video/leanback/presenter/VideoBadgePresenter.java
135:        public void setAudioBadge(int calculatedBestAudiotrack) {
223:        vh.setAudioBadge(video.getCalculatedBestAudiotrack());

Video/src/main/java/com/archos/mediacenter/video/info/VideoBadgePresenter.java
153:        public void setAudioBadge(int calculatedBestAudiotrack) {
218:        vh.setAudioBadge(video.getCalculatedBestAudiotrack());
```

**Comment by bronnel** [comment]
@courville thanks, I don't have a choice but to simply give up, since I don't know much about java , only a few basic stuff, I'm only familier with xml codes, looks like what I want to accomplish about this app is way difficult for me, I thought it was easy, anyway thanks for your help.

**Comment by courville** [comment]
Sorry not to be able to provide more assistance for now: I am quite busy to try to fix latest issues regarding milestones to publish the application. Will get back on this and ping you.

**Comment by bronnel** [comment]
Thanks ,its  ok take your time with the app ,  whenever you have time , in the meantime I will try to get acquainted with java.

**Comment by bronnel** [comment]
@courville thanks for labeling as enhancement, is it possible to hire a developer to do the job ? I'm willing to pay for this + some other improvements? I don't know how to find a developer with skills for this project, what do you think of it?

**Comment by courville** [comment]
> @courville thanks for labeling as enhancement, is it possible to hire a developer to do the job ? I'm willing to pay for this + some other improvements? I don't know how to find a developer with skills for this project, what do you think of it?

@bronnel, I can reach out to some of the developers of the application. I ask to contact you if they are interested. Thanks for proposing this.

**Comment by bronnel** [comment]
@courville thank you

**Comment by courville** [comment]
@bronnel, could you briefly describe what you are expecting in terms of UI changes in order to anticipate the amount of work required? @PhieF might be interested. Another candidate would have been @persi-persu but he has been quiet for a while.

**Comment by bronnel** [comment]
@courville Thank you so much, If you are familiar with [Infuse](https://itunes.apple.com/us/app/infuse-pro-6/id1444671526?mt=8) , It is basically nova for iOS devices but it has a beautiful UI check out these screenshots, isn't it amazing I want our N.O.V.A. to be like this, I dream of this kind  UI for Android everyday.
I want the UI of the Detailed video information screen to be in a way that it shows TV and movie **MPAA** parental guidelines, the metadata tags of **Director** , **Writers, tagline, Studio logos** like Kodi (if possible) also **IMDb** **TVDB** and **Themoviedb** rating beside their logos I will make a concept using Photoshop , plus all metadata that is currently available, all these for phone/table mode which is what  I'm most interested in, as well as the android TV mode,

![Infuse-for-iOS-dark-mode-001](https://user-images.githubusercontent.com/15629916/58751531-47791300-84a8-11e9-9500-ccf7a7280bed.jpg)
![https___i imgur com_wQo0JC2](https://user-images.githubusercontent.com/15629916/58751857-4ac2cd80-84ad-11e9-827a-2d75eddd6627.jpg)



**if we can get the Video details screen like this or something similar that would be awesome**
![https___i imgur com_CO49eEK (1)](https://user-images.githubusercontent.com/15629916/58751512-04b73b00-84a8-11e9-9645-eb2d72857c74.jpg)
**this what I'm refering to in terms of IMDd and themoviedb logos**
![Screenshot_2019-06-01-20-14-18](https://user-images.githubusercontent.com/15629916/58751662-f23e0100-84a9-11e9-8ab4-35a4650d958b.png)

**Comment by courville** [comment]
@bronnel this is quite a change that you are describing (though relevant and interesting). I am not sure that we would like to engage into it (yet). I would propose to go step by step and tackle first things first on getting MPAA rating inside the current UI.

**Comment by bronnel** [comment]
@courville Ok you are right the first thing for now is getting the MPAA rating , I made this beautiful concept have a look at it, it s not yet finished completely though
![Screenshot_2019-06-01-00-31-29](https://user-images.githubusercontent.com/15629916/58761701-cc6b3780-854f-11e9-8959-fc2294e488ed.jpg)

**Comment by courville** [comment]
What about starting to add the MPAA badge only on the current UI?
If this is ok for a start, let's discuss offline if you can provide me with an email address about a bounty program to implement this feature.

**Comment by bronnel** [comment]
@courville Thank you, here is my email austin.316scsa@yahoo.com let me know what you need.

**Comment by bronnel** [comment]
@courville did you receive my e-mail? , meanwhile check this mouth watering concept I just finished using photoshop. Can I create a new Issue labled "NOVA UI concepts" ?
![Detailed video info](https://user-images.githubusercontent.com/15629916/58766986-00654d80-858e-11e9-973e-26dab74966ea.jpg)

**Comment by courville** [comment]
Yep received the email. Discussing with @PhieF about the proposal.
For UI, please open one single new "new UI concepts" to gather all your nice proposals.
But in order to not generate disappointment in the end, please note that we are not a lot contributing to nova (doing it as a side lobby) and even less having great UI skills.

**Comment by bronnel** [comment]
@courville I'm really grateful that you kept this project alive even if you are doing it as a side hobby, I will try to contribute with UI, I'm good with design but my problem is Java , I manipulated with xml codes modifying skins for Kodi (xbmc) I will try my best modifying the UI, but first we need to get the initial parts of the code to show up like the MPAA ...

**Comment by bronnel** [comment]
Hi @courville I asked someone on upwork to do the job for me, what is the best future proof branch to work on ? is it nova or androidx ??

**Comment by bronnel** [comment]
Hello @courville I asked someone on upwork to do the job for me, I need to know what is the best future proof branch to work on ? is it nova or androidx ?? or should the commits from all branches be included?

**Comment by courville** [comment]
@bronnel the future proof branch is androidx. Note that there is still quite some work to make it releasable.

**Comment by bronnel** [comment]
Hi @courville to compile are these the only cmds I need ?
mkdir aos; cd aos
repo init -u https://github.com/nova-video-player/aos-AVP -b nova
repo sync -j4
repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
make

after successful make command I ran this?

cd native/dav1d-android-builder; git clean -fdx; cd ..
Removing android-ndk-r19-beta2/
Removing android_cross_arm64-v8a.txt
Removing android_cross_armeabi-v7a.txt
Removing android_cross_x86.txt
Removing android_cross_x86_64.txt

**but I get fatal error when I ran:**
cd native/ffmpeg-android-builder; git clean -fdx; cd ..
bash: cd: native/ffmpeg-android-builder: No such file or directory
fatal: not a git repository (or any of the parent directories): .git

**Comment by courville** [comment]
MPAA badge implemented now.
