### ISSUE TITLE
systematic audio delay on some configurations

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#149]
Cf. https://www.reddit.com/r/NovaVideoPlayer/comments/ba5r5k/issue_audio_delay_and_judder/

> I have a Mi laser projector running Android TV 8.1, CPU: T962X Cortex-A53 quad-core 1.5GHz /64-bit
> 
> The audio is always out of sync in Nova and Archos, every single video, every type and encoding, no exceptions. The audio is delayed exactly 220ms for all videos. The issue is not present in other players like VLC or MX.
> 
> There is also a noticeable judder when playing the videos on Nova and Archos. Other players like VLC, MX, Plex play all videos smoothly.
> 
> Tried software decoding and audio passthrough, but that didn't help. Issues are also present in the beta version

**Comment by emarch06** [comment]
Hi,
I also have this issue on freebox mini 4k :-(

**Comment by courville** [comment]
We might have an idea of the problem.
Could anyone that has this issue test that using audio passthrough mode 2 playing a video that uses multichannel AAC codec would make this systematic delay go away and report?

**Comment by courville** [comment]
Please test beta 4.13.
See https://github.com/nova-video-player/aos-avos/commit/3ff4bb721f3a1c1d986834aee0a706da70581f85
With this change AudioTrack is used both for passthrough mode 2 and without passthrough.
It has been verified that the 220ms delay is not present on mi projector.
