### ISSUE TITLE
Warning and error

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#168]
after successfuly compile using the command lines in ubuntu then opening video in Android studio I can successfuly run it, but I get this warning and a couple others

**warning**
`API 'variantOutput.getAssemble()' is obsolete and has been replaced with 'variant.getAssembleProvider()'.
`
**error** when clean project then make project
`No best alternative for libs/context/build/asm_sources`

**Comment by courville** [comment]
Good that you managed to generate the apk.
The warning should have been solved on the androidx branch (still present on nova branch) of Video.

**Comment by bronnel** [comment]
@courville Hi thanks, now I want to compile androidx branch using this command
`repo init -u https://github.com/nova-video-player/aos-AVP -b androidx`
 **but I get this error**
`Warning: License for package Android SDK Platform 28 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Video'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
  
  Using Android SDK: /home/dragon/aos/AVP/android-sdk

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 38s
make: *** [AVP/core.mk:153: all] Error 1
`

**Comment by bronnel** [comment]
@courville now after solving that, I get another error
`FAILURE: Build failed with an exception.

* What went wrong:
Task 'aCLNPD' not found in root project 'Video'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
make: *** [AVP/core.mk:153: all] Error 1
`

**Comment by courville** [comment]
aCLNPD does not exist anymore: please try aCLND
or ./gradlew assembleCommunityLeanbackNoamazon
For your SDK28 you need to accept the licenses (I thought I committed the license file).
