### ISSUE TITLE
error when running compiled project on another computer

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#170]
@courville Hi, I have this issue, I compiled nova branch successfully on Linux , then launched in android studio and ran successfully , then I export project to zip file in android studio
but when I open the project on another computer I get this error:
`CreateProcess error=2, The system cannot find the file specified`

![11](https://user-images.githubusercontent.com/15629916/59378613-63f53500-8d5d-11e9-9c25-60bbf41bbaab.jpg)
![22](https://user-images.githubusercontent.com/15629916/59378620-68215280-8d5d-11e9-86d7-992b03e6fdec.jpg)

**Comment by courville** [comment]
I never checked this use case sorry. It is quicker IMHO to clone the whole project and recompile.

**Comment by bronnel** [comment]
@courville thanks, I can recompile easily, but I want to transfer modified code from one computer to another, can you please help with this?

**Comment by courville** [comment]
Well code modifications can be treated through the git code revision system.

**Comment by courville** [comment]
I would encourage you to clone the repos on your own github account, make your modifications there and then use this to construct your pull request. That way your work will be available everywhere.
You can then rewrite the git history with git rebase -i to clean up before submission if needed.
