### ISSUE TITLE
Please add ISO/IEC8859-16 subtitle encoding

### ISSUE THREAD

**Issue by csgabe** [nova-video-player/aos-AVP#174]
Please add ISO/IEC8859-16(CP-28606) subtitle encoding.

**Comment by courville** [comment]
Could you please provide a sample of subtitle file with this encoding?
Thank you

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-avos/commit/8be3ebf8a1692510edfcb581c4505c6e7887ac41 and https://github.com/nova-video-player/aos-Video/commit/4723217f1513fcc9a2889083141ebcfc0e12a6ca
