### ISSUE TITLE
Freezing on start (Nvidia Shield TV)

### ISSUE THREAD

**Issue by vieira-temes** [nova-video-player/aos-AVP#176]
The app starts to a blue screen and then nothing happens.

I've used it before and everything was OK. I had to reset the Shield for other reasons and then I didn't install the app for a while. When I wanted to watch some movies, I installed it and the current behavior was observed. The only change I can think of (besides the Shield's reset) is the user/password to connect to a Windows PC in the local network.

I deleted the app's Android/data folder and cleared cache and data in Android Settings, to no avail.

I've also tried 4.1 as per issue #98, just in case, with no luck.

The original Archos player does the same but with a grey screen instead of blue.

I can't find any debug or log files using FX File Explorer.

Any help will be highly appreciated. I'm in love with your player.

**Comment by courville** [comment]
This is a new behavior that I have not seen (I am using also the nvidia shield).
Would you be able to take adb logs when it happens and post them here or send the logs via email to software@courville.org?

**Comment by vieira-temes** [comment]
It actually stopped happening recently. It's fine now.

**Comment by courville** [comment]
> It actually stopped happening recently. It's fine now.

ok good (though probably still an issue).
I close the issue, if it re-appears let's re-open it.
