### ISSUE TITLE
AndroidTV: add passthrough mode selection in player audio tile

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#178]
This would avoid to switch in the settings menu.

**Comment by lucianolingnau** [comment]
In an ideal world one would only have to switch the "right" option for his setup once and never touch it again. Not sure I'd clutter the "in player menu" with this option. Seems a bit superfluous to me.

**Comment by courville** [comment]
> In an ideal world one would only have to switch the "right" option for his setup once and never touch it again. Not sure I'd clutter the "in player menu" with this option. Seems a bit superfluous to me.

+1
Will not implement.
For now No passthrough mode should decode and work multi-channel on all setups.
