### ISSUE TITLE
Update app on Amazon AppStore

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#192]
It seems that systematically with a non actionable feedback app update are denied on Amazon AppStore despite many cases open with Amazon support.
Note that only Fire Tablet are supported on first application submission.
After a while and using https://developer.amazon.com/fr/app-testing-service it turns out that what is preventing update is:

> Caution : Widget detected
> Your app appears to be a widget. You can submit your APK without fixing this issue, but your app will not be compatible with Amazon devices.

Thus, need to disable widget and re-introduce specific Amazon build flavor (sigh).

**Comment by Pentaphon** [comment]
@courville Any progress on getting the Amazon app to update? It's currently broken for everybody in that store and it got its first bad review because of that.

**Comment by courville** [comment]
@Pentaphon thanks for the heads up: indeed update was missing.
I have just resubmitted latest apk for approval on amazon AppStore.
Note that any prior update were denied on the AppStore without any way for me to get anything actionnable from the amazon support team.
/me has finger crossed...

**Comment by courville** [comment]
Wait for it... amazon just published the latest update that is even more recent than the playstore one.
