### ISSUE TITLE
Remove "warning: hardware decoding disabled" popup when playing video on forced SW decode

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#194]
If we explicitly disabled hardware decode, we don't need a reminder each time we play a video. We already know what we did. Please remove that popup. It gets distracting and kind of ruins the video experience. 

Also, people sitting next to me keep pointing out the warning, thinking there's something wrong with the player.

**Comment by courville** [comment]
First question: why are you using software decoding?
Motivation behind this toast is to avoid people complaining about poor video decoding performance because they forgot that they forced software decoding (happens a lot in reality).

**Comment by Pentaphon** [comment]
> First question: why are you using software decoding?
> Motivation behind this toast is to avoid people complaining about poor video decoding performance because they forgot that they forced software decoding (happens a lot in reality).

I find that software decoding is smoother, faster, and has better picture quality than HWA on all my devices. I use software decoding on PC, Linux, and Android all the time. Whenever I use HWA instead of SWDec, I get picture corruption on some older videos, and on older hardware like the Nexus Player, x265 videos will actually play and x264 videos scrub forward a lot smoother. I find HWA to be problematic so I always turn it off. ffmpeg-based players have great software decoding on all hardware so I've never needed to use HWA, ever.

**Comment by courville** [comment]
HWA for embedded devices is a must to play modern videos (1080p, 4k etc.).
Your point is valid for old hardware like Nexus Player that has crappy soft codecs pretending OMX acceleration e.g. HEVC.
It is also valid for some old SD videos.
Battery wise or thermal wise I would not recommend using SWDec.

**Comment by Pentaphon** [comment]
> Battery wise or thermal wise I would not recommend using SWDec.

Yeah, so the only time you really benefit from HWDec is on phones when playing Youtube videos, but my phone already has HWDecode for all Youtube codecs. Meanwhile, I only use Nova on my Nexus Player which is always running from a wall outlet and I've looked at the thermals, the Intel SOC on it never gets hot on x264 software decoding or x265 software decoding. It's not fast enough to play 4K smoothly but I never get 4K video anyway. When playing older XVID videos encoded over a decade ago, my Nexus Player will show half the video flickering from time to time on HWDec but when I use SWDec, it plays smoothly. No issues at all. No issues at all on any video playing with SWDec, really.

Also I think a lot of people have older hardware that has mediocre GPUs but good enough CPUs and ffmpeg-based SWDec is a good way to solve most of their playback issues with your player.

**Comment by courville** [comment]
For now sticking to the debatable choice of keeping the swdec toast to remind people to get back to hwdec and not complain about performance issues. Closing the issue for now.

**Comment by Pentaphon** [comment]
> For now sticking to the debatable choice of keeping the swdec toast to remind people to get back to hwdec and not complain about performance issues. Closing the issue for now.

Fair enough. I've bought new hardware since I first posted this so I run HWdec on all my current devices. I do however, think the toast can be annoying for people who know enough to turn off HWdec for their specific device where HWdec doesn't work for say, x265 and I've had several people ask me why that toast kept popping up before a video. Other players don't have a similar toast and I think it is worth following suit. The info display telling you what kind of decoding you're using should be enough.
