### ISSUE TITLE
5.1 Beta asks for username and password on non-passworded share on Windows 10

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#200]
Just tried the 5.1 beta and it keeps asking me for a username and password even though I have explicitly disabled password protected sharing on Windows 10 64 bit. 

![Untitled](https://user-images.githubusercontent.com/49374058/65384996-ed61bf00-dcdd-11e9-88a8-1dfd507195df.png)

Also, has anybody successfully connected to Windows 10 64 bit shared SMB2/3 folders with Nova because I can't seem to find a sure-fire way to connect to them at all. I have to use upnp instead because I don't want to use SMB1.

**Comment by courville** [comment]
There is no way to connect to non SMBv1 shares with 4.x version.
5.x versions starts integrating jcifs-ng that will provide support for SMBv2/3.
I managed to connect to password protected shares on win10 (need to retest though on current release).
I will test the non password protected shares on win10.
Thanks for reporting.

**Comment by courville** [comment]
OK I can reproduce and also with test program.
What is strange is that from macOS it is also not possible to login as GUEST.

**Comment by courville** [comment]
See https://github.com/AgNO3/jcifs-ng/issues/186

**Comment by courville** [comment]
Quick question before digging too much into the issue: have you managed to get a Guest account on your windows 10 computer and access it through another windows computer?
For now I am failing at this awesome exercice and the big Internet says that Guest has been disabled on windows 10 for a while.

**Comment by Pentaphon** [comment]
No, I have not tried that but I have been able to access non-passworded Windows 10 shares with the VLC 3.2 beta for Android so I was surprised when Nova couldn't do the same thing with the new SMB2/3 support.

**Comment by courville** [comment]
I just tried Android VLC beta on a windows 10 family edition and it also requests credentials even after turning off the password protected sharing in my case.
It seems also that there is no Guest account now and re-enabling it is quite an adventure.
On the windows pro edition, there is a Guest account but on the computer I had access to you could not turn off the password protected sharing.

**Comment by courville** [comment]
OK I manage to connect with Guest from my mac. I have everything now to generate traces.

**Comment by Pentaphon** [comment]
>I just tried Android VLC beta on a windows 10 family edition and it also requests credentials even after turning off the password protected sharing in my case.

That's odd but I guess I am using Windows 10 Pro. Did you give access to "everyone" like so? That's how I got VLC 3.2 beta 1 to connect to Windows 10 Pro non-passworded shares. 

![everyone](https://user-images.githubusercontent.com/49374058/65834659-1eb82d00-e292-11e9-90ce-93f64efca710.png)
