### ISSUE TITLE
leanback: increase poster resolution

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#206]
Kodi has better resolution https://www.reddit.com/r/NovaVideoPlayer/comments/d756qu/movietv_posters_low_quality_images_compared_to/

**Comment by courville** [comment]
Poster resolution is set in ScraperImage.java but also in MovieParser3.java

**Comment by courville** [comment]
Should have been resolved in v6.x

**Comment by OKVnDa** [comment]
Any chance adding an option in settings for poster resolution? Really not a fan for compile the whole project.
