### ISSUE TITLE
[Feature Request]  rotten tomatoes, metacritic and MPAA rating 

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#22]
Hi, I have some suggestions for improving Nova player, and I'm willing to help.
1-adding support for rotten tomatoes and metacritic, trakt , themoviedb, tvdb rating
2-Parental guideline rating flags for movies and tv shows
for movies: G -- PG -- PG-13 -- R -- NC-17
for tv shows: TVY -- TVY7 -- TVG -- TVPG -- TV14 -- TVMA
3-this one is the is last priority , I want to be able Pause / Play Video just by touching the screen (I mean single tap to pause video then single tap to resume) without showing on-screen controls, Yes I know I can use an external player, but I prefer the built-in player of archos (i mean nova), since it is very stable and perfect.

check the ratings of this is app called Moviemate available on play store

![screenshot_20181004-221733_movie mate](https://user-images.githubusercontent.com/15629916/46497575-a015e480-c823-11e8-9a68-15d5dac5f5ab.jpg)

also check the MPAA ratings of this one called Cinetrak
![screenshot_20181004-222656_cinetrak](https://user-images.githubusercontent.com/15629916/46497997-da33b600-c824-11e8-8e44-38dfd588bfd5.jpg)
![screenshot_20181004-222702_cinetrak](https://user-images.githubusercontent.com/15629916/46497998-da33b600-c824-11e8-9320-c19244ea02db.jpg)
this one called nachos
![image](https://user-images.githubusercontent.com/15629916/46498183-5c23df00-c825-11e8-94a4-52a82cc1290c.png)

**Comment by bronnel** [comment]
@courville can you please add some of these features , I don't know much but I will try to help as much as I can.

**Comment by bronnel** [comment]
@courville are you going to start working on the UI, can you at least add Content rating to the media info screen , like pg , pg13 , r , tv-14 etc ,?

**Comment by bronnel** [comment]
@courville

**Comment by courville** [comment]
MPAA implemented, better rating not yet possible (rotten tomatoes not free). Sticking with tmdb for now.
