### ISSUE TITLE
Subtitle issue from UPnP Server

### ISSUE THREAD

**Issue by Stanley008** [nova-video-player/aos-AVP#221]
Hi, 
there is an issue with subtitles when playing movies from UPnP server. Movies are playing fine, but when trying to download subtitles in the player(not in the movie description page - it works fine there) - the movie is shown as a number only and it is searched like that, which means it doesn't find anything relevant.

**Comment by courville** [comment]
Unfortunately there is no universal way to get subs working via upnp since it is not part of the protocol (only guess fetching is performed that works sometimes with some servers).
Closing the issue.
