### ISSUE TITLE
[Feature Request] Needs network streaming via HTTPS URL.

### ISSUE THREAD

**Issue by 5amar31** [nova-video-player/aos-AVP#23]
It supports FTP servers but this is also a useful option to have.

**Comment by courville** [comment]
ssl has been removed from avos long ago and should be put back. Only http is supported for now.

**Comment by morpheasgr** [comment]
I saw my duplicate issue being closed and got my hopes up that the feature was implemented. Is there anything that us, the community, could do to help add this feature? I guess it is kinda difficult to implement SSL encryption stuff. If there is anything a junior dev such as myself could do, please let me know.

**Comment by courville** [comment]
@morpheasgr thanks for proposing to help. The https addition is not that trivial. I will talk with some former devs to check how to do this.

**Comment by morpheasgr** [comment]
> @morpheasgr thanks for proposing to help. The https addition is not that trivial. I will talk with some former devs to check how to do this.

Thank you so much!

**Comment by mschumacher69** [comment]
I didn't know that Nova could load video from an http URL, how to do that?

**Comment by courville** [comment]
Status update: curl+openssl android builder scripts added. Now need to add back in avos https.
Old patch is there: [0001-add-back-openssl-and-curl.patch.zip](https://github.com/nova-video-player/aos-AVP/files/7899748/0001-add-back-openssl-and-curl.patch.zip)

**Comment by courville** [comment]
@mschumacher69 nova can be used as an app to open http streams for videos from other apps.
One way to test (yes I know this is not what you are expecting) is to issue `adb shell am start -a android.intent.action.VIEW -d 'http://URL/video.mkv'`

**Comment by mschumacher69** [comment]
@courville thanks for the clarification!

**Comment by courville** [comment]
Status update: avos has https support back but does not work yet.
Moreover Android 12 prevents for now opening of http/https links (to investigate) and https streaming still ko on Android 11.

**Comment by morpheasgr** [comment]
Progress is still progress and thanks a bunch for working on this feature. I am on Android 11 on a OnePlus 6T, https direct video file links do work on other software including mpv, vlc and MX Player Pro. Sadly my content provider only works through HTTPS, but offers direct links to the files. Let me know when you put out a test build for arm64 so I can see if my links work. Will create some tedt links for various formats in advance.

**Comment by courville** [comment]
Thanks @nnoury, tested to work ok now through ffmpeg.

**Comment by courville** [comment]
Github pre-relase 6.0.40 contains https/ssl support.
