### ISSUE TITLE
Why is there 2 versions?

### ISSUE THREAD

**Issue by Baramiji** [nova-video-player/aos-AVP#240]
A thing confuse me, and I couldn't find the answer anywhere.
Why in the [releases section](https://github.com/nova-video-player/aos-AVP/releases) we find 2 different versions on nova:
- vesrion 4
- version 5

What's the difference between them?
Thank you.

**Comment by courville** [comment]
Version 4 is the released one on Google Play.
Version 5 is a more experimental one that implements SMBv2/3 and other changes.

**Comment by Baramiji** [comment]
Merci.
Tout est clair.
