### ISSUE TITLE
CreateProcess error=2, The system cannot find the file specified on Android Studio(Windows)

### ISSUE THREAD

**Issue by AKprisonER** [nova-video-player/aos-AVP#247]
The error restricts from building apk.
Errror on module "Filecorelibrary" NDK build
Execute exec caused
Caused by: java.io.IOException: Cannot run program "make" (in directory ""): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)

**Comment by courville** [comment]
For now building on a Windows host is not supported.
It works on Linux and MacOS but not Windows.

**Comment by bronnel** [comment]
@courville I tried building on Linux it gives this error  "Filecorelibrary" NDK build , I also tried on windows using Docker gives me the same error ,I appreciate if you could help me out here?
