### ISSUE TITLE
Publish app on F-Droid

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#25]
This requires to get rid of Privlibs.

**Comment by courville** [comment]
Cast privlibs removed i.e. com.google.android.gms:play-services-ads com.google.android.gms:play-services-cast https://github.com/nova-video-player/aos-Video/commit/30fb059fcffa3ab6dfb96d6cf8bad6b53b8aca96

**Comment by courville** [comment]
We are free and should remain free thus Archos ads are gone removing privlibs com.amazon.android:mobile-ads com.google.android.gms:play-services-ads via https://github.com/nova-video-player/aos-Video/commit/88f89ee0f13feaf7c36c1e242c2af95a3c87cc7f

**Comment by courville** [comment]
Seems that http://www.artificialworlds.net/blog/2017/01/17/submitting-a-package-to-f-droid/ is a good start.

**Comment by courville** [comment]
Before building in build script do now a `rm native/torrentd/libs/*/torrend`

**Comment by courville** [comment]
Previous attempt to get AVP on F-Droid with very interesting information: https://gitlab.com/fdroid/fdroiddata/merge_requests/2716

**Comment by courville** [comment]
Note that compared to AVP, there are less privlibs.
However we still have FileCoreLibrary/libs/jakarta-oro-2.0.1.jar but latest is https://mvnrepository.com/artifact/apache-oro/jakarta-oro/2.0.8
```
find . -name \*jar | grep -v build\/intermediates | grep -v gradle\/wraper
./Video/gradle/wrapper/gradle-wrapper.jar
./FileCoreLibrary/libs/jakarta-oro-2.0.1.jar
./MediaLib/libs/in-app-purchasing-2.0.76.jar
```

**Comment by courville** [comment]
Jakarta Oro gone now https://github.com/nova-video-player/aos-FileCoreLibrary/commit/1c53c9c25297ca971d79478e284757434bca6ba6
in-app-purchasing needs to go but has adherence to Video/src/main/java/com/archos/mediacenter/video/billingutils

**Comment by courville** [comment]
No more in-app-purchase lib https://github.com/nova-video-player/aos-Video/commit/5e882a2f52b3e934c754344783d81bba56de6251

**Comment by courville** [comment]
@phhusson Need to build server setup now: https://f-droid.org/en/docs/Build_Server_Setup/

**Comment by Pentaphon** [comment]
Thanks for working on this, @courville. Listing Nova on F-Droid will give it a lot more exposure. And open source Android users are very supportive to anything on F-Droid.

**Comment by rzr** [comment]
Is there a ticket also opened f-droid's side ?

**Comment by Poussinou** [comment]
@rzr is right, it could be a good thing to open a [RFP](https://gitlab.com/fdroid/rfp/-/issues) on F-Droid side. It looks like @courville is already used to this app development, it could be helpful on F-Droid side.

**Comment by courville** [comment]
@Poussinou @rzr @Pentaphon inclusion of nova has been submitted to fdroid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6570 please +1
Thx @phhusson for this!

**Comment by courville** [comment]
RFP submitted https://gitlab.com/fdroid/rfp/-/issues/1284

**Comment by Pentaphon** [comment]
@courville @phhusson Thanks for getting this on F-Droid. It will definitely give a boost to the Nova userbase.

**Comment by ghost** [comment]
Today I checked on Fdroid again it is still not available on official repo
Please make it available on IzzyOnDroid Repo
As the creator of repo summarises

> 
    it holds open-source-apps that for some reason didn’t make it into the official F-Droid repo or are no longer updated there. Those reasons usually have to do with proprietary dependencies introduced into the apps.
    as an F-Droid maintainer put it, it also serves as a stepping stone for projects wanting to be included in the official repo, but yet have to solve such dependencies. Once they’re done with that job and listed on the official repo, they’re usually removed from IzzyOnDroid’s again (mostly to avoid confusion due to signature mismatches).
    if you know a fitting app that’s neither in this nor in the official repo, you can visit IzzyOnDroid Repo’s Repo at GitLab and let me know, so I can include it if possible.

**Comment by courville** [comment]
@cleanerspam thanks for the hint. We will try to progress on fdroid since there might be a way to converge.

**Comment by Pentaphon** [comment]
> Please make it available on IzzyOnDroid Repo

I've requested that here. https://gitlab.com/IzzyOnDroid/repo/-/issues/93

**Comment by Pentaphon** [comment]
@courville Thanks for finally getting Nova on the F-Droid store. I must advise you though, that the current page is missing screenshots, a description, donation link, etc. 

https://f-droid.org/packages/org.courville.nova/

Compare that to how the VLC page looks: 

https://f-droid.org/en/packages/org.videolan.vlc

**Comment by courville** [comment]
@Pentaphon yes we noticed too. We are trying to fix it.
There are quite some hacks involved for now in the release process to make it work with the versioning requirements from F-Droid that could interfere.

**Comment by rzr** [comment]
Congratz, btw Is there a ticket for TV profile of F-Droid ?

**Comment by licaon-kter** [comment]
@courville https://github.com/nova-video-player/aos-Video/commit/d015fb614e9931bcddd33da8ef2bf17fdc89fbea nope...things got b0rked https://gitlab.com/fdroid/fdroiddata/-/commit/631dba234b74b7fc05c58eb382489789ce7073cc

**Comment by courville** [comment]
@licaon-kter ok thanks for pointing it out.

**Comment by courville** [comment]
See https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6994

**Comment by courville** [comment]
OK now metadata are there https://f-droid.org/fr/packages/org.courville.nova/index.html

**Comment by jerryn70** [comment]
@courville did you guys stopped updating app in fdroid ? The last fdroid release was on october 2020
