### ISSUE TITLE
Grey bar at the bottom during video playback

### ISSUE THREAD

**Issue by mynick11** [nova-video-player/aos-AVP#250]
Hi,

first of all congrats for the best video / media center application that is available at the moment - you did an amazing job so far!

However I am facing a problem during the video playback. It doesn't matter which file (mp4, avi, mkv) I am playing I have a grey bar at the bottom of the video below the normal black bar for 16:9 format. Is there any chance to fix it? At the moment I am using the alternate player option, since there is no such trouble with other players.

Hardware: RK3328 Rockchip TV BOX with Android 9

Thanks & best Regards

**Comment by courville** [comment]
Thanks for the feedback. One question to understand the influence of video hardware decoding on this behavior: would it be possible for you to check if there is the same glitch with forcing software decoding in settings (not recommended option to keep)?

**Comment by mynick11** [comment]
Hi Courville,

unfortunately software decoding has no effect on the bar. The only situation where the bar is gone is, if you open the menu during the playback. I've added some Pictures of the situation. One is the normal Mode and the other two are showing the Bar as a layout element if you switch on the layout borders in the android debug mode.

I hope this help.

Best regards
![20191129_100918](https://user-images.githubusercontent.com/58254495/69859218-06fe2480-1294-11ea-83cf-a508bd0434f6.jpg)
![20191129_101826](https://user-images.githubusercontent.com/58254495/69859232-0b2a4200-1294-11ea-9457-9e224366d964.jpg)
![20191129_101339](https://user-images.githubusercontent.com/58254495/69859241-0e253280-1294-11ea-9947-9583149b593f.jpg)

**Comment by mynick11** [comment]
Hi once again,

I've got some news. After loading the APK for debug in Android Studio it seems that the problem is located in the player_controller_placeholder (compare attached screenshot). The placeholder is not a problem as long as there are no additional control elements / possibilities. For TV Boxes or Keyboards it seems to be a problem because the placeholder does not disappear once it is activated. The Bug can be reproduced as follows:

- Start video playback in the Android Virtual Device Manager with Nova
- Everything is fine
- Now push the down arrow button (or left or right)
- The bar appears and remains as long as one of the following actions do not occur:
  - Click on the screen with a mouse
  - Press the up arrow button in order to open the quick menu - after closing the menu the bar has disappeared.

It seems that the TV Boxes have some virtual keyboard or something like that installed in order to work with a remote control. However this leads to the bar being present all the time. 

Is there any chance to remove the placeholder bar or to try making it invisible / not reacting on different control actions?

![Bug](https://user-images.githubusercontent.com/58254495/70039434-3bd2ea00-15ba-11ea-9067-e1cc934a070f.JPG)


Thanks & best regards

**Comment by courville** [comment]
Yes indeed we saw via uiautomator that the area you mentioned is indeed org.courville.nova:id/player_controller_placeholder
Thanks for the detailed and quality feedback.
I will try to investigate.

**Comment by courville** [comment]
In Video/res/layout/player.xml there is:
```
    <!-- This is a fake player controller that is used to handle the focus in the Activity window, 
         while the actual player controller is in another window -->
    <View
        android:id="@+id/player_controller_placeholder"
        android:layout_width="fill_parent"
        android:layout_height="30dip"
        android:layout_alignParentBottom="true"
        android:focusable="true"/>
```
I will keep it but let's try to make is invisible i.e.       `mPlayerControllerPlaceholder.setVisibility(View.INVISIBLE);` or `android:visibility="invisible"`

**Comment by courville** [comment]
@mynick11 could you please try this experimental release build https://drive.google.com/open?id=1MN4SJXHL9jeTO7K6mPiWQSfF5L4RQN8y and report if the above change made any difference?
Thank you

**Comment by mynick11** [comment]
Hi Courville,

amazing work, the bar is gone and I could not see any negative effects from this change. 

However, besides the bar issue there still seem to be some issues regarding the resolution handling especially when it comes to .h265 videos but this specific bug seems to be solved. 

Best regards

**Comment by courville** [comment]
OK good. Could you please open another bug for H265 with sample and also a picture of the issue?
Thanks.

**Comment by courville** [comment]
Rollback since it breaks play/pause key focus.

**Comment by courville** [comment]
This grey bar is also present on chromeos on the pixelbook.

**Comment by courville** [comment]
Thus view with android:visibility="visible" makes the play/pause with enter/space and "invisible" or "gone" only space works...

**Comment by courville** [comment]
No obvious solution for now: reduce size of the bar to 1px.
Not ideal but better...
