### ISSUE TITLE
UI problem when video plays

### ISSUE THREAD

**Issue by Dmitry-k42** [nova-video-player/aos-AVP#256]
Hi!
I have a problem in stable version 4.20. Bottom navigation bar is overlapped by the system nav bar in landscape reverse orientation. I can not pause video and touch all other buttons in the bottom bar. In landscape normal orientation everything is fine. I have Lenovo Tab 10, Android version 9

Example:
![Screenshot_20191207-110658_Nova_](https://user-images.githubusercontent.com/2426173/70372239-8079c080-18ed-11ea-8da1-7b355c44b930.png)

**Comment by courville** [comment]
Thanks for reporting.

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-Video/commit/44703489c28510cdf54791c6ed3698b7860c591c

**Comment by courville** [comment]
I have fixed some layout issues for tablets regarding playerController however this was not really tackling your specific issue (but could).
Can you please test this apk  https://drive.google.com/open?id=1oO_j_okbhQeactnNu-14hWsgscbM8rsw and report if it fixes the problem you have?

**Comment by Dmitry-k42** [comment]
Yes, it is fixed. Thank you a lot!
