### ISSUE TITLE
Multiple Bugs regarding h.265 decoding

### ISSUE THREAD

**Issue by mynick11** [nova-video-player/aos-AVP#257]
Hi Marc,

as requested you will find below my findings regarding the h.265 decoding. 

1. Test File 
The Test was done with this test file: http://jell.yfish.us/media/jellyfish-10-mbps-hd-hevc.mkv - I am not the owner of this video material. Credits for the guys providing their test files!

2. The expected result
The video is coded properly in 1920 x 1080 full screen mode, so the expectation is that we see a full screen video without any bars or something other - like here (pic was taken with another video app): 

![20191209_181240](https://user-images.githubusercontent.com/58254495/70458069-a18b0e80-1ab1-11ea-8abc-b92cb851357d.jpg)

3. The real results

Starting the video in Nova leads to stretching of the video and having these black 16:9 bars on the upper and lower part of the screen:

![20191209_181451](https://user-images.githubusercontent.com/58254495/70458220-f464c600-1ab1-11ea-872c-2adb94145af3.jpg)

Taking the whole thing to the "Fullscreen mode" of Nova the bars are removed BUT the video is completely stretched and cut out / tailored in the wrong way (compare the URL in the right lower corner)

![20191209_181554](https://user-images.githubusercontent.com/58254495/70458522-7fde5700-1ab2-11ea-8618-1dd0905b3b8c.jpg)

4. Bug because of the #250 fix

It seems like since the #250 fix there is a standard focus on the Info button. So if i press the "Enter" Key of the remote control I get the Info about the file and not the video paused like before. 

![20191209_181614](https://user-images.githubusercontent.com/58254495/70458699-f24f3700-1ab2-11ea-81c0-ae2ad4c91c4c.jpg)

5. Test Equipment

These tests were done with the Rockchip RK3328 TV Box with Android 9 on it and the current Nova version 4.22 
 
Best regards

**Comment by courville** [comment]
Thanks for reporting and illustrating the issue: indeed there is obvious stretching.

**Comment by courville** [comment]
Happens too on the Philips TV: https://www.reddit.com/r/NovaVideoPlayer/comments/dz4wh5/reqissue_android_tv_9_pie_aspect_ratio_totally/

**Comment by courville** [comment]
@mynick11 I guess that the problem also happens not only with HEVC (H265) video but with other codecs like H264. Do you confirm?

**Comment by mynick11** [comment]
Hi,

no, I cannot confirm that. With h.264 it behaves differently but also wrong. There you have small black bars at the left and right corners of the TV. With "Fullscreen Mode" on it zooms a bit and the bars are gone then. But no stretching there.

**Comment by courville** [comment]
ok most likely RK and amlogic are not able to handle displaying surfaces that are larger than the screen resolution.

**Comment by courville** [comment]
@mynick11 I would like to propose that you try out this apk https://drive.google.com/open?id=1_41GSHTwoHs9-yxZm1ngyw3GH5Wjjt9t that has special debug logs.
Would you have a way while playing the jellyfish video to get the adb logs out of your box and more specifically look for `avos_player: sfdec_read: INFO_FORMAT_CHANGED:` and report the end of the line in "normal mode" and "full screen mode".
Something like `adb logcat | grep 'avos\|SurfaceController' ` would help.
Thanks

**Comment by mynick11** [comment]
Hi,

Here are results of my testing:

1. Emulated Android TV with Android 9 in Android Studio (everythings fine) Log:

[Emulated_AnrdoTV_Android9.txt](https://github.com/nova-video-player/aos-AVP/files/3950279/Emulated_AnrdoTV_Android9.txt)

2. The going crazy log of a RK3328:

[RK3328.txt](https://github.com/nova-video-player/aos-AVP/files/3950281/RK3328.txt)

The first problem is that the surface controller is not recognizing the LCD plugged correctly.

- SurfaceController: updateSurface: lcd plugged dw=1280, dh=720 --> This is wrong. The TV / TV Box is set to 1920 / 1080.

- Then it seems that it cannot get the configs: 
OMXNodeInstance: getConfig(0xefd935a0:rk._decoder.hevc, ??(0x7f000062)) ERROR: UnsupportedSetting(0x80001019)

- And in the end it decides to change the format:
avos_player: sfdec_read: INFO_FORMAT_CHANGED: 2304x1080

I hope this helps.

Best regards.

**Comment by courville** [comment]
Thank you for this detailed answer (really).

> * avos_player: sfdec_read: INFO_FORMAT_CHANGED: 2304x1080

this is a bad news for you since it means that the implementation of MediaCodec is borked on your specific box.
Note that on certified AndroidTV boxes this is enforced by CTS testing.
There is little we can do at this stage.

Regarding:
> SurfaceController: updateSurface: lcd plugged dw=1280, dh=720 --> This is wrong. The TV / TV Box is set to 1920 / 1080.

this would hint that your Rockchip box is using a 720p graphic/UI plane (perhaps it can be changed in settings).

**Comment by mynick11** [comment]
Hi,

thanks for the answer. 
Still the question remains, if there is a problem with the media codec of the box, why is Nova the only player having trouble with it? I've tested the videos on three different players the others worked without any issues.

Regarding the 720p - It is set tp 1080x1920p60 in the settings, also the TV shows that it is 1080p coming through the HDMI. 

For me it looks like Nova has not sufficient rights or something to get the info it needs to show the video right.

Best regards

**Comment by courville** [comment]
OK you have some valid points.
Could you please try this apk where we leave to the codec to do the scale/crop (this improves an issue on amlogic) and provide a picture of the change in output (if any): https://drive.google.com/open?id=129SxewI4jvtyy4b7N6-uJwl0YQfeGe1m
Note that it will not solve entirely your problem but could give us some clues on how to progress.
For the 720p screen resolution reported, it could very well be that the UI plane is using a 720p "framebuffer/surface" that is scaled to 1080p which is the display mode selected. This enables fast responsive UI with not so nice rendering.

**Comment by mynick11** [comment]
Hi,

no change unfortunately :/

Best regards

**Comment by courville** [comment]
OK let's try another approach and not trust the MediaCodec reporting and only the container reporting that could help (and causes different bugs): https://drive.google.com/open?id=129SxewI4jvtyy4b7N6-uJwl0YQfeGe1m
Could you please test this new apk and report?
I apologize for these repetitive blind attempts.

**Comment by mynick11** [comment]
Hi,

there is nothing to apologize for ;) You're doing a great job. The stretching is gone. Video playback works perfectly for h.265 1920/1080 & h.264 1920/1080 & 720/480. 

However due to the rollback to fix the focusing of the buttons the grey bar is visible again.

Best regards

**Comment by courville** [comment]
@mynick11 could you please check the following apk that uses another method of scaling (perhaps a better one but I do not know if it works in your case) https://drive.google.com/open?id=17QtCjqNfEcRtMYqeNTtDAfPtYbyOPcTk
Thanks!

**Comment by mynick11** [comment]
@courville unfortunately this version leads to the same stretching as the initial one. The version before worked best for me.

**Comment by courville** [comment]
OK reverting to previous one for now.
