### ISSUE TITLE
[question] is background playback supported?

### ISSUE THREAD

**Issue by magiruuvelvet** [nova-video-player/aos-AVP#27]
I just compiled Nova Player from source today myself to make sure I've got the ad-free version without any privlibs. It runs smoothly on my device.

I want to permanently replace MX Player Pro with Nova Player, because its open source, but I'm missing an essential feature to keep videos running in the background.

Also looking forward to the F-Droid release :)

**Comment by courville** [comment]
Background playback is not supported for now but nova supports PIP to allow other app usage.
I am not sure it fits the request though.
