### ISSUE TITLE
Feature request: Look for folder name for unscraped media to improve matching

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#287]
In many cases, the folder has a descriptive name while the file inside is XYZ.avi - some videos are in "movie name folder/xyz.avi"
Could you make it optional may be to look for a folder name if the video file name has no match in TVDB?
I believe this will solve 50% of the unscraped files.

Thank you in advance - low priority, but I believe an easy to implement and good feature

**Comment by JJD2K** [comment]
I saw you added "Better TV show scrape result through multi-language Levenshtein metric computation"
unfortunately, that did not parse even a single extra file for me.
Could you add my suggestion as a fallback if subtitles file is not marched for the video file name to look for the folder name where it is located? 
I do not think this could cause any issues. You can make it optional if you doubt it.

**Comment by courville** [comment]
See README of https://github.com/nova-video-player/TestScraper, it explains the scraping process. It should cover your case in MoviePathMatcher pass. Perhaps another pass provides already a match. Please provide exact path and filename for me to check.

**Comment by courville** [comment]
Scraper has completely been reworked since. Closing the issue for now.
