### ISSUE TITLE
Displaying the SMB version in the external directory search

### ISSUE THREAD

**Issue by Ilithy** [nova-video-player/aos-AVP#292]
Hi, I would love to see a small change in the user interface, in the search tab of the samba share directory, would it be possible to add the version of the protocol used by the device, a bit like that:

![Screenshot_20200131-143353__01](https://user-images.githubusercontent.com/36798218/73544246-0ec77a00-4439-11ea-8054-874be472030c.jpg)

 I don't know if it's implementable, or if it would be difficult, thank you very much.

**Comment by Pentaphon** [comment]
I think this would actually be useful.

**Comment by courville** [comment]
I think this is a good idea too but I am afraid that that would require a SMBv2 capable jcifs that would inherently support all samba versions.

**Comment by courville** [comment]
Last versions of jcifs-ng are much better and this distinction SMBv2/1 and technical display are IMHO not required anymore (though this is a nice idea).
Anyway, I do not see how to identify SMB level at scan (it is not provided via the API).
I will thus close the issue.
