### ISSUE TITLE
Duplicate watch history - wrong sync time reported

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#294]
I've been using SeriesGuide to mark episodes as watched manually, but I recently started using Nova to scrobble.

I've been having some duplicates in my watch history since I started scrobbling and I've been trying to figure out what's causing it.

I have noticed that the watched icon is different between the original watch and the duplicate in SeriesGuide (check attached screenshot). I think the check mark means it's been set as watched manually and the chat bubble means it's been scrobbled automatically. But I haven't been marking episodes manually since I started scrobbling with Nova.

I'm suspecting that SeriesGuide is duplicating the watch once it syncs with trakt. Is there a way to check the log to check the source of the watches to figure out if the duplicates are from SeriesGuide or from Nova?

Thanks
![Screenshot_20200201-232344](https://user-images.githubusercontent.com/461871/73598625-c056d000-454b-11ea-9606-2551d0ab545c.png)

**Comment by mschumacher69** [comment]
@courville I don't think the issue is from SeriesGuide.

Today it happened again without touching SeriesGuide. I watched Tell me a Story S02E02, it scrobbled it correctly. Then when I watched S02E03, close to the end of the episode it re-scrobbled S02E02 and then scrobbled S02E03 twice.

I have noticed that this usually happens when I binge watch multiple episodes of the same show.

**Comment by courville** [comment]
I think this is related to real time scrobbling when bookmarks are saved while watching. If you disable this in settings, do you still observe this behavior?

**Comment by mschumacher69** [comment]
Thanks I will try when I get back home and let you know.

**Comment by mschumacher69** [comment]
@courville ok disabling live scrobbler seems to have solved the problem, but now the time stamp is 3 hours off. It marks them as watched 3 hours in the future on trakt.

Any ideas?

**Comment by mschumacher69** [comment]
@courville any idea why the time stamp is 3 hours in the future when I disable live scrobbler?

When I enable live scrobbler, the time stamp is correct but I get duplicates.

When I disable live scrobbler, I don't get duplicates anymore but the time stamp is 3 hours in the future.

**Comment by courville** [comment]
@mschumacher69 I believe the fixed number of hours difference in the history must come from a timezone issue when reporting the watched time. I will fix it.

**Comment by mschumacher69** [comment]
Thanks! What about duplicates when live scrobbling? Is this something that can be fixed or is it going to remain an issue?

**Comment by courville** [comment]
@mschumacher69 the live scrobbling dupplicate watch will stay I am afraid because this is the only way to save bookmarks that I found but I reduced the reporting frequency in the beta version.

**Comment by mschumacher69** [comment]
Ok thanks, I will try the beta to see if it's any better. Are there any known major bugs currently in the beta?

**Comment by mschumacher69** [comment]
@courville so I'm on beta now, the time stamp is correct now if Live Scrobbler is disabled. Trakt support told me though that the time is optional in that API method and they just use the current date by default, so maybe you don't have to send a custom date/time?

Regarding the duplicates, I'm still getting them when Live Scrobbler is enabled. The weird thing is that it duplicates episodes that I am not watching right now. For example, if you look at the attached screenshot, you can see that I finished watching episode 1x06 at 9:06 PM, but it also marked episode 1x05 at the same time and duplicated 1x06 again. The correct watch time of 1x05 is 8:18 PM which is there, but it reduplicated it at 9:06 PM when I finished watching 1x06.

![image](https://user-images.githubusercontent.com/461871/74186237-46b19700-4c5b-11ea-89bc-97a94bd8c61f.png)

**Comment by mschumacher69** [comment]
@courville did you see my observation above?

**Comment by mschumacher69** [comment]
@courville I've been testing with live scrobbling for more than a week now since you fixed the trakt resume point sync issues and I can confirm that there are no duplicates when scrobbling anymore, although I have noticed that sometimes the time stamp is 1-4 min in the future, but that's not a huge issue.
