### ISSUE TITLE
Play/Pause button needed or DPAD_Center mapped as spacebar

### ISSUE THREAD

**Issue by mo123** [nova-video-player/aos-AVP#296]
It would be great if a Play/Pause UI button can be shown when you press a button while a video is playing. You can already seek so a rewind/forward button is not needed.

On Android media players, you can use an airmouse and press spacebar to pause/play a video but you can't use the DPAD_Center/OK button on the front side of an airmouse to play or pause a video.

So either a Play/Pause UI button that can be pressed with a mouse or keyboard or an extra mapping for DPAD-Center/OK button that works the same as spacebar will help a lot, whatever will work the best.

**Comment by mschumacher69** [comment]
Pressing ok in the center of the dpad pauses/plays on my Android TV remote control.

**Comment by mo123** [comment]
Seems ir remote DPAD middle OK button can pause but airmouse eg. Mele F10 DPAD middle buttons can't pause.

**Comment by courville** [comment]
@mo123 real question is what is the keycode of this mele F10 DPAD middle button to see if I can add this.

**Comment by mo123** [comment]
Seems the keylayout file for the Mele F10 remote online is broken for the remote and only compatible with old Android OS's.
I created a new keylayout file for the remote.
Now Left mouse click is mapped to ENTER and another button is mapped to MEDIA_PLAY_PAUSE and this seems to work correctly now for play/pause.
So the issue is resolved :)
