### ISSUE TITLE
Add Oreo+ tv channel recommendations for launcher

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#3]
Add for Oreo+ Android version TV channel recommendations for the launcher https://developer.android.com/training/tv/discovery/recommendations-channel
Idea would be to have 3 channels: recently played, recently added and playlist.

**Comment by courville** [comment]
Play next even better.

**Comment by courville** [comment]
Implemented.

**Comment by alexanderadam** [comment]
Is this the same functionality [as this one](https://developer.android.com/training/tv/discovery/recommendations) and should this still be working?

Because somehow I can't add a Nova recommendations channel to my home screen.
