### ISSUE TITLE
Scheduled rescan of network content

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#311]
I swear to god there used to be a setting to schedule rescan of network content, but for the love of me I can't seem to find it anymore! Am I going crazy???

**Comment by courville** [comment]
Shouldn't it be a discussion to be held on https://www.reddit.com/r/NovaVideoPlayer/ ?
Scheduled rescan (that is perhaps broken) is available opening network->rescan button.
It is not a setting.

**Comment by mschumacher69** [comment]
I posted there 3 days ago, no one replied...
https://www.reddit.com/r/NovaVideoPlayer/comments/f9g2c2/scheduled_rescan_of_network_content/

It used to be a setting where u could select to rescan at a specific time or at every app launch, I'm certain of that.

Perhaps it used to be in the stable version? I'm on beta now, is this perhaps why this setting is not there anymore?

**Comment by courville** [comment]
On androidTV it is available in the network tile when selecting rescan green tile.

**Comment by mschumacher69** [comment]
Yes that's it thank you!!! I was looking for it under Preferences!
