### ISSUE TITLE
No way to revert to an old versio without deleting cache

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#326]
Hello
Now that the subtitles are broken there is no way to go back to an older version without deleting the cache.
adb install -r -d -f

returns an error and my library is huge.

Could you please provide an option to go back to an older release without deleting the cache.
My only option now is to uninstall and go to an older version and wait the scraper for hours or wait for the fixed release and use other player.

Thank you.

**Comment by courville** [comment]
Android does not provide a way to downgrade easily and cache management is not really under control in an application (at least I do not know of a way).
I recommend when doing the scraping to export NFO and posters so that if a rescrape is needed it will go way faster.
