### ISSUE TITLE
v4.44 not available on the Play Store yet

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#327]
Has v4.44 been published to the Play Store yet? Because I haven't received it yet.

**Comment by courville** [comment]
Is this a code issue? Please refer to reddit release notes. 4.44 has been pushed to release on Google play

**Comment by mschumacher69** [comment]
Sorry I always forget that you have a reddit community. The problem with reddit is that you can't subscribe to email notifications, so I always get email notifications about Nova from github.
