### ISSUE TITLE
Feature Request: Preferred audio language

### ISSUE THREAD

**Issue by DaedalusBLN** [nova-video-player/aos-AVP#334]
As most files nowadays are mkvs with multiple audio and subtitle tracks, I would like to request a preferred audio language selector.

Also have another smaller feature request: display only forced subtitles option (to only show subs for foreign language parts and signs in movies). This will be tougher to implement, but preferred audio language should be as easy as preferred subtitles was.

Thanks for working on this application 😊

**Comment by courville** [comment]
Feature will be release in upcoming 6.2.54 version.

EDIT: only for the default audio language not the subtitle additional request.

**Comment by vertigo220** [comment]
Not sure if this is what OP meant, but there should be an option to show forced subs only by default. That is, if I set English as the preferred language and play a video with regular English subs, they shouldn't be displayed by default, but if I play a video with a forced sub track, it _should_ display by default.

**Comment by Pentaphon** [comment]
@courville this issue can be closed since it was merged and I have a new related feature request here: https://github.com/nova-video-player/aos-AVP/issues/1356
