### ISSUE TITLE
HTTPS (SSL) Support

### ISSUE THREAD

**Issue by DaedalusBLN** [nova-video-player/aos-AVP#335]
Bug: Cannot open some direct links with the app for some reason, the player does not appear in the app select screen while other players do. Could you fix it?

Links are of the format:
https://numericserverno#.download.real-debrid.com/d/something/file.name.mkv

**Comment by courville** [comment]
Thanks for the report, would there be a link I could use to troubleshoot the issue?

**Comment by DaedalusBLN** [comment]
Sure, set up my remote traffic to be used and found a public domain file I could share with you. But I don't want my remote traffic to be abused by people reading this, so I mailed the link to you.

**Comment by DaedalusBLN** [comment]
![Screenshot_20200426-160455](https://user-images.githubusercontent.com/35345064/80308444-c4eff500-87d7-11ea-97cd-d621e0d397b7.jpg)

**Comment by DaedalusBLN** [comment]
@courville did you get the link?

**Comment by courville** [comment]
Yes thank you, did not find time to have a look though. I reviewed manifest and we do register http/https. What app are you using to open the video?

**Comment by courville** [comment]
OK when opening the link in gmail, I have mxplayer that is proposed to open the video link but not vlc nor nova.
I have a way to reproduce now.

**Comment by courville** [comment]
OK reading https://github.com/guardianproject/securereader/blob/master/app/src/main/AndroidManifest.xml helped.
It seems to be a limitation on the Android PatternMatcher (sigh).
Note to self, read the following comments:
```
               <!--
                To match all files with a specific file ending, you have to use this
                craziness because of Android limitations in their regex parser
                https://stackoverflow.com/questions/1733195/android-intent-filter-for-a-particular-file-extension
                https://stackoverflow.com/questions/3400072/pathpattern-to-match-file-extension-does-not-work-if-a-period-exists-elsewhere-i/8599921
                -->

                <!--
                The ultimate in crack smoking!  Some apps will only respect these file associations
                if the mimeType is not set, and other apps will only respect them if mimeType is set
                to */*.  Therefore we have two whole copies of the same thing, besides setting the mimeType.
                -->
```
Note to self again: `<data android:mimeType="*/*" />` does not work.

**Comment by courville** [comment]
Please check following apk and report if it helps in your case: https://drive.google.com/open?id=1cWqm2KVCi_yLBC2259K0gmQRKNatD3SV

**Comment by DaedalusBLN** [comment]
> Please check following apk and report if it helps in your case: https://drive.google.com/open?id=1cWqm2KVCi_yLBC2259K0gmQRKNatD3SV

@courville 
It fixes the issue of Nova appearing in the app selection intent. But can't get any files I tried (mostly MKVs of x264 or x265, often with surround audio I think) to play back, the player briefly pops up and disappears. Tried to turn off hardware decoding too, in case that helps. Check your mail, sent you a fresh link to the same file. See if you are able to actually start the stream on Nova, without downloading the file and playing it off storage. I have no issues with local files whatsoever.

PS: Using Android 10 on a OnePlus 6T.

Thanks for looking into this.

**Comment by courville** [comment]
Yep I can reproduce. I will look into it. Please keep the link live.

**Comment by DaedalusBLN** [comment]
> Yep I can reproduce. I will look into it. Please keep the link live.

Will do! Can also generate some links for other encodings/container types if necessary.

**Comment by courville** [comment]
OK this is linked to the fact that https support has been removed at some point from the native application multimedia engine because of openssl security issue... It will take some time to dig up in history of the mother deprecated Archos Video Player application. You can now remove the link since I have an independent setup to reproduce.

**Comment by DaedalusBLN** [comment]
You're correct. The link I sent you is identical for http non-SSL by the way, removing the s made the file play just fine. Feel so stupid for not checking that with the modified build you sent me, I had tested that with the build from GPlay. So I'll be eagerly waiting for https support to be re-implemented and I can imagine it will take a while. Thanks for the amazing support, you've earned a billion stars! This player shall rule them all soon.

**Comment by DaedalusBLN** [comment]
Any progress on this? I tried searching in the archos repositories for SSL/HTTPS related entries, but I failed.

**Comment by courville** [comment]
> Any progress on this? I tried searching in the archos repositories for SSL/HTTPS related entries, but I failed.

It is because the removal of ssl/https on Archos Video Player has been performed prior to the open-source release.

No progress for now on the topic.

**Comment by courville** [comment]
Closing as duplicate of https://github.com/nova-video-player/aos-AVP/issues/23
