### ISSUE TITLE
SFTP - Deprecated key exchange algorithm

### ISSUE THREAD

**Issue by hovmeister** [nova-video-player/aos-AVP#339]
Hi!

Tried out the sftp connection today, but it refuses to connect to my server.
On the server I get the following error message:
`no matching key exchange method found. Their offer: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 [preauth]`

I have tried this on both my home TV-box and my mobile phone running Android 10.
It seems the nova app uses a deprecated key exchange algorithm, according to what I
found at the [OpenSSH Website](https://www.openssh.com/legacy.html)

Adding one of the offers to the KexAlgorithms option in sshd_config on my server solves the issue, but it is my understanding that this is un-secure. For example:
`KexAlgorithms curve25519-sha256@libssh.org, diffie-hellman-group14-sha1`
While security is not essential for video playback, new users may need to do the same fix to their servers in the future.

I am in no way an expert, but can provide logs and testing if needed.
Info:
- up-to-date headless Arch install, Kernel 5.6.11
- openssh 8.2p1-3

**Comment by courville** [comment]
Thanks for pointing this out. Could you please try out without altering your sshd_config the following apk https://drive.google.com/open?id=1kl31TKM4xSY-m3cMxfavNYvFStpV_wq_
I upgraded jsch from the old 0.1.51 to 0.1.55 that proposes more KexAlgorithms i.e. before
`config.put("kex", "diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1");`
and now:
`config.put("kex", "ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1");`

**Comment by hovmeister** [comment]
I think the link is broken?
Will give it a try ;)

**Comment by courville** [comment]
This link should work
https://drive.google.com/file/d/1kl31TKM4xSY-m3cMxfavNYvFStpV_wq_/view?usp=sharing

Le dim. 10 mai 2020 à 19:05, Henrik Hovrud <notifications@github.com> a
écrit :

**Comment by hovmeister** [comment]
Yes, this APK works without the sshd_config fix :+1:

**Comment by courville** [comment]
OK good thanks for the confirmation.

Le lun. 11 mai 2020 à 12:10, Henrik Hovrud <notifications@github.com> a
écrit :
