### ISSUE TITLE
"Better TV show scrape result through multi-language Levenshtein metric computation"

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#343]
This feature seems to produce worse results than before. It not only does not match anything more than before but produces incorrect matching results. I sent you a sample via email.

Could you please check my suggestion from #287

**Comment by courville** [comment]
Thx for reporting, I will check on the filename scraping. It would be easier to provide the exact filename instead of screenshot though.

**Comment by courville** [comment]
Scraper has completely been reworked since. Closing the issue for now.
