### ISSUE TITLE
not more than 6 audio tracks is available

### ISSUE THREAD

**Issue by darkblaze69** [nova-video-player/aos-AVP#345]
have mkvs containing 7 or more audio tracks.
Nova player offers only first 6 of them.

**Comment by pavelpanasenko** [comment]
Confirm this bug. Only first six tracks available.

**Comment by courville** [comment]
Fixed by https://github.com/nova-video-player/aos-avos/commit/3d5dd9d83a3811b49276afe447f4d1673961c667
