### ISSUE TITLE
[FEATURE REQUEST] More info about subtitle and audio tracks

### ISSUE THREAD

**Issue by Jakub-Cepela** [nova-video-player/aos-AVP#348]
When opening same video file in VLC and Nova, VLC seems to be able to display more information about subtitle and audio track. In this case, one subtitle track is even missing. See pics below.

**VLC**
![image](https://user-images.githubusercontent.com/45459516/84444733-b607b980-ac42-11ea-8d69-eb2f1a8e4eeb.png)
![image](https://user-images.githubusercontent.com/45459516/84444741-ba33d700-ac42-11ea-8ef0-f5a79dd3c021.png)

**Nova**
![image](https://user-images.githubusercontent.com/45459516/84444760-c5870280-ac42-11ea-8cdf-dca83ff53217.png)
![image](https://user-images.githubusercontent.com/45459516/84444768-cb7ce380-ac42-11ea-8db0-8a58205f866c.png)

**Comment by courville** [comment]
Indeed valid request, would be a good enhancement. I put that on my todo list (ETA unclear though).
Contributions welcome.
Note that there is also no BD subs are not yet supported.

**Comment by Pentaphon** [comment]
@courville I believe that v6 has added title support

**Comment by courville** [comment]
Indeed solved in v6.2+
