### ISSUE TITLE
SMB，1080p ，HEVC/h.265, AAC 48000hz stereo,  can load but not play

### ISSUE THREAD

**Issue by Xianbei233** [nova-video-player/aos-AVP#35]
As the title

**Comment by courville** [comment]
Could you please share the first 10s of the video sample and disclose the device on which the issue happens? Thank you.

**Comment by Xianbei233** [comment]
magnet:?xt=urn:btih:XM77HQDFITPN7VGZRC3ZRJZSBIOTWSEU

**Comment by Xianbei233** [comment]
mipad 1, mocha,  ‎NVIDIA Tegra K1 CPU, LOS 14.0

**Comment by courville** [comment]
Checked and works on several platforms. Might be mipad LOS specific.
