### ISSUE TITLE
Support pre-Lollipop devices

### ISSUE THREAD

**Issue by KOLANICH** [nova-video-player/aos-AVP#351]
It may make sense to support older devices.

**Comment by Pentaphon** [comment]
Based on the changes the dev is making, it's not going to happen. We need to move forward instead of supporting ancient devices forever. It's time for you to buy a new device.

**Comment by KOLANICH** [comment]
>It's time for you to buy a new device.

No, it's not. All the new devices are shit.

**Comment by Pentaphon** [comment]
>All the new devices are shit.

That attitude is just going to leave you unable to use any apps on Android when your device becomes completely unsupported. It's only a matter of time. Even the apps you love today will have to stop supporting your device someday.

**Comment by KOLANICH** [comment]
In fact my device is supported by Replicant and even some XDA devs (but I don't trust random XDA devs to build the firmware), but ... damned blobs and damned Google that made it is almost infeasible to build roms to anyone except companies (at least I am sure that my PC doesn't have enough ram for it) :(((( Replicant uses CPU rendering currently and bringing lima FOSS GPU driver is not a priority for them. Replicant also doesn't bring support for other drivers, though their disasm looks pretty straightforward, I guess it is feasible to implement their FOSS replacements. I wonder if I can rebuild/transplant userspace without touching any kernel components and touching the whole google toolchain and maybe without rebuilding everything entirely.
