### ISSUE TITLE
Version 4.49.1-20200704.1437 crashes out on Sony Android TV

### ISSUE THREAD

**Issue by Dandemon** [nova-video-player/aos-AVP#352]
I've replicated this issue on two different Sony Android TVs containing Android 8.  No system updates of any note just prior to the bug occurring.  The incidence happened following the install of 4.49.1-20200704.1437 on about 6 July.

The app crashes out randomly, back to the home screen.  A restart of the whole TV will let you re-open Nova and browse the content (on an SMB server on the LAN), and you can open any movie or TV episode up to the description.  When it goes to play the item, you get a spinning blue circle.  It then either returns you to the description screen without playing, or crashes out to the home screen altogether.

The video content I'm trying to play is very simple:  MP4 in 576p, one audio track in 2 channel stereo.

Re-opening Nova after one initial crash (as per above) will then result in regular crashing, which will happen even without trying to play or browse anything.  The crash back to the home screen will usually happen within seconds of opening the app.

Something's really wrong here.

**Comment by courville** [comment]
Thanks for reporting the issue. 
Are you playing the file from an hard drive hooked up to the TV?
Could you please share the video to software@courville.org ?
It might be the ffmpeg upstep causing the issue.
Are you able to collect adb logs (https://github.com/nova-video-player/aos-AVP/wiki/Debugging)?

**Comment by courville** [comment]
Might be related to this on google play console:
```
java.lang.OutOfMemoryError: 
  at java.lang.Thread.nativeCreate (Thread.java)
  at java.lang.Thread.start (Thread.java:730)
  at com.archos.filecorelibrary.ExtStorageReceiver.<init> (ExtStorageReceiver.java:60)
  at java.lang.Class.newInstance (Class.java)
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:2987)
  at android.app.ActivityThread.-wrap18 (ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1544)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6084)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:755)
```

**Comment by courville** [comment]
Just pushed 4.49.2 please give it a try and let me know if it solves the issue (might take some time to get deployed).

**Comment by Dandemon** [comment]
> Just pushed 4.49.2 please give it a try and let me know if it solves the issue (might take some time to get deployed).

Just did that - the exact same issue crops up with 4.49.2-20200706.  After a restart Nova will load and be stable until you try to play something.  When you do play, it will stop and return you to the Nova home screen.  A few seconds later the app crashes out to the Android TV home screen.  Any subsequent launch of Nova will load it for a few seconds, then quit again.

Any chance we could revert to your last good version?

In answer to your earlier question, the app accesses video data via SMB over a NAS.  There are no issues accessing the NAS using other apps on the same TV.  I did reboot the NAS to check if it was the issue - no difference.

**Comment by mschumacher69** [comment]
Videos were playing fine on 4.49.1 on my Sony TV (also on Android 8), I haven't tested 4.49.2 yet.

**Comment by courville** [comment]
I have tried on a Sony TV to reproduce without success so far.
@Dandemon could you please share the video file for which you reproduce the issue?
Is this possible for you to take adb logs when it happens?
Thank you

**Comment by Dandemon** [comment]
Literally any video file produces the same issue.  I have tried different files each time. After you restart the app it crashes without loading ANY video file.  My app is set to re-scan the network share on launch.

I have looked through some of your other recent notes.  I should tell you that both of the Sony TVs producing the crashes access files off WD MyCloud NAS drives (NOT My Cloud Home, the earlier good ones).

I'm sorry, I don't have the skill to take adb logs off a TV.

**Comment by mschumacher69** [comment]
Just tested on 4.49.2, working fine as well.

**Comment by courville** [comment]
@mschumacher69 thanks for checking: this is also what I observe. I guess that there is something wrong for @Dandemon but without logs I will be clueless...

**Comment by mschumacher69** [comment]
Must be the type of files he's playing. I've tried with regular SD x264 mp4s with regular 2.1 AAC sound, maybe he's trying something more sophisticated.

@Dandemon if you can at least share the type of files you're trying to play with @courville if you don't want to share specific video files.

**Comment by Dandemon** [comment]
> @Dandemon if you can at least share the type of files you're trying to play with @courville if you don't want to share specific video files.

I already have.  It's plain mp4, created with standard settings on Handbrake at 576p.  Two channel audio.  Moreover, these files have never EVER caused a problem over years of Archos (paid) and now Nova.

Even more to the point, reloading Nova results in a crash without loading any video at all.  Barely 4 seconds into the app and it crashes back to the Android TV home page. 

Would it help if I made a Youtube video of all this happening?  I know it's not as good as a log.

**Comment by Dandemon** [comment]
Here's a demonstration of the bug in action:  https://youtu.be/pNVPlvP6Vh0

**Comment by Pentaphon** [comment]
@Dandemon since you're not willing to send him a video sample, could you examine one of your files with https://mediaarea.net/en/MediaInfo and export the info as text so we can see the exact metadata of what kind of files you are trying to play? 

You can also use http://avidemux.sourceforge.net/ to cut out a 30 second lossless section of one of your videos and send that to him if you can't upload an entire movie.

**Comment by courville** [comment]
> Here's a demonstration of the bug in action: https://youtu.be/pNVPlvP6Vh0

thanks for the video. What it tells me is that it is likely not related to video playback.
It would really help to get logs otherwise I will not be able to pinpoint the issue.
The only thing I would recommend is to reset nova (or deinstall/reinstall) AndroidTV settings->application->nova->reset and let me know if it helps. Of course it will force you to rescan all your media content...

**Comment by Dandemon** [comment]
> The only thing I would recommend is to reset nova (or deinstall/reinstall) AndroidTV settings->application->nova->reset and let me know if it helps. Of course it will force you to rescan all your media content...

I deleted and re-installed Nova from scratch.  Tried playing a movie, and within a few seconds the problem came back.  The app then went unstable on any file access or when trying to index.

I re-installed again, and this time I am just indexing (without playing any video content at all).  It hasn't crashed yet.  It's playing videos that triggers the general instability of the app.  Possibly network related, but I can't help wondering if there's a memory leak somewhere, eg in the caching.

**Comment by courville** [comment]
@Dandemon thanks for checking. Your issue is really real and weird. Sorry but with no logs it will be difficult.

**Comment by Pentaphon** [comment]
@courville have you considered adding a custom, built-in logger to Nova itself? That would make it easier for people like Dandemon to send you logs and give you more detailed bug reports from users in general.

**Comment by Dandemon** [comment]
Seems like other people will have to report crashes here before anything will be done.

Does anyone know a way of installing an older version of this app via the Google Play Store on the TV?  I have my elderly father using Nova and he's not able to watch anything until this is fixed.  Not a great situation during covid. :-(

**Comment by Pentaphon** [comment]
> Does anyone know a way of installing an older version of this app via the Google Play Store on the TV?

Just look at the older releases on the github releases page and find the one that worked for you. Then just don't update.

**Comment by Dandemon** [comment]
> Just look at the older releases on the github releases page and find the one that worked for you. Then just don't update.

That's fine, but how do I get that older version into my TV?

**Comment by Pentaphon** [comment]
> That's fine, but how do I get that older version into my TV?

I use X-plore File Manager to start a Wifi server on any device to push APKs to it and then just install with the remote.

**Comment by Dandemon** [comment]
Hold the phone.

It works again. @courville - version 4.49.4-20200709.1136 works perfectly.  Both on mine and my father's Sony Android TVs.  He didn't re-install the app at any time, it just auto updated.

Thank you!!

**Comment by courville** [comment]
Glad that it works!

**Comment by mschumacher69** [comment]
@courville did u manage to figure out what was causing it or did it just get fixed by chance?

**Comment by courville** [comment]
No real clue there.
