### ISSUE TITLE
Scrapping for TV show fails when the year is present in the filename

### ISSUE THREAD

**Issue by lucianolingnau** [nova-video-player/aos-AVP#359]
I just noticed that nova has issues scrapping TV Series which contain a year in it's filename. For example:

- "The Midnight Gospel (2020) S01E02 Officers and Wolves (1080p NF Webrip x265 10bit EAC3 5.1 - HxD) [TAoE].mkv"

It shows up as unidentified in Nova and when I click on "Get Info" it suggests the following search term:

- "The Midnight Gospel (2020) S01E02"

If I manually delete the (2020) from the search term (And it becomes "The Midnight Gospel S01E02" I immediately get a match. Any chance that the scrapper can be improved to deal with this sort of thing? Movies usually have a year in theyr filename but that doesn't seem to cause any issues.

**Comment by courville** [comment]
Unfortunately there is no easy fix for this without introducing some regressions.
One could think that adding a rule to remove the year between parenthesis would be the solution (and it is in your case).
However with shows like Doctor Who there is a 2005 version and the classic one, or Battlestar Galactica (2003 vs. 1973) suppressing the date would lead to an erroneous identification.
Thus "the scene" making the encodings should not put a date when there is no need to discriminate between reboot shows and old ones.
If there is a better solution that I missed, I am open for solutions.
For now a rename is indeed needed.

**Comment by lucianolingnau** [comment]
Hi Marc!

I'm assuming that when you query something like "Doctor Who" on the TVDB API, you would get a list of results, but they would differ based on the "firstAired" property. Wouldn't it be possible to ignore the year in parenthesis when querying TVDB but then use it to match it to the "correct" result from the returned list based on the firstAired matching the year in parenthesis in the filename?

I'm not really familiar with the TVDB API, this was only the first idea that jumped to my mind after having a quick look. And I'm no developer so if I just said something stupid, feel free to ignore. :P

But either way, just knowing it is an issue already helps because then I know for certain that it is an issue and what the workaround is.

Ideally, it should work with the year because you never know when there will be a reboot later on. There is never a reboot until one is released, hehe. I guess that's the dilemma. And when it happens one would not only have to add the year to the old one but also to the new one.

Sometimes it's not even a reboot, but a different show with the same tittle from a different year.
@courville - feel free to close then I guess, to reduce the amount of "stale" issues.

**Comment by courville** [comment]
It should be fixed in latest 6.x releases.
