### ISSUE TITLE
Not working with torrserve

### ISSUE THREAD

**Issue by Net-zen** [nova-video-player/aos-AVP#362]
Player just doesn't  start playing with the latest version of torrserve (https://github.com/YouROK/TorrServe)
It works fine on the previous release of torrserve (except position bookmarks, it's not working on any version) 
But not working with the new release of torrserve (1.1.85).

**Comment by spawnlmg** [comment]
Doesn't start playing from this link
http://127.0.0.1:8090/torrent/play/The.Umbrella.Academy.S02.WEBDL.1080p.LostFilm_The.Umbrella.Academy.S02E01.WEBDL.1080p.LF.RGzsRutracker.mkv?link=magnet:?xt=urn:btih:a6a69aa16442e330d17163ba35ccf00d804a6cc9&dn=%D0%90%D0%BA%D0%B0%D0%B4%D0%B5%D0%BC%D0%B8%D1%8F+%C2%AB%D0%90%D0%BC%D0%B1%D1%80%D0%B5%D0%BB%D0%BB%D0%B0%C2%BB+%2F+The+Umbrella+Academy+%5B02x01+%D0%B8%D0%B7+10%5D+%282020%29+WEB-DL+1080p+%7C+LostFilm&file=0

**Comment by Nemiroff** [comment]
Trouble with cleartext HTTP traffic.
[log.txt](https://github.com/nova-video-player/aos-AVP/files/5034436/log.txt)

**Comment by YouROK** [comment]
Error is that torrserver creates local http server and broadcasts torrent over http. And there are no rights to the local http server. Some people release torrserver to the Internet, there is also an unprotected http

**Comment by YouROK** [comment]
Torrserve for test
https://github.com/YouROK/TorrServe/releases/download/1.1.85/TorrServe_1.1.85.apk

**Comment by courville** [comment]
Ok thx for the details ans logs. Will enable cleartext. Nova should support .torrent streaming natively.

**Comment by darkblaze69** [comment]
the problem seems simple. when this going to be fixed?

**Comment by YouROK** [comment]
Access for all cleartext
https://stackoverflow.com/a/54827498

**Comment by courville** [comment]
@YouROK sorry for following up late. Proposed fix added.
