### ISSUE TITLE
Does Nova Player support mov_text (tx3g) subtitles in MP4?

### ISSUE THREAD

**Issue by ledin74** [nova-video-player/aos-AVP#366]
Hi, I can't get my subtitles to work in my MP4's, Nova Player dosen't find them.

Using a Nvidia Shield 2019, tried playback from both SMB & Internal drive

ffprobe:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:41:07.08, start: 0.000000, bitrate: 2797 kb/s
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 2698 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (HE-AAC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2(swe): Subtitle: mov_text (tx3g / 0x67337874), 0 kb/s (default)
    Metadata:
      handler_name    : SubtitleHandler

**Comment by courville** [comment]
Closing since released in v6.1.6
