### ISSUE TITLE
No clear distinction between watched and unwatched at a movie/episode overview

### ISSUE THREAD

**Issue by lucianolingnau** [nova-video-player/aos-AVP#367]
I find it really handy to be able to distinguish watched from unwatched stuff in lists (when looking at the episodes of a TV show or at a list of all movies).

Weirdly however, this is not clearly visible when looking at a particular episode or movie's details (the screen from where the playback can be started). So currently, I need to look for the "Mark Watched" or "Mark Unwatched" actions to figure out whether I saw it already or not.

Perhaps a small and simple improvement would be to also have the blue "watched" marker on the top right corner of the cover to visibly state whether the episode or movie is watched or unwatched. This would make it consistent with the list views where several episodes or movies are displayed side by side.

But if that's not an option, some other easy and clear indication whether it's watched or not would be nice. :)

**Comment by DrGogu** [comment]
There is already a blue checkmark at the top right corner that shows up for watched items.

**Comment by lucianolingnau** [comment]
> There is already a blue checkmark at the top right corner that shows up for watched items.

Sort of! Only in the list of titles, but not if you open the details of a particular episode.  I've now included two pictures from my TV (sorry, I'm not sure how to grab screenshots from Android TV) to make it clearer what I'm referring to.

![PXL_20201106_165912114](https://user-images.githubusercontent.com/4371185/98393883-38fa3800-205a-11eb-9a94-5fd401118415.jpg)
![PXL_20201106_165905079](https://user-images.githubusercontent.com/4371185/98393885-3992ce80-205a-11eb-8ab1-ddc49ba22ab1.jpg)

**Comment by mschumacher69** [comment]
It's easy to identify watched episodes inside an episode's details, episodes that have the "Mark Not Watched" button would be watched. Episodes that don't have this button would not be watched.

**Comment by lucianolingnau** [comment]
@mschumacher69  From the user's perspective, it makes a ton of sense to repeat the learned pattern of "blue ribbon = watched" instead of using a different pattern on a particular part of the software.

Additionally, the wording is also the exact opposite. "Mark watched" means you haven't watched it yet and "Mark not watched" implies that it was already watched.

I'm not arguing this is the most important thing ever, I'm not even saying it's a bug. But it would improve the user experience in my opinion. It makes sense to use patterns that the user knows and recognizes whenever possible.

**Comment by mschumacher69** [comment]
The wording is not the opposite, watched videos would show "Mark not watched" which means they have been watched.

**Comment by courville** [comment]
@lucianolingnau, you are right and the request is valid.

**Comment by DrGogu** [comment]
Also, watched items are not removed from recently played. I have to
manually mark them unwatched, then watched, then they get off the list.
 Kind of annoying.

**Comment by courville** [comment]
> Also, watched items are not removed from recently played. I have to manually mark them unwatched, then watched, then they get off the list. Kind of annoying.

well a watched item is recently played. Moreover, selecting a watched tvshow item enables to hit next episode.
Kind of nice.

**Comment by courville** [comment]
Track code modifs, see https://github.com/nova-video-player/aos-Video/commit/8c505bfbe08f922beb9191fb03a3b31e1245a6e9 and https://github.com/nova-video-player/aos-Video/commit/f1803b560d26cba69f06ccd135bdcedada6c9758
