### ISSUE TITLE
Webdav support

### ISSUE THREAD

**Issue by heymaad** [nova-video-player/aos-AVP#368]
Is there any plan to implement webdav as media source? I'm sure many would welcome it.

**Comment by courville** [comment]
Indeed, but there is no plan yet for it.
A good start would be to implement in FileCoreLibrary webdav support perhaps using https://github.com/lookfirst/sardine

**Comment by Sec-ant** [comment]
Plus one for this feature, any plan yet?

**Comment by vs40** [comment]
Any updates on WebDAV support implementation?

**Comment by uGeek** [comment]
Is compatibility with WebDAV servers in the plans?

**Comment by uGeek** [comment]
It would be great for Synology QNAP NAS servers via WebDAV, WebDAV servers, Nextcloud, ownCloud, ...

**Comment by jakubzieba** [comment]
Any updates about this feature ?

**Comment by wowdd1** [comment]
+1

**Comment by InitialXKO** [comment]
So there won't be any progress on it.

**Comment by courville** [comment]
This issue has not been closed: it remains thus valid. However it is not the top of my priority list. Contributions welcome.

**Comment by phhusson** [comment]
First draft
I'm not going to push it, I'll try to use this occasion to clean up that code

[webdav-v0.txt](https://github.com/nova-video-player/aos-AVP/files/10512674/webdav-v0.txt)

**Comment by Ceonta** [comment]
This is more powerful than Kodi and not far behind Infuse, but unfortunately it has too few supported network sharing protocols.

**Comment by sdlkhfksl** [comment]
Any updates about this feature ?

**Comment by chris191110** [comment]
https://github.com/nova-video-player/aos-AVP/issues/609

**Comment by chris191110** [comment]
Hope add support for webdav

**Comment by courville** [comment]
FYI I have just pushed new nova release on github (v6.1.1) that contains webdav network shares support: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.1.1
Please test and report any issue.

**Comment by vs40** [comment]
> FYI I have just pushed new nova release on github (v6.1.1) that contains webdav network shares support: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.1.1
> Please test and report any issue.

Doesn't work for me :(
Tried it on Xiaomi Stick 4K and Galaxy S20FE and can't connect via WebDAV.
On Stick it shows short loading animation and goes back to network settings.
On S20FE it shows permanent loading animation.

All credentials are correct. 
And only when I specially make mistake in login/password it shows login error.

Tried it with Koofr and pCloud, both have properly working WebDAV.

**Comment by courville** [comment]
@vs40 I just tested the current build with Koofr and managed to log in on my side (webdavs port 443 i.e. using https://app.koofr.net/dav/Koofr).

**Comment by vs40** [comment]
> @vs40 I just tested the current build with Koofr and managed to log in on my side (webdavs port 443 i.e. using https://app.koofr.net/dav/Koofr).

Can you share screenshot of your server settings?
I'm already tried to write it with/without https, to switch between WebDAV/WebDAVS, to put "dav/Koofr" in main URL and write it in in optional Path menu, but still nothing...

**Comment by courville** [comment]
@vs40, here are my settings:
- select webdavs in dropdown menu
- input app.koofr.net for server address
- input 443 for port
- input /dav/Koofr for path

**Comment by Wolsey20** [comment]
I tried with my Alldebrid account on my Nvidia shield tv but I can't connect always a connection error.
I have entered the correct address and the correct identifier (API key). https://help.alldebrid.com/fr/Outils%20Alldebrid/webdav

**Comment by courville** [comment]
@Wolsey20 could you please details what you have entered on nova to connect?

**Comment by Wolsey20** [comment]
webdavs
Server address : https://alldebrid.com/webdav/
port: 443
Username : APi key
Password : API Key

**Comment by courville** [comment]
Server address is wrong: remove the https://
and /webdav should be in the path not in server address
cf. my earlier post...

**Comment by courville** [comment]
**Please read this before posting login issues** (part of nova FAQ now)

When adding/browsing a webdav network shortcut, you need to fill the following dialog inputs:

* dropdown menu: to select webdav or webdavs network protocol (i.e.: http or https)
* server address: hostname/IP address (i.e. not an url) without specifying the path (e.g. [my.webdav.com](https://my.webdav.com))
* port: usually 443 for webdavs and 80 for webdav (on Synology NAS it is 5006 or 5005)
* path: url path for the server starting with a slash (e.g. `/dav`)

**Comment by vs40** [comment]
> * input /dav/Koofr for path

I see, I was entering it without first slash.

**Comment by phhusson** [comment]
> webdavs Server address : https://alldebrid.com/webdav/ port: 443 Username : APi key Password : API Key

That's not what the documentation you linked mention as password

**Comment by Wolsey20** [comment]
thank you it works

webdavs
Server address : alldebrid.com
port: 443
path : /webdav/
Username : APi key
Password : xxxxxx

**Comment by g1thubusername** [comment]
> FYI I have just pushed new nova release on github (v6.1.1) that contains webdav network shares support: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.1.1 Please test and report any issue.

Great news! But could you please help me to configure it with luckycloud?
This is the info from FAQ:
https://docs.luckycloud.de/en/cloud-storage/webdav

And this is my settings:

![tempFileForShare_20230312-213843](https://user-images.githubusercontent.com/115928563/224572348-768c98d1-d64c-4acd-b267-4a560fe10708.png)

But Nova crashes, when I press OK to connect.
Meanwhile it works via other apps with same settings.

**Comment by psjay** [comment]
Is there a way to switch protocol just by moving arrow keys? 
The current implementation could not focus the protocol selector through arrow movements, so it's not usable on an Android TV.

**Comment by g1thubusername** [comment]
> > FYI I have just pushed new nova release on github (v6.1.1) that contains webdav network shares support: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.1.1 Please test and report any issue.
> 
> Great news! But could you please help me to configure it with luckycloud? This is the info from FAQ: https://docs.luckycloud.de/en/cloud-storage/webdav
> But Nova crashes, when I press OK to connect. Meanwhile it works via other apps with same settings.

Still can't set it up :(
Any help folks?

**Comment by courville** [comment]
@g1thubusername poking in the dark since I do not have an account:
* protocol: select webdavs in the drop down
* hostname: sync.luckycloud.de
* port: 443
* path: /luckydav
* username/password of your account
I would be interested in the crash logs.

**Comment by g1thubusername** [comment]
> poking in the dark since I do not have an account:

I have done everything exactly like that, but it crashes.
You can create your own test account for free and try yourself.

>  I would be interested in the crash logs.

Where can I find crash logs?

**Comment by courville** [comment]
@g1thubusername I might have captured the crash trace on my debug backend: could you please let me know the device model you are using?
Could be related to https://nova-video-player.sentry.io/issues/3993484184
```
java.lang.NullPointerException: Attempt to invoke virtual method 'long java.util.Date.getTime()' on a null object reference
    at com.archos.filecorelibrary.webdav.WebdavFile2.<init>(WebdavFile2.java:63)
    at com.archos.filecorelibrary.webdav.WebdavListingEngine$WebdavListingThread.run(WebdavListingEngine.java:93)
```
This happens in WebdavListingEngine when adding a directory.

**Comment by g1thubusername** [comment]
> could you please let me know the device model you are using?

Samsung Galaxy S20.

**Comment by courville** [comment]
@g1thubusername could you please test this experimental build: https://drive.google.com/file/d/1IYfr52-OTmm-DU8x2o8GSLq1AaGbytx3/view?usp=sharing and report if it is any better?

**Comment by g1thubusername** [comment]
> could you please test this experimental build

Awesome! Now it works! 
Is it ok to install that version on Fire TV Stick 4K as well or it requires different build?

**Comment by courville** [comment]
@g1thubusername you can use this safely on fireTV stick (it contains some other experimental changes, finger crossed).

**Comment by xiaomingleng** [comment]
[Bug]: When I connected to my local WebDAV endpoint without username and keyword, it failed with "You must specify a remote address". Why does it have to be with username and keyword?

**Comment by courville** [comment]
@xiaomingleng, I think this issue has already been reported and what you need is to use anonymous login instead of blank username.
I will code to force "anonymous" login when there is no login provided...

**Comment by Pentaphon** [comment]
@courville this can be closed, no?
