### ISSUE TITLE
[Feature Request] HW Acceleration indicator

### ISSUE THREAD

**Issue by chromer030** [nova-video-player/aos-AVP#375]
Hi , please implement an indicator in UI to show whether the playing video has HW acceleration or is playing in SW mode.
Also a menu or info dialog on settings to show formats which has HW acceleration support on device.
Thanks.

**Comment by courville** [comment]
Information about SW/HW decoding is present in the info activity while playing.
Regarding the other request, it is not the purpose of nova to hw capabilities of a device.
