### ISSUE TITLE
cannot download subtitles while playing a video file

### ISSUE THREAD

**Issue by shrgnshrgn** [nova-video-player/aos-AVP#378]
its not possible to download subtitles while playing a movie/series, if you want to download subtitles you have to search for subs before playing the video, it can be annoying because sometimes you have to try a couple of subs before finding the appropriate subtitle it would be good if we could search the subs while playing the video like we had in the early releases, we still have the option but it just gives an error. thanks.

**Comment by courville** [comment]
Just tested downloading subs during video playback and in my specific test it was working.
Can you please let me know your setup: android product, version, where your video files are located and (local/hdd which filesystem/network storage) and elaborate a little more on your various steps to reproduce?

**Comment by shrgnshrgn** [comment]
Ill try to upload a video when im home. My setup: Android TV 9 running on Xiaomi Mi Box S.
Im using Nova with an external WD my passport 5TB HDD. all files are stored on it. back in april it worked flawlessly im always running the latest google play Nova releases. Thanks.

**Comment by courville** [comment]
One more question: what is the filesystem used on your external hdd?
No need to send a video, I will test this configuration.

**Comment by shrgnshrgn** [comment]
its a NTFS 5tb HDD directly connected to my mi box s via the usb port, hope it helps

**Comment by courville** [comment]
OK just read your message. Meanwhile I tested fat32 and exfat and it works as intended.

**Comment by courville** [comment]
And last test with ntfs and just downloaded subs while watching the tv serie episode.
OK now, I would request the video or even better some logs https://github.com/nova-video-player/aos-AVP/wiki/Debugging when downloading the subs while playing the video.
I trust that there is an issue (this is not the first report of the sort), it is just that I cannot reproduce.

**Comment by courville** [comment]
Jut to be aligned, could you please retest with this apk https://drive.google.com/file/d/1gMPDlty1xgA0wrPdaBMlen8HZUmiD6xe/view?usp=sharing (the one I use that contains latest fixes).

**Comment by shrgnshrgn** [comment]
It's a shame i cannot get you some logs... I updated my nova with the link that you gave me & tried to download the subs it didnt solve the problem... I know 3 other people that have the exact same setup as me and also have the exact same issue... Here is a video of the issue maybe you can get something out of it: https://youtu.be/YoqAerRUtdo

**Comment by courville** [comment]
Thanks for the clear video and a way to reproduce: much clearer now.

**Comment by courville** [comment]
OK found the issue: `PlayerActivity` provides `fileUrl` with a preceding `file://` and not the `VideoInfoActivity`: it needs to be removed.

**Comment by courville** [comment]
Sharing apk for testing: https://drive.google.com/file/d/1EKQxMbxCK5SRF8IVVT02PrlI3hNN9-kN/view?usp=sharing

**Comment by shrgnshrgn** [comment]
Great! Ill try it in an hour

**Comment by shrgnshrgn** [comment]
It works like a charm, just tested it. Thanks!
