### ISSUE TITLE
Nova Video Player does not see subtitles in many MKVs

### ISSUE THREAD

**Issue by DrGogu** [nova-video-player/aos-AVP#384]
For some reason, Nova Video Player does not see the embedded subtitles (mostly PGS) in many MKVs from different sources.  It will not even list the subtitles.  VLC player, Plex, and MX Player see and can display them.  It makes the app unusable.  Is there a fix for that?  I use the latest nVidia Shield.  Thanks.

**Comment by courville** [comment]
PGS is not supported.
Issue is duplicate of https://github.com/nova-video-player/aos-AVP/issues/47
