### ISSUE TITLE
Find a way to quickly find a tv show

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#39]
Idea: add a TV series sorted by alphabetical order like movies by genre.

**Comment by angiotell** [comment]
[20181117_091404.pdf](https://github.com/nova-video-player/aos-AVP/files/2729864/20181117_091404.pdf)
Like this?

**Comment by courville** [comment]
Fixed by https://github.com/nova-video-player/aos-Video/commit/2fe739c82755f34be971fced24028a22c0450892
