### ISSUE TITLE
Smb does not work

### ISSUE THREAD

**Issue by Wolsey20** [nova-video-player/aos-AVP#395]
Bonjour,

Le smb ne fonctionne pas, j’ai essayé sur ma shield tv, mon OnePlus 7 et ma tablette rien ne marche j’ai toujours un message d’erreur de connexion avec la version officielle et la dernière bêta, il n'y a que la version 5.15.7 qui fonctionne.

Merci

Hello,

The smb does not work, I tried on my shield tv, my OnePlus 7 and my tablet, nothing works I still have an error message connecting with the official version and the last beta, there is only version 5.15.7 which works.

Thank you

**Comment by courville** [comment]
Thanks for reporting. I guess this is in front of an SMBv2/3 server. Could you please check that in the settings the SMBv2 support is activated?
If this is the case then I guess some logs would help.

Merci

**Comment by Wolsey20** [comment]
Indeed, smb2 support was not activated by default on version 5.15.10, I activate them and everything works again.

Thank you
