### ISSUE TITLE
SMB linux <20> can't connect

### ISSUE THREAD

**Issue by Argon-D** [nova-video-player/aos-AVP#396]
Hi guys, first of all your app is amazing! i just installed XFCE (ubuntu) and last version of samba. All works exept on my sony tv (android tv), from all my device share works but not from my tv :( i tried many ways but i am stuck with <20> can't connect 
and i dont know how to fix it . Can you help please to try to fix my issue? . With W10 works but i must use XFCE on that computer linked to the TV 

i've installed this version : Samba version 4.11.6-Ubuntu  
Thanks

**Comment by courville** [comment]
SMBv2 support is only available on the beta version of nova (5.x) available here: https://github.com/nova-video-player/aos-AVP/releases/tag/v5.15.10 (take the armeabi-v7a for the sony).
Check also that SMBv2/3 is enabled in settings.

**Comment by Argon-D** [comment]
thanks for the quickly reply, there is any ETA for the official release on Play Store or it will be in beta for the months to come?
I'll let you know of course if i will got some problem with beta rls 
thanks again for the amazin app

**Comment by courville** [comment]
SMBv2 support is out thus let's close this issue.
