### ISSUE TITLE
Please add current version number in about section on preferences. 

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#400]
Hi, right now, development is moving pretty quick and there's a lot of small updates, the github-only versions, and the experimental version as well. It can be a lot for new users who want to report bugs, compare versions, etc. 

I've noticed there's nothing to indicate the version number in the app itself. Can we have the current version posted somewhere in the app itself like in the about section of preferences, so we don't have to check the Android app settings each time to see which version we have installed?

**Comment by courville** [comment]
Task completed
