### ISSUE TITLE
Investigate TheTvDB alternative

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#402]
TheTVDB has notified nova that after change of API to v4, there will be a change of licensing and might become a paid service for apps and users.
It means that probably we need to evolve towards a new online db for tv show scrape.

**Comment by courville** [comment]
cf. https://www.reddit.com/r/NovaVideoPlayer/comments/jvousc/thetvdb_alternative/

**Comment by mschumacher69** [comment]
From the email that I received, it says "License fees are based primarily on usage, company size, and how the data is used."

So maybe because Nova is a free and open source app with no source of income whatsoever (not even ads), you'll get an api license for free (hopefully).

**Comment by courville** [comment]
@mschumacher69 this is what I hope and replied on reddit. But let's keep this issue open to list alternatives and record what other communities are leaning towards.

**Comment by bronnel** [comment]
I hope they will give NOVA a free license , v3 of tvdb will continue to work until march 2021 then v4 will take its place , with a yearly fee of $11 or so .
Here a discussion about a free alternative on kodi forums 
https://forum.kodi.tv/showthread.php?tid=352588
https://www.theshowdb.com/

here is another free alternative
https://www.tvmaze.com/

and there is always themoviedb

**Comment by bronnel** [comment]
here is another free alternative
https://www.tvmaze.com/

**Comment by courville** [comment]
OK reading https://github.com/UweTrottmann/SeriesGuide/issues/762 suggests that we need to switch.

**Comment by mschumacher69** [comment]
If trakt and seriesguide are moving away, I guess you're gonna have to follow suit.

Don't trakt provide episode data, posters and backdrops via their API?

I mean't can't you pull episode data from their API or is their API just for syncing watch progress?

**Comment by bronnel** [comment]
@courville thank you for switching to TMDb for tv show data, it is the right move, everyone is getting away from TVDB,  TVDB was build by the userbase community and now they are asking money for data that was provided by the userbase, well they should go and F**k themselves.

**Comment by courville** [comment]
> @courville thank you for switching to TMDb for tv show data, it is the right move, everyone is getting away from TVDB, TVDB was build by the userbase community and now they are asking money for data that was provided by the userbase, well they should go and F**k themselves.

not finished yet but soon.

**Comment by bronnel** [comment]
thank you , no problem take your time with it, TMDB is perfect , I read somewhere that users are now uploading their data to TMDB instead of TVDB, which means more support and that's what we want.

**Comment by courville** [comment]
Adapting the code to TMDB, I am optimizing the scraping process with caching that should boost the tvshow scraping speed. .. Now I need to iron out all the corner cases.

**Comment by bronnel** [comment]
@courville Great work this would be really awesome.

**Comment by bronnel** [comment]
@courville I have one suggestion , in future when you release tmdb for shows, I think it is a good approach not to get rid of tvdb completely , what I think is best is that  you can make new option in preferences where the user chooses the  source for tv shows data scraping , it should either be tvdb or tmdb, I think it is a good choice , just in case we get a free license from tvdb, I really like this idea , do you agree?

**Comment by mschumacher69** [comment]
Agreed, especially that thetvdb has a per user license as well, so if any user pays for thetvdb subscription, they can make use of it in nova.

**Comment by courville** [comment]
@bronnel and @mschumacher69 in principle I agree with you and this is what I did initially but I ended up with difficult code to maintain. For now unfortunately this is not what is implemented.

**Comment by courville** [comment]
v6 only uses tmdb: closing.

**Comment by Squall-Leonhart** [comment]
shame, the people saying tmdb is perfect obviously have a dog in the race, as TMDB is incomplete, has wrong episode listing and no obvious way to identify what episodes are which via their slow website.

**Comment by mschumacher69** [comment]
> shame, the people saying tmdb is perfect obviously have a dog in the race, as TMDB is incomplete, has wrong episode listing and no obvious way to identify what episodes are which via their slow website.

You do know that TMDB is maintained by the community, so you can update incomplete shows yourself.
