### ISSUE TITLE
SMB Resolver Order Question

### ISSUE THREAD

**Issue by ian1182** [nova-video-player/aos-AVP#409]
With the release of V5.15.16 on 7th January what is the recommendation for setting the "SMB resolver order" option. Checking after the google play store download in my case the option was ticked indicating that "BCAST,DNS" was in use. It is not obvious, to me at least, if it should be ticked or not. Under what circumstances should the option be enabled?

For me it did not seem to cause a problem either way, I could access my Synology NAS (set to min of SMB V2) without any apparent issue independent of how the option was set.

Thanks

**Comment by courville** [comment]
The default setting i.e. resolver order BCAST,DNS is the one recommended since in a home network SMB servers have no real DNS entry. I introduced this setting because it was causing issues for some but this issue has been resolved.

**Comment by ian1182** [comment]
OK, that makes it clearer. I'll leave the option ticked
