### ISSUE TITLE
Enable picture-in-picture mode on Android phones and ChromeOS devices

### ISSUE THREAD

**Issue by cfal** [nova-video-player/aos-AVP#415]
Native picture-in-picture mode would be very useful, especially on Chromebooks, which doesn't work well with the window overlay method.

AFAICT, it's only enabled at the moment for Android TV due to this clause:

https://github.com/nova-video-player/aos-Video/blob/baad60a492651f7a7802edb5635924cd88767cfd/src/main/java/com/archos/mediacenter/video/player/PlayerActivity.java#L1808

Is it possible to enable it? Or are there other outstanding issues that stop it from working well on non-Android TV devices?

**Comment by cfal** [comment]
@courville Any chance you would consider enabling this or would accept a PR to do so?

**Comment by courville** [comment]
@cfal sorry for the late reply on your query.
We have a kind of PIP (window mode available in player mode) on phones and chromebook should inherit the androidTV framework one and option in format tile (need to check that it is working).
Perhaps instead of `ArchosFeatures.isAndroidTV,` we need to use `TvUtils.isTV` to capture chromebooks.
Do you confirm that your problem is chromebook specific?
And PR are always welcome.

**Comment by cfal** [comment]
Thanks for responding! Yes, I can confirm that my problem is Chromebook specific. The popup window doesn't work well and the native PiP integration (which AFAICT only VLC supports atm) works much better and integrates with ChromeOS's own PiP functionality.

**Comment by cfal** [comment]
Thanks for following up on this!

**Comment by Korb** [comment]
The Small Window item is not displayed in the context menu of the [NOVA 6.2.95 f-droid](https://f-droid.org/en/packages/org.courville.nova/) screen.

OS version: Funtouch OS 14
Model: Vivo T1 (4G, V2153)
Hardware version: MP_0.1
Build number: PD22010F_EX_A_14.2.9.0.W20
Baseband version: .HA.1.1.c2-00054-DIVAR_GENSP_PACK-1.29062.107
Kernel version: 4.19.157-perf+, 1 Sat Oct 12 11:14:50 CST 2024
Compile time: 12 Oct 2024 06:06:30
Android security update: 1 October 2024
Google Play system update: 1 October 2024
Software parameter update: 29 October 2024

Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)
