### ISSUE TITLE
v5.15.18 WDMyCloud SMB timeout regression

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#416]
See https://www.reddit.com/r/NovaVideoPlayer/comments/l3vgjp/beta_version_5518/

**Comment by courville** [comment]
I can see two possible source of regression:

- special port
- else with resolver forced to BCAST,DNS

**Comment by spiderdaz** [comment]
hi marc ,ive done some logging and it seems to me that there is an addressing problem again ,the wdmycloud has a 192.168.0.22 address on my network but it seems like its looking for 169.254.7.23 i have no clue as to why ,the address does not respond to a ping ,nslookup gives my virgin media address and cant find domain?? ive linked to the logs from startup after forced stop and no further interaction from me.
    https://drive.google.com/file/d/1kwD2c-81pmITc5RTdemX9kRft_14gfNJ/view?usp=sharing

**Comment by courville** [comment]
@spiderdaz ok thank you for the logs. It tells that your server is not resolved.
I will re-add the UDP IP discovery injection in the cache that should provide a solution for you.
I think that if you keep BCAST,DNS order it should be better.
Now what I do not understand is why the BCAST resolver does not kick in correctly since it picks up a 169.254.X.X address meaning that there is no real valid IP identified...
I will send you a new binary this evening to check.
Thank you again for your support.

**Comment by spiderdaz** [comment]
well i have tried both settings of resolver order with force stops inbetween and the results are the same. i have noticed that after it times out on this device selecting another device afterwards also times out until i try a second time.

**Comment by courville** [comment]
OK I see in the logs that you are not using the latest build I shared. Let's try this one (simplified SMB probing) with all the corrections I found out so far: https://drive.google.com/file/d/1ZiKE3_RMZ_j-8aiduFWEQxL25zsLIgM2/view?usp=sharing file is Video-TEST15.apk.
DNS resolver fails in your case thus please use BCAST,DNS resolver order and let me know if there is any improvement. Logs welcome too.

**Comment by spiderdaz** [comment]
yes those logs were from the latest test apk you sent me.
test 15 is giving the same results except when in dnsbcast order the error on screen says failed to connect to 169.254xxxx which it wasnt earlier.
so logs here ,from start after forced stop ,resolver order bcastdns option ticked.
https://drive.google.com/file/d/1yO1T2cXxQ1ln2RqrlZbsfjxm5AGEOK2d/view?usp=sharing

**Comment by courville** [comment]
@spiderdaz ok thanks for the testing, logs and report. Will dig it up.

**Comment by spiderdaz** [comment]
marc ,im sorry for messing you around, but it seems i have sorted it after a fashion.
in the ui for the wdmycloud i changed its name ,which presumably flushed its address cache or something ,it immediately started to respond. i have changed the name back again to check and it now seems to be working. its odd because its only the nova player program that was affected ,everything else on my network including the shield could access and use it as normal.i had obviously tried various reboots of the wdmycloud ,my router etc before trying this.let me know if you want a log of its now normal operation and thanks once again for your time and help.
edit
this is working with the default resolver order.i.e box not ticked.

**Comment by courville** [comment]
@spiderdaz thanks for the context: this explains the behavior. When using network shortcuts with nova it registers it with the name of the SMB share (that has been changed I guess when you renamed it on your wd interface). Thus when trying to access the share via the shortcut, it failed to resolve the name into the address (hence resulting in the 169.254.x.x reporting).
No need for logs for now.
And thanks to this back and forth, I know now that my new SMB client configuration is working with WD.

**Comment by spiderdaz** [comment]
I think you may have misunderstood me. The failure to read the SMB share occured when I updated the nova APK. It was previously working fine.
It was only after checking the logs and trying to understand any differences between the 2 identical devices that I decided to alter the display name within its client UI. This is when it started working again . So the cause is still unknown, I think hopefully coincidence as to why  it was not resolving the correct address.
I don't know where the address  is stored,would it be on the shield,router or on the wdmycloud itself??

**Comment by courville** [comment]
OK thanks for the clarification: re-opening the issue.
Perhaps the link was registered not to the NAS name and to the NAS IP address for some reasons but I do not see this in the logs.
The way it is designed, only NAS share name should be referenced which makes it stable even if NAS address changes.
But perhaps playing around with resolver order this changes something (though it should not). I will check this.

**Comment by courville** [comment]
OK what is strange is that the BCAST resolver returns a result with no find:
```
21:26:50.042 [Thread-9] DEBUG jcifs.netbios.NameServiceClientImpl - Resolved 'WDMYCLOUD' to addrs [WDMYCLOUD<20>/169.254.7.23] via RESOLVER_BCAST
```
In your case anyway DNS resolver never kicks in (but this is not an issue).

**Comment by spiderdaz** [comment]
The IP address of the devices is fixed also through dchp reservation at the router, I also double checked the reservations and that the address and name resolved correctly from Windows while the problem with nova still existed.  By my understanding when using broadcast the program asks all network devices to report Thier name and IP ,is this correct ? And does it mean that the wdmycloud was for some reason spitting out no IP or an unreachable ip in response to nova, or does nova itself keep a cache which may have been compromised during the update?
As soon as I changed the name ,on restart nova correctly picked up the new share name and IP and the original name was missing from the network list.

**Comment by Pentaphon** [comment]
So v5.15.18 is in beta now? I haven't gotten v5.15.17 in the stable Play Store. I just have v5.15.16.

**Comment by courville** [comment]
> So v5.15.18 is in beta now? I haven't gotten v5.15.17 in the stable Play Store. I just have v5.15.16.

Play Store still in v5.15.16, beta went through v5.15.17 and is now v5.15.18. Trying to get a sense of new v5.15.18 config on 2k users before going full scale.

**Comment by spiderdaz** [comment]
I'm still running the test 15 that you sent me, should I be changing to the playstore beta ? Don't know if I'm ahead or behind the curve??

**Comment by courville** [comment]
> I'm still running the test 15 that you sent me, should I be changing to the playstore beta ? Don't know if I'm ahead or behind the curve??

you are ahead of the curve. Update will be proposed when I update the beta track anyway.
Do not forget to remove the logs (logback.xml) otherwise it will slow things up.

**Comment by courville** [comment]
Closing the issue. Will reopen if need be.
