### ISSUE TITLE
Cannot play video

### ISSUE THREAD

**Issue by damngood18** [nova-video-player/aos-AVP#418]
Recently, Nova can't play most of my video files.  I'd like to keep using it but will have to look for another media player for my Nvidia Shield---Samsung Tv.  My samsungs (2016 tv) native media player has no problems.  I found Nova much neater though.

**Comment by courville** [comment]
Can you please elaborate a little more on the problem seen and use case to reproduce (where the video files are located, is it a recent issue, etc.)?
I am using nvidia shield without a problem on my side.
Taking logs would help too to figure the issue you are specifically experiencing: https://github.com/nova-video-player/aos-AVP/wiki/Debugging

**Comment by Pentaphon** [comment]
> My samsungs (2016 tv) native media player has no problems.

It sounds like you mean over DLNA? You need to give us more details. I have no problem playing videos on Nova, even over DLNA.

**Comment by Pentaphon** [comment]
@courville I would suggest you close any issue where the author doesn't get back to you with more information within 6 month's time which is plenty of time to respond. This issue, for example is nearly a year old and the author didn't even give you any information to start with. If people are not willing to even respond to you to fix their issues, it is not fair to you to have your issue box cluttered with useless issues that go nowhere.

**Comment by courville** [comment]
Closed due to inactivity.
