### ISSUE TITLE
remove delete file in upnp

### ISSUE THREAD

**Issue by MD77MD** [nova-video-player/aos-AVP#429]
deleting a file whlie browsing in upnp mode, results in the app crashing... although it works fine in smb mode...

 i suspect that deleting files is not possible in upnp mode that's why the app crashes... i would suggest removing the delete option while in upnp mode

**Comment by courville** [comment]
Just for clarification sake, I take that this remarks applies to the phone/tablet interface. The leanback TV one seems to be immune.
