### ISSUE TITLE
FTP中文显示乱码

### ISSUE THREAD

**Issue by homeboy-xie** [nova-video-player/aos-AVP#431]
华为Mate 30，从Google Play下载的版本以及github下载的正式版FTP中文均显示乱码。但测试版6.0.5-6都正常。
![Screenshot_20210320_144957_org courville nova](https://user-images.githubusercontent.com/33028584/111862086-ddd43c80-898d-11eb-9db3-15d7034ea607.jpg)

**Comment by courville** [comment]
Translation: "For Huawei Mate 30, the version downloaded from Google Play and the official version of FTP downloaded from github all show garbled characters. But the test version 6.0.5-6 is normal."

Thanks for pointing this out: I have been working on improving the ftp support and did not know that it had a positive impact on the foreign language support. Good to know. It will thus be fixed when releasing 6.x version.
