### ISSUE TITLE
Watch state not syncing with trakt

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#434]
None of the Formula 1: Drive to Survive episodes synced with trakt for some reason.

Edit 1: None of the shows are actually syncing with trakt anymore.
Edit 2: Another show just synced actually, not sure what's going on...
@courville

**Comment by mschumacher69** [comment]
@courville any idea why is it not syncing with trakt?

**Comment by courville** [comment]
Should be fixed in 6.0.34. See https://github.com/nova-video-player/aos-AVP/issues/519
