### ISSUE TITLE
SMB connection not working in latest version for Android TV I downloaded from Google Playstore: 5.15.19-20210319.1842

### ISSUE THREAD

**Issue by silverag123** [nova-video-player/aos-AVP#441]
SMB connection not working in latest version for Android TV I downloaded from Google Playstore: 5.15.19-20210319.1842
I am using shared folder on Windows 10 within domain and player detect my PC but keep asking for user/password - whatever I enter, it won't login but keep asking for user/password. The same folder is visible in VLS so it is not due to problems in sharing.

Problem is the same with SMB v1 and v2 (and I also set SMB1 in Windows 10 but problem is also present).

**Comment by courville** [comment]
Could you please try to change in nova settings the SMB resolver order and
retry after a force close of the application?
Was it working on an earlier version of nova?

Best regards,

Le sam. 10 avr. 2021 à 03:15, silverag123 ***@***.***> a
écrit :

**Comment by silverag123** [comment]
Thanks for fast reply!
OK - I turned option "SMB resolver order" on, but no luck - problem is the same. Player shows my Laptop in network option but when I click on it, it keeps asking for user/pass and whatever I use - and I tried combination domain;username for username and only username without domain - both with proper password and combinations that works in VLC.

This is my first use of Nova player and I did not try any older versions. I am willing to try if you can tell me where to download older versions (Google Playstore has only last one)

**Comment by courville** [comment]
OK sounds like in your case, I need to add the domain parameter. 
I will share a test build when I have time to see if it solves your issue.

**Comment by silverag123** [comment]
Excellent! Inform me where to download APK to try. Thanks in advance!

**Comment by courville** [comment]
Merged in last version.
