### ISSUE TITLE
Whenever I click shared smb folder app crashes

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#448]
Basically title.

**Comment by courville** [comment]
Basically can you please provide more details (SMB server type, android device used, logs, etc...)?

**Comment by okan35** [comment]
Phone is Sony Xperia xz premium android 9,
Smb data is in the screenshot, imgur.com/a/vfFnXh5

Even if you clean app data when you go.to left menu and click shared smb folders it just crashes.

Dont know what kind of logs I can provide.

**Comment by courville** [comment]
OK this is SMB1, could you please disable SMB2 support in nova settings, force close app and see if it helps?
This is strange that it crashes (I do not experience this).
In terms of logs adb logcat logs would be nice: https://github.com/nova-video-player/aos-AVP/wiki/Debugging this would capture the android app crash at least.

**Comment by okan35** [comment]
Yep, that was it. I disabled smb2  and reentered smb address and it worked no crashing. I will try for logs.

**Comment by courville** [comment]
OK thanks for the confirmation. I am very interested in getting the logs to fix it.

**Comment by okan35** [comment]
So I tried again and got the log, it is this error;

05-07 18:56:47.382 10659 10744 E AndroidRuntime: FATAL EXCEPTION: Thread-9
05-07 18:56:47.382 10659 10744 E AndroidRuntime: Process: org.courville.nova, PID: 10659
05-07 18:56:47.382 10659 10744 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=576 srcPos=2541 dst.length=6 dstPos=0 length=6
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at java.lang.System.arraycopy(Native Method)
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at jcifs.netbios.NodeStatusResponse.readRDataWireFormat(SourceFile:80)
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at jcifs.netbios.NameServicePacket.readResourceRecordWireFormat(SourceFile:241)
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at jcifs.netbios.NodeStatusResponse.readBodyWireFormat(SourceFile:62)
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at jcifs.netbios.NameServicePacket.readWireFormat(SourceFile:128)
05-07 18:56:47.382 10659 10744 E AndroidRuntime:        at jcifs.netbios.UdpDiscovery$UdpDiscoveryThread.run(SourceFile:197)

**Comment by courville** [comment]
Realignement of UdpDiscovery with latest version of jcifs-ng probably required. @nnoury please check.

**Comment by courville** [comment]
@okan35 could you please check out if this build https://drive.google.com/file/d/1qgp3CpYnxMgMicdvrwVRNL8QPgF3KpaQ/view?usp=sharing solves the issue on your side?
Since I am not (yet) able to reproduce, I am trying to blindly solve the problem.
One question: are you using a VPN when using nova?
Thx

**Comment by okan35** [comment]
It is very interesting that I never thought of this because for some apps I turn off blokada ad blocker which uses dns blocking for ads.

  I just tested couple of times and whenever I turned on blokada nova app didn't even open, it crashed from beginning and when I turn off blokadait works. I will try with the app you gave and let you know.

**Comment by okan35** [comment]
It still keeps crashing with app you sent when blokada is turned on. When I turn it off, nova works.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by courville** [comment]
@okan35 could you please get me the log of the crash with blokada turned on?
Especially if you could also tell me what is displayed here after this (i.e. if it is 576)?
```
D UdpDiscovery: UdpDiscoveryThread: size (snd|rcv)_buf 576
```

**Comment by courville** [comment]
Scratch that: I am now able to reproduce with blokada.

**Comment by okan35** [comment]
That is it then, great that you are able to produce. So it what I gave before ? Array out of bound error ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by courville** [comment]
> That is it then, great that you are able to produce. So it what I gave before ? Array out of bound error ? 

yep this is why I am using this very same issue.
