### ISSUE TITLE
Problem with Nova Video Player for Andriod TV

### ISSUE THREAD

**Issue by dellt211** [nova-video-player/aos-AVP#453]
Hi, I'm most likely the less tech savvy person around.  I have been using the Nova player for our television for some time now without any problems.  However, it seems for about the last month or so, Nova fails to see many of my videos.  

There also appears to be a limitation of total files, since it will not see any files titled A-T except for around 970 when in fact there are over 1200.

I stream videos from my computer (Win7) to the television via home network.  But recently I found that Nova refuses to see any video with a title that begins past the letter T (U-Z it does not see).   

Also it seems to now only able to add 998 max videos,  however I can't even reach that number, but only sees 971 max of mine.    It used to handle over 3k videos.    

I loved this app (when it was working properly) and hope this is something simple and can be fixed.  I have uninstalled and reinstalled Nova many times, same outcome.
Has Nova had an update recently that could explain this?   If so, how can I go back to the older version that worked.

Like I said, I'm not very savvy and Nova was easy using UPNP?,  I'm hoping this is something easy to fix.  

Also, I plugged in a new drive and installed a fresh Windows 7 Ultimate, hoping maybe that would fix it, it did not.  Also, using the VLC app, it does see all the videos however Nova cannot.

Thanks in advance for any ideas on a possible fix.

Dell

**Comment by dellt211** [comment]
Finally got it to list/show more than 1k videos, at last.  Seems there may be a limit to amount within a single folder.  I split them up and got over the 1K mark.  It still does not list the entire amount but it's presently within a 100 or so.

**Comment by courville** [comment]
Thanks for reporting this issue and sorry for the late reply.

Do you confirm that you observe this issue on UPnP browsing?

BR,
