### ISSUE TITLE
Crash on HarmonyOS TV

### ISSUE THREAD

**Issue by yulelong** [nova-video-player/aos-AVP#460]
NOVA keeps crashing once I launched it on my Huawei TV (HarmonyOS 2). 
I've tried following steps, yet this issue remains.
- installing and uninstalling v6/v5/v4
- rebooting my TV
- grant file access permission

The Download/org.courville.nova//nova.log file is empty (0 bytes).
How can I help to solve this?

**Comment by courville** [comment]
Hi, thanks for reporting the issue.
What would be helpful is to get some logs (adb logcat) of the crash since I do not own an HarmonyOS based device.
Could you please check if you can get these following https://github.com/nova-video-player/aos-AVP/wiki/Debugging ?
Thank you

**Comment by yulelong** [comment]
> 
> 
> Hi, thanks for reporting the issue.
> What would be helpful is to get some logs (adb logcat) of the crash since I do not own an HarmonyOS based device.
> Could you please check if you can get these following https://github.com/nova-video-player/aos-AVP/wiki/Debugging ?
> Thank you

Unfortunately, ADB debugging is not supported on Huawei HarmonyOS TV sets...
Stranger still, NOVA works fine on my Huawei HarmonyOS phone.

**Comment by yulelong** [comment]
KODI uesd to crash on HarmonyOS TV as well, and they figured out a solution (see: https://github.com/xbmc/xbmc/pull/19171)
Hope this will help if it's similar here.

**Comment by courville** [comment]
Thanks for sharing Kodi's fix.
Please try this Kodi inspired blind fix on nova and report if it helps: https://drive.google.com/file/d/14SBFN0T6kjHm8VVPM8HU1E9C-cphKHWZ/view?usp=sharing

**Comment by yulelong** [comment]
thanks for looking into this. unfortunately, nova still crashes...

**Comment by courville** [comment]
Damn... I will thus need logs to pinpoint the issue.
I read that you could enable adb (wireless) on the Huawei TV.
Could you please give it a try?

**Comment by yulelong** [comment]
No, I can only access certain files using FX Explorer, and I can not enable adb on Huawei TV... There's no such option in settings (even if I clicked the build number many times)
I have also confirmed this at club.huawei.com, which really sucks...

**Comment by courville** [comment]
OK I will figure out how to (re)enable  the Download/org.courville.nova/nova.log and get back to you.

**Comment by courville** [comment]
Sorry for the late reply: could you please try out this test apk that has some crash reporting to a debug backend for me to be able to see errors: https://drive.google.com/file/d/1jJnt5Sb4_r5Katat0rxVSgX4a5GrFNbg/view?usp=sharing
Thanks

**Comment by yulelong** [comment]
still, nothing in the log file...i attempted to delete the existing nova.log file, and then run nova. once nova crashed, the nova.log was created automatically again, but was still 0 byte

**Comment by yulelong** [comment]
by the way, this version runs for a bit longer time than previous versions does, i can even see the settings button show up. previous versions immediately crashes when i run them...

**Comment by courville** [comment]
Thank you for your testing with this special version that reports crashes to my acra backend.
Crash is:
```

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$AsyncFutureTask.done(AsyncTask.java:429)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
	at android.content.ContentResolver.insert(ContentResolver.java:1840)
	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.createChannel(SourceFile:370)
	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.doInBackground(SourceFile:335)
	at com.archos.mediacenter.video.leanback.channels.ChannelManager$CreateChannelTask.doInBackground(SourceFile:326)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```
This is related to channel management that apparently I did not completely removed for harmonyOS

**Comment by courville** [comment]
I just have uploaded a new version of a test apk that could fix the issue https://drive.google.com/file/d/1jJnt5Sb4_r5Katat0rxVSgX4a5GrFNbg/view?usp=sharing on same link. If you are not tired of testing please give it a shot and report. Thanks.

**Comment by yulelong** [comment]
Oh i see... i thought i should get the log file and report it to you... tried the newest version, and you can check the new log now, bro

**Comment by courville** [comment]
Apparently the app you run is still 5.14.21 and I should have uploaded 5.14.22 with the proposed fix.
Please use this fresh link [Video-TEST2.apk](https://drive.google.com/file/d/1sGIagOwRMD1qYD0yVQJgDGRqtkbdR4GT/view?usp=sharing) and let me know if it is any better.
Sorry for the inconvenience.

**Comment by yulelong** [comment]
hi, i have tested test2.apk already. still crashes however, please check the log. thanks!

**Comment by courville** [comment]
Same player shoot again: https://drive.google.com/file/d/1O1Rx0bfiElWKekIZLNQCgeKABWpRSYHA/view?usp=sharing

**Comment by yulelong** [comment]
finally! fixed! nova doesn't crash anymore! thanks for your efforts, bro!
