### ISSUE TITLE
Crash when back button clicked on smb discovery

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#470]
Click back button when smb servers ar being discovered, after this app goes to crash loop when Shared smb is clicked.

Enabling smbv2 support from preferences doesn't solve the issue.

**Comment by courville** [comment]
Could you tell me more (device/phone/tv, version of the app) and get logs (https://github.com/nova-video-player/aos-AVP/wiki/Debugging)? Unfortunately I cannot reproduce.

**Comment by okan35** [comment]
Version is the one from GitHub releases, sony Xperia premium android 9, I try to get logs from your link or android studio itself

Can you send me a debug app to get logs ?

It is the same as last time I gave this log.

pastebin.com/9WrEctZH

**Comment by courville** [comment]
On github relases there are many releases. Do you confirm it is 6.0.11?
Sorry but pastebin provided is empty.
Best way to get logs is through adb via usb.

**Comment by okan35** [comment]
I did get them through usb adb logcat. It was the same as the last error. It this crash.

--------- beginning of crash
09-03 09:26:12.776 30961   798 E AndroidRuntime: FATAL EXCEPTION: Thread-12
09-03 09:26:12.776 30961   798 E AndroidRuntime: Process: org.courville.nova, PID: 30961
09-03 09:26:12.776 30961   798 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: src.length=576 srcPos=2109 dst.length=6 dstPos=0 length=6
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at java.lang.System.arraycopy(Native Method)
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at jcifs.netbios.NodeStatusResponse.readRDataWireFormat(SourceFile:80)
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at jcifs.netbios.NameServicePacket.readResourceRecordWireFormat(SourceFile:241)
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at jcifs.netbios.NodeStatusResponse.readBodyWireFormat(SourceFile:62)
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at jcifs.netbios.NameServicePacket.readWireFormat(SourceFile:128)
09-03 09:26:12.776 30961   798 E AndroidRuntime:        at jcifs.netbios.UdpDiscovery$UdpDiscoveryThread.run(SourceFile:197)



It is the last release 5.15.21 I downloaded from github release, the release from 2 days ago.

**Comment by courville** [comment]
OK I see now. This is thus the same as https://github.com/nova-video-player/aos-AVP/issues/448

**Comment by okan35** [comment]
Yeah I also saw it later, I thought this was different as the app is newer but yeah this same issue.

**Comment by courville** [comment]
Thanks for the confirmation, let's follow the progress on the other issue.
