### ISSUE TITLE
MainFragment jumping focus issue during rescrape with 6.0.14

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#474]
See https://github.com/nova-video-player/aos-AVP/issues/469

> Did a fresh install of 6.0.14 arm64 and after adding some SMB drives and starting to scrape the selection will automatically always jump to the top row (Movies for me). Making it virtually impossible to use while scraping. It doesn't exhibit that behavior in preferences, only on the main screen (including the far left selection row- it will always jump to "All movies"). When scraping is done it randomly jumps back to the top row for no reason.

@HDGuy, I do not reproduce this one: could you please tell me which row options you have selected in settings?

**Comment by ghost** [comment]
Have the same 'problem' having all rows activated except the new additions and recently watched.

**Comment by courville** [comment]
With above settings issue is reproduced and confirmed.

**Comment by HDGuy** [comment]
Even with all rows off it’s still happening- jumps back to the top during scraping then random jumps back to the top “Movie”  selection afterwards.

**Comment by courville** [comment]
OK I managed to get it again: could be linked to this code path:
```
DEBUG c.a.m.video.leanback.MainFragment - onLoadFinished: cursor id=45
DEBUG c.a.m.video.leanback.MainFragment - onLoadFinished: NonScrapedVideos cursor ready with 1
DEBUG c.a.m.video.leanback.MainFragment - updateNonScrapedVideosVisibility
DEBUG c.a.m.video.leanback.MainFragment - checkInitFocus: mLastAddedInitFocus=NEED_FOCUS, mLastPlayedInitFocus=NO_NEED_FOCUS, mWatchingUpNextInitFocus=NOT_FOCUSED
DEBUG c.a.m.video.leanback.MainFragment - checkInitFocus: LastAdded loader ready and needs focus and row is absent
DEBUG c.a.m.video.leanback.MainFragment - checkInitFocus: sets focus on row 0 with animation if above rows were not visible it happens on network first
```

**Comment by courville** [comment]
@HDGuy, @jaqarll  please check if latest 6.0.22 has fixed the issue on your side.

**Comment by ghost** [comment]
@courville seems fixed here.

**Comment by courville** [comment]
Please reopen if you witness the issue again (one never knows).
