### ISSUE TITLE
Smb broken, can't login to smb drive 

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#478]
Smb is not working anymore after the auto-update of the beta version of nova via the play store.

When I try to access my smb drive and insert my login details it just throws me back into the prior screen. 

Have tried smb1 and 2 and neither works. Have this issues on Google TV and my smartphone.

Maybe connected to #448?

**Comment by courville** [comment]
Indeed:
```
09-14 21:15:01.423 23475 23475 E AndroidRuntime: FATAL EXCEPTION: main
09-14 21:15:01.423 23475 23475 E AndroidRuntime: Process: org.courville.nova, PID: 23475
09-14 21:15:01.423 23475 23475 E AndroidRuntime: android.database.sqlite.SQLiteException: Can't downgrade database from version 2 to 1
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:540)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at com.archos.filecorelibrary.samba.NetworkCredentialsDatabase.open(SourceFile:192)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at com.archos.filecorelibrary.samba.NetworkCredentialsDatabase.saveCredential(SourceFile:125)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at com.archos.mediacenter.video.browser.ServerCredentialsDialog$2.onClick(SourceFile:160)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(SourceFile:167)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-14 21:15:01.423 23475 23475 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```
And not related to https://github.com/nova-video-player/aos-AVP/issues/448

**Comment by courville** [comment]
I think I see what happened. Do you confirm that you tested a recent 6.xx build? If this is the case the nova internal NetworkCredentialsDatabase version got updated to version 2 and is remanent even after app suppression. This creates a crash in the expected version 1 of NetworkCredentialsDatabase with nova 5.xx version.
Only 6.xx users getting back to 5.xx will be affected (and it needs to be fixed).

**Comment by courville** [comment]
Easy fix: go in android settings -> apps -> nova and clear cache (to purge NetworkCredentialsDatabase cache).
Other remedy: install latest 6.0.17 version from github on top of 5.xx latest version.

I will fix it properly in a new 5.xx version.

**Comment by ghost** [comment]
Installing the new version did the trick,  thanks!

One question: why did the play store version update over the manual version with a higher version number?
