### ISSUE TITLE
Embedded subtitle cant be chosen

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#480]
Basically you cant choose or even if you choose it doesn't show the subtitles, not sure how İ can help with this issue other than sending the episode file itself.

**Comment by courville** [comment]
If these embedded subs are PGS subs it is normal since nova does not support it yet cf. https://github.com/nova-video-player/aos-AVP/issues/47

**Comment by okan35** [comment]
I don't know if it is PGS, I just know that vlc is able to show in subtitle choices while nova does not show at all in subtitle choices. I will check if it is PGS.

**Comment by courville** [comment]
Closing the issue as duplicate of https://github.com/nova-video-player/aos-AVP/issues/47 until proven wrong (feel free to reopen issue if this is not the case).
