### ISSUE TITLE
App trying to connect unknown domain

### ISSUE THREAD

**Issue by arnabghorui** [nova-video-player/aos-AVP#481]
I just installed this app. I have Blokada adblocker installed which has a logger that shows all the connection requested. Whenever I open Nova player it tries to connect the domain "ckaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa". That's it, no .com or something. I'm attaching a screen shot. 
App installed from f-droid via IzzyOnDroid repo
![Screenshot_2021-09-17-19-46-02-45_28e7e250715ee4f6466531e60931a5bc](https://user-images.githubusercontent.com/61308067/133797663-5df0ad43-5d50-4653-bae6-ae43036e9d8d.jpg)
.
Version: 6.0.17

**Comment by courville** [comment]
This is strange indeed. Looking at "ckaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" refers more to udp nbtscan pattern and could be triggered by nova scanning the local network for SMB shares.
Blokada putting in place a VPN, and nova before 6.0.17 was prioritizing vpn over other network interface causing coexistence issues and could explain this.
I do not explain for now why blokada is classifying this as a domain.
