### ISSUE TITLE
Smb folder button doesn't show when connected to mobile internet

### ISSUE THREAD

**Issue by okan35** [nova-video-player/aos-AVP#483]
Instead it should show it but disable or give a warning that it can't connect since it is not on the same network.

Because of this when I was on mobile internet I couldn't see my smb folder so I cleaned app data thinking there was something wrong and noticed after this that I was not on my wifi. ![Screenshot_20210919-180219.png](https://user-images.githubusercontent.com/19223877/133935101-ff22a1f4-b5ef-4774-90fb-56649fd245e2.png)

**Comment by courville** [comment]
I understand your point but it has been the way nova works since day one. No plan is made for now to change this behavior.
