### ISSUE TITLE
Add playback speed speed

### ISSUE THREAD

**Issue by Thewisem** [nova-video-player/aos-AVP#486]
Could you please add playback speed?
You could do it the newpipe or vlc way and have a bar that increases or decreases the speed
Or
You could just have options like 0.25,0.50,0.75,1.0 etc till 3.0.

**Comment by Pentaphon** [comment]
That seems more for a general video player than a media center type player, which Nova is. I'd use another player for that.

**Comment by courville** [comment]
This is TBD see https://github.com/nova-video-player/aos-AVP/issues/10
Closing as duplicate.
