### ISSUE TITLE
implement binge watching repeat mode

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#494]
Subject says it all.

**Comment by Korb** [comment]
What is this mode available in the “Play mode” menu? Unlike other items, its name doesn’t mean anything to me.

**Comment by courville** [comment]
@Korb this mode allows to play tv shows episodes sequentially like when you are binge watching.

**Comment by Korb** [comment]
@courville, "Play mode" := "Folder", I understand, thanks for the clarification!

**Comment by courville** [comment]
@Korb this is not folder mode. It works irrespectively of the location of your files if the tv show episodes are indexed.
