### ISSUE TITLE
Nova always plays first audio track rather than audio track matching system language

### ISSUE THREAD

**Issue by thataboy** [nova-video-player/aos-AVP#497]
Nova appears to always plays first audio track regardless whether it matches the system language

For example, given

`
Video: MPEG4 Video (H264) 1920x1080 23.976fps [V: h264 high L4.0, yuv420p, 1920x1080 [default]]
Audio: DD+ 48000Hz 6ch 256kbps [A: French [fre] (eac3, 48000 Hz, 5.1, 256 kb/s) [default]]
Audio: DD+ 48000Hz 6ch 256kbps [A: English [eng] (eac3, 48000 Hz, 5.1, 256 kb/s)]
`

it will play French audio even if system language is English. I think it should prefer the English track.

Thank you for your consideration

**Comment by Pentaphon** [comment]
@courville this has been fixed by the preferred audio option in https://github.com/nova-video-player/aos-AVP/issues/334 so it can be closed
