### ISSUE TITLE
6.0.28 What platforms support Dolby Vision?

### ISSUE THREAD

**Issue by HDGuy** [nova-video-player/aos-AVP#501]
It’s not working on my 2019 Shield Pro and it doesn’t appear ExoPlayer is part of this build, so I’m curious what hardware supports it?

**Comment by phhusson** [comment]
I'm pretty sure it works on Shield Pro, but we currently have issue with formats supported.

I'm pretty sure I tested my code on Shield Pro 2019, so it should work on the supported formats. I recommend that you test with the samples on Dolby's website for starter https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/ I tested the implementation with one of those (sadly i don't remember which one it is, and i don't have hardware to test atm)

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-AVP/issues/383 and https://github.com/nova-video-player/aos-AVP/issues/405
Let's reopen #383 if need be.

**Comment by courville** [comment]
Let's do follow up using #383 to avoid duplicates. I close this issue.
