### ISSUE TITLE
Stopped displaying some TV shows in the "TV Shows" tab

### ISSUE THREAD

**Issue by arikoza** [nova-video-player/aos-AVP#505]
Stopped displaying some TV shows in the "TV Shows" tab. They are in "Recently Added" and "Obsolete Interface"
Version v6.0.28
![6fun83ui66w71](https://user-images.githubusercontent.com/93445603/139542733-4b1c6c93-2416-4616-9c55-f2836a3ddc86.jpg)

**Comment by courville** [comment]
Thanks for the feedback it seems to be a bug occurring in some specific language.
Can you please disclose the language you are using (locale) and also the full name of the video file that causes the issue?
I will try to reproduce and fix.

**Comment by arikoza** [comment]
>Thanks for the feedback it seems to be a bug occurring in some specific language.

No. Not because of the language, most likely. Empirically, it turned out that the error occurs when there is no background or genre in the file description in the TMDB database. Perhaps because of some other data, but mostly they are filled everywhere. Just in case, the language is Russian (RU)

**Comment by courville** [comment]
@arikoza very interesting remark. Could you still provide the exact name of the tv show that leads to this behavior so that I can reproduce?
Moreover can you please let me know if you are using the Google play release you are using (i.e. official one 5.x or the github one v6.x)?
Thanks

**Comment by arikoza** [comment]
TvShow name: Жена олигарха S01E01.avi
https://www.themoviedb.org/tv/136243

Video-armeabi-v7a-API_21+-release.apk  v6.0.28 and v6.0.34

**Comment by courville** [comment]
Thanks, now I have a file and can reproduce the issue (not related to language).
