### ISSUE TITLE
[Feature Request] Fine control of automatic refresh rate selection

### ISSUE THREAD

**Issue by Tyaap** [nova-video-player/aos-AVP#506]
I am using a Nvidia Shield 2019 Pro, LG CX and the latest Nova Player release.
With this setup the automatic refresh rate algorithm is selecting these refresh rates:
* 23.976fps --> 24Hz
* 25fps --> 50Hz
* 30fps --> 60Hz
* 59.94fps --> 60Hz

I would like to override these selections:
* 23.976fps --> 23.976Hz
* 25fps --> 25Hz
* 30fps --> 30Hz
* 59.94fps --> 59.94Hz

Perhaps it can be configured in a similar way to automatic refresh rate settings in MPC-BE ([screenshot](https://i.postimg.cc/G2QMbZLm/2-Fullscreen-Auto-Change.png)).

**Comment by courville** [comment]
Sorry for the late reply. I want to keep the refresh rate selection algorithm seamless without any complicated custom overriding (yes I know debatable design choice).
However, I reworked the refresh rate selection algorithm that will solve (I hope if your TV supports and advertizes these rates) for 23.976fps --> 23.976Hz and 59.94fps --> 59.94Hz cases.
Please try v6.0.33 pre-release and reopen if it does not behave as expected.

**Comment by Tyaap** [comment]
23.976fps --> 23.976Hz and 59.94fps --> 59.94Hz are working as expected. For the other cases, would it be possible to add a option to disable the use integral multiples of the frame rate? Or perhaps an option to prefer the lowest suitable refresh rate, instead of the highest? The main reason being that motion interpolation on the LG CX (and probably other TVs) does not work well with frame doubling.

**Comment by courville** [comment]
Interesting remark. The obvious fix would be to disable evil motion compensation mode on the tv. Maximizing the refresh rate is always best to grant a smooth UI on top of the video. I could always add a setting but I am not a big fan of "yet another cryptic setting for advanced users only" in general.
