### ISSUE TITLE
play video from Ftp problem

### ISSUE THREAD

**Issue by magusone** [nova-video-player/aos-AVP#508]
hello,
I'm useing FTP local server to play my media (hdd conected to router rt-ac86u) on my Bravia TV. I prefer FTP becouse I can load external subtitles (srt file) and it's faster then SMB. I can navigate to video file but Nova (v6.0.28) can't play it ("cannot play video" message).
Btw. is there possibility to do this in Kodi (Jarvis 16.1) useing Nova (v0.67)? I was trying to do this with adding Nova to playercorefactory.xml file and use Nova to play a video in Kodi, but nothing happend.

Thx for any help.

**Comment by rahaaatul** [comment]
> I'm using FTP local server to play my media (HDD connected to router RT-AC86U) on my Bravia TV. I can navigate to the video file but Nova (v6.0.28) can't play it ("cannot play video" message).

You can try enabling **Play with external media player** in Nova settings and it will play with other media players. See if it plays the media.

**Comment by courville** [comment]
Nova supports only specific ftp servers, please check https://home.courville.org/nova_video_player-faq/index.html
Please try to use sftp instead.

**Comment by petrutlucian94** [comment]
Thanks for the hint. Just a minor observation, the doc says: "Nova is only compatible with ftp(s) servers supporting "recent" 2007 MLST command ([RFC3659](https://tools.ietf.org/html/rfc3659)), e.g. with proftpd but NOT with vsftpd;".

For what is worth, sftp + vsftpd 3.0.3 did work in my case, despite MLST still being marked as a TODO: https://github.com/djarosz/vsftpd/blob/c2a07b8b86fa98ac51762f78c2862030544f02aa/REFS#L26-L29. I've switched to sftp as SMB keeps disconnecting, couldn't figure yet why (could be my Raspberry Pi 4 or Samba).
