### ISSUE TITLE
Sign in trakt not possible

### ISSUE THREAD

**Issue by asitkumar789** [nova-video-player/aos-AVP#509]
![Screenshot_20211111-084123](https://user-images.githubusercontent.com/40228837/141230951-b28d2aeb-8a11-4e7d-a862-6636edc36c92.jpg)

Why i get this error always?

**Comment by rahaaatul** [comment]
Try VPN, mine's working fine.

**Comment by courville** [comment]
Can you please check https://home.courville.org/nova_video_player-faq/index.html section regarding trakt and check that you are not using any blockers?

**Comment by courville** [comment]
Closing since it works for me and others.
