### ISSUE TITLE
Fetched Subtitles from online don't appear on subtitle settings.

### ISSUE THREAD

**Issue by rahaaatul** [nova-video-player/aos-AVP#512]
Here's a [demo](https://drive.google.com/file/d/13-bRDuv84E4cScBpOiV3Bti6gxlIugGs/view?usp=drivesdk) of the problem.

The external subtitles won't appear in Nova or any other player. Similar to issue [#504](https://github.com/nova-video-player/aos-AVP/issues/504).

**Comment by courville** [comment]
Thanks for the video. What I see is that when downloading the sub, the video is not yet indexed which can cause some side effects. Moreover you have selected possibility to use an external video player and you pick nova that is treated as external player and thus no sub is passed to "external nova player".
Can you please check if when disabling use external player it works?

**Comment by rahaaatul** [comment]
@courville [v6.0.33](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.33) fixed it. It's working fine now.
