### ISSUE TITLE
Nova does not fall back to SW decoding when encountering files an Exynos chip does not support HW decoding for

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#516]
I have a Samsung SM-T510 tablet running Android 11 that does not support 10-bit x265 at all because it has an Exynos chip that only hardware decodes 8-bit HEVC, and I have to turn off Nova's hardware decoding in the preferences page to get them to play with the software decoder which runs 10-bit files just fine. I would expect 10-bit x265 files to fall back to software decoding on Nova but they simply do not play and I have to manually disable the hardware decoder on the preferences page just to get them to play. This is a bit annoying since I have to keep re-enabling HW decoding on the preferences page for the majority of my files. 

Any clue as to why Nova doesn't fall back to software decoding on my tablet when encountering 10-bit x265 files it cannot HW decode?

**Comment by courville** [comment]
Nova has a swdecode fallback in case of hwdecode fails. No the question is why it does not kick in in your particular case.
Any logcat you could provide? @nnoury any idea?

**Comment by Pentaphon** [comment]
Here you go. 

[samlog.txt](https://github.com/nova-video-player/aos-AVP/files/7656347/samlog.txt)

**Comment by Pentaphon** [comment]
@courville get anything useful from my log?

**Comment by courville** [comment]
From the logs using the same command as in issue #515, it reveals no error reported from hwcodec on the platform. I suspect that this is why nova does not fallback to swdec. Note that since jellyfish videos have no sound (not common), nova might not react well too.

**Comment by Pentaphon** [comment]
> Note that since jellyfish videos have no sound (not common), nova might not react well too.

Anything else I can do to help? Any other specific video you would like me to test on this Samsung tablet?

**Comment by courville** [comment]
@Pentaphon could I get the two outputs from the following commands to figure out if there are multiple codecs declared on your samsung tablet?
```
adb shell cat /vendor/etc/media_codecs_*.xml
adb shell dumpsys media.player
```
Or alternatively the screenshot from https://play.google.com/store/apps/details?id=com.parseus.codecinfo

**Comment by Pentaphon** [comment]
I exported the codec list from the app you linked me. 

[Codec list.txt](https://github.com/nova-video-player/aos-AVP/files/7699006/Codec.list.txt)

**Comment by courville** [comment]
OK no duplicate codecs for hevc. Let's try on another file with sound (10b hevc). Could you get the logs from nova and another player using `adb logcat -v brief | grep -i -E "avos|mediacodec|omx|audio"` ? Let's see if there is any difference there.
I am really surprised that the samsung tablet cannot decode 10b hevc.

**Comment by Pentaphon** [comment]
Ok here's what I got for 4 players. I used the full video that I clipped https://gofile.io/d/eTxqEJ from in my other 10-bit thread.

1) A clean install of Nova 6.0.28 - No Playback
[novaclean.txt](https://github.com/nova-video-player/aos-AVP/files/7699521/novaclean.txt)

2) A clean install of MPV - No Playback
[mpv.txt](https://github.com/nova-video-player/aos-AVP/files/7699522/mpv.txt)

3) A clean install of VLC - Successful Playback
[vlc.txt](https://github.com/nova-video-player/aos-AVP/files/7699528/vlc.txt)

4) The Stock Samsung Video Player - No Playback (message saying: "Can't play video. Codec not supported" but the audio plays just fine. 
[samsungvideo.txt](https://github.com/nova-video-player/aos-AVP/files/7699561/samsungvideo.txt)

**Comment by courville** [comment]
Thanks for the logs, I notice that both for nova and mpv we get:
```
E/libexynosv4l2( 3705): failed to ioctl: VIDIOC_G_FMT (11 - Try again)
```
not for the other players.

**Comment by Pentaphon** [comment]
> I notice that both for nova and mpv we get:

Is this something that can be worked around by Nova and potentially fix problems with other devices or is my tablet stuck with not being able to fall back to SW decode when coming across these videos? I will notify the mpv-android dev about this issue as well.

**Comment by Pentaphon** [comment]
@courville good news, I showed this issue to the mpv dev and he submitted a patch upstream to ffmpeg.

Here's his comments and fix if you are interested: https://github.com/mpv-android/mpv-android/issues/468#issuecomment-992829282

**Comment by courville** [comment]
@Pentaphon excellent news! Thanks for pushing this. 
Ref: http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289545.html
Corresponding pre-release available here https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.33 (warning pre-release targeting API31 might create regressions).

**Comment by courville** [comment]
OK created own nova ffmpeg fork including https://github.com/nova-video-player/FFmpeg/commit/348f14911a2dcb4f619cf15ce6056d4ddf29b767 following https://patchwork.ffmpeg.org/project/ffmpeg/patch/DB9PR09MB521251A14DCD46826854BCC6EC749@DB9PR09MB5212.eurprd09.prod.outlook.com/ and http://ffmpeg.org/pipermail/ffmpeg-devel/2021-December/289545.html

**Comment by Pentaphon** [comment]
> OK created own nova ffmpeg fork including

I'm afraid that 6.0.36 did not solve the issue. The same behavior happens. There is no HEVC playback when hardware decoding is enabled on this device.
