### ISSUE TITLE
[Bug]: Trakt won't sync correctly or won't sync at all

### ISSUE THREAD

**Issue by rahaaatul** [nova-video-player/aos-AVP#519]
### Problem description

Nova won't sync video watched/completed with `Trakt` . Although in the app, it's marked watched.

Also manually marking (watched/not watched) not working either.

It's marking the incorrect video as watched.
_i.e., I watched Boruto, it synced Sunset Beach. And other videos are unsynced._

### Steps to reproduce the issue

_Watch a video, wait for it to be completed and synced with_ `trakt`.

### Expected behavior

Should sync with `Trakt` with correct information.

### Your phone/tablet/androidTV model

SMART TV

### Operating system version

Android 5.1

### Application version and app store

6.0.33

**Comment by courville** [comment]
Forgot to propagate tmdb id instead of tvdb id in trakt sync for tv shows in the migration to tmdb from tvdb.
Will be corrected soon.

**Comment by courville** [comment]
Please check v6.0.34 if it fixes all your trakt issues.

**Comment by rahaaatul** [comment]
It's working correctly now, thank you for the quick fix @courville .

**Comment by mschumacher69** [comment]
Is 6.x available in beta or do I need to sideload it manually?

**Comment by rahaaatul** [comment]
> Is 6.x available in beta or do I need to sideload it manually?

Check release and download the pre-release.

**Comment by rahaaatul** [comment]
> Is 6.x available in beta or do I need to sideload it manually?

Download and Install the [`Pre-Release`](https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.36) from GitHub.

**Comment by mschumacher69** [comment]
Thanks, I'd rather not because Nova is my main media center and I can't afford bugs.

Any ETA on official release?
