### ISSUE TITLE
[Bug]: Volume indicator

### ISSUE THREAD

**Issue by arikoza** [nova-video-player/aos-AVP#523]
### Problem description

When changing the volume, the bar is completely transparent and there is no indication at what level the volume is now. I would also like to be able to disable the built-in indicator and use the system
![photo_2021-12-24_17-29-31](https://user-images.githubusercontent.com/93445603/147359497-830741e0-ed69-4dbe-914b-457a4f535d8b.jpg)

### Steps to reproduce the issue

increase or decrease the volume

### Your phone/tablet/androidTV model

TV Box Tox1

### Operating system version

Android 9

### Application version and app store

v6.0.36

**Comment by arikoza** [comment]
Problem only 320 dpi

**Comment by courville** [comment]
Let's merge this issue with https://github.com/nova-video-player/aos-AVP/issues/493 and treat it as duplicate.
Closing.
