### ISSUE TITLE
[Bug]: "Filecorelibrary" NDK build failure

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#524]
### Problem description

I tried building on Linux it gives this error "Filecorelibrary" NDK build , I also tried on windows using Docker gives me the same error , I appreciate if you could help me out here.

### Steps to reproduce the issue

Building nova using linux or windows

### Expected behavior

successful build

### Your phone/tablet/androidTV model

LG V50 Thinq

### Operating system version

Android 10

**Comment by courville** [comment]
Sure I will gladly help.
Can you please give me the full error message i.e. the output of `make &> build.log` or alternatively the output of `./gradlew aND` in Video directory?
The easiest to build nova is under Android studio, I guess: there you can also paste the build error in build console.

**Comment by courville** [comment]
Ah forgot you need to get branch v6 of nova now:
```
mkdir aos; cd aos
repo init -u https://github.com/nova-video-player/aos-AVP -b nova
repo sync -j4
repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
cd Video
./gradlew aND
```

**Comment by bronnel** [comment]
@courville , Thanks, I appreciate it. I'm really having a hard time trying to build , can you be so kind and show me a proper guide on how to build using windows ? I really prefer windows if possible, if not possible on windows then I will go ahead and use Linux instead.

**Comment by courville** [comment]
@bronnel I never used windows to build nova and I am pretty sure it is not supported.
Best is to use linux and install android studio and use the commands I provided in the previous post.
I will fix the docker soon but on a plain linux it should work out of the box.
If it does not please ping me.

**Comment by bronnel** [comment]
@courville this is what I get when I run new cmd
```
repo init -u https://github.com/nova-video-player/aos-AVP -b v6
Downloading manifest from https://github.com/nova-video-player/aos-AVP
fatal: Couldn't find remote ref refs/heads/v6
manifests: sleeping 4.0 seconds before retrying
fatal: Couldn't find remote ref refs/heads/v6
fatal: cannot obtain manifest https://github.com/nova-video-player/aos-AVP

```

**Comment by courville** [comment]
OK my bad, please use: `repo init -u https://github.com/nova-video-player/aos-AVP -b nova`
Can you please let me know the config you are using: do you confirm it is android studio on linux distro?
It will require java11 but you can use the one of Android studio (global preference->build-tools->gradle select java11 in gradle JDK.

**Comment by bronnel** [comment]
@courville thanks for the help, but now I get this error
```
> Task :FileCoreLibrary:ndkBuild FAILED
android_ndk is 
/bin/sh: 1: /ndk-build: not found
make: *** [native_build_native/libnativehelper] Error 127
AVP/core.mk:183: recipe for target 'native_build_native/libnativehelper' failed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':FileCoreLibrary:ndkBuild'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
1 actionable task: 1 executed
```

**Comment by courville** [comment]
Given the logs provided it means that it does not find android_ndk.
Please install under android studio the ndk in the tools->sdk manager->sdk tools->NDK and CMake.
If it works the following line should point to ndk:
```
android_ndk is 
```
and it should not complain about `/ndk-build: not found`

**Comment by bronnel** [comment]
@courville I did that it still says `ndk-build: not found` 

I also did this but does not make any difference
`export PATH=$PATH:/home/matrix/Android/Sdk/ndk/23.1.7779620`

I feel like I am the only one with this issue.

**Comment by courville** [comment]
@bronnel I am sure you are not the only one. Let me redo a clean build from a clean docker like `docker run -it --name nova debian:bullseye bash` (i.e. using bullseye debian):
```
apt update && apt upgrade --yes --assume-yes
apt install -y sudo curl wget unzip nasm ninja-build maven build-essential python3 python3-pip python3-setuptools python3-wheel git default-jdk
update-alternatives --install /usr/bin/python python /usr/bin/python3 1
curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo > /dev/null
sudo chmod a+rx /usr/local/bin/repo
cd /opt
ANDROID_SDK_TOOLS=7583922
OS=linux
wget --quiet --output-document=/opt/android-cmdline.zip https://dl.google.com/android/repository/commandlinetools-${OS}-${ANDROID_SDK_TOOLS}_latest.zip
unzip -q /opt/android-cmdline.zip -d /opt
mkdir -p /opt/android-sdk/cmdline-tools
mv cmdline-tools android-sdk/cmdline-tools/tools
export ANDROID_SDK_ROOT=/opt/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
ndk=$(pkg="ndk;21"; sdkmanager --list | grep ${pkg} | sed "s/^.*\($pkg\.[0-9\.]*\) .*$/\1/g" | tail -n 1)
yes | sdkmanager "${ndk}" > /dev/null
cd $HOME
mkdir nova
cd nova  
repo init -u https://github.com/nova-video-player/aos-AVP -b nova
repo sync -j 4
repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
cd Video
./gradlew aND
```
You need to have in your path the proper `ANDROID_SDK_ROOT`

**EDIT:**  now it compiles with ndk 21 (fails with ndk 23).
**EDIT 2:** need to install default-jdk to get to complete build

**Comment by courville** [comment]
@bronnel now it builds on my side with the docker. I hope it will be the same on your side.

**Comment by bronnel** [comment]
@courville I tried docker here is what I get

```
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/athread.o] Error 1
make[3]: Entering directory '/nova/native/avos'
[armeabi-v7a] Compile arm    : avos <= athread.c
make[3]: Leaving directory '/nova/native/avos'
make[3]: Entering directory '/nova/native/avos'
[armeabi-v7a] Compile arm    : avos <= bits.c
make[3]: Leaving directory '/nova/native/avos'
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/bits.o] Error 1
make[3]: Entering directory '/nova/native/avos'
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/util.o] Error 1
[armeabi-v7a] Compile arm    : avos <= util.c
make[3]: Leaving directory '/nova/native/avos'
/usr/bin/as: unrecognized option '-EL'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/debug.o] Error 1
make[3]: Entering directory '/nova/native/avos'
[armeabi-v7a] Compile arm    : avos <= debug.c
make[3]: Leaving directory '/nova/native/avos'
make[3]: Entering directory '/nova/native/avos'
[armeabi-v7a] Compile arm    : avos <= i18n.c
/usr/bin/as: unrecognized option '-EL'
make[3]: Leaving directory '/nova/native/avos'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/i18n.o] Error 1
make[2]: *** [AVP/core.mk:184: native_build_native/avos] Error 2
make[2]: Leaving directory '/nova'
make[1]: *** [AVP/core.mk:277: native_avos_full] Error 2
make[1]: Leaving directory '/nova'

> Task :MediaLib:ndkBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MediaLib:ndkBuild'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 54s
2 actionable tasks: 2 executed
make: *** [AVP/core.mk:176: all] Error 1
root@137638330bca:/nova# 

```
**Edit:**
I created `local.properties` file inside Video with these lines still no luck
```
sdk.dir = /home/matrix/Android/Sdk
ndk.dir = /home/matrix/Android/Sdk/ndk/21.3.6528147
```
default-jdk also installed still no luck , I followed the steps you mentioned and there is no difference.

**Comment by courville** [comment]
@bronnel your error seems to come from the fact that you have now the two ndk and it still picks the 23 one.
Please do `sdkmanager --uninstall "ndk;23.1.7779620"` or any 23.x number listed as `sdkmanager --list_installed`

**Comment by bronnel** [comment]
@courville I did that , I removed everything and started from zero , I let docker take care of everything and ended up with same error, I'm out of luck , I don't know what to do , I tried everything

**Comment by courville** [comment]
Clearly the error is that you are using ndk 23 
```
make[3]: *** [/opt/android-sdk/ndk/23.1.7779620/build/core/build-binary.mk:476: obj/local/armeabi-v7a/objs/avos/Source/athread.o] Error 1
```
Perhaps you are reusing the same docker image.
I have updated the docker file in `AVP/docker`: please take the latest https://github.com/nova-video-player/aos-AVP/blob/nova/docker/Dockerfile
In order to start from scratch please check that you have removed the previous docker containers and images:
```
docker container ls --all
docker container stop CONTAINERID
docker container rm CONTAINERID
docker image ls
docker image rm IMAGEID
```
and restart from scratch.
There is no reason why it should not work now.

**Comment by bronnel** [comment]
Finally built successfully , first I removed all previous docker images with those lines you provided, there were images dating back to 5 months ago, I removed everything including jdk-11 , and used your updated docker file , containing ndk-21 , now everything works perfect , thank you , I appreciate your help @courville and happy new year . Now I have a feeling the new docker file is going to work on windows as well and I'm going to give it a try tomorrow.

**Comment by courville** [comment]
\o/ we made it! Dockerfile should work under windows for sure (since it will run a linux docker). What is not supported on windows is the native build.

**Comment by bronnel** [comment]
@courville , I have a strange issue , after successful build I cannot find nova folder in home directory

**Comment by courville** [comment]
In the docker, the nova folder is located at the root `/nova` and apk built are located `/nova/Video/build/outputs/apk/noamazon/debug` if you built with `./gradlew aND`
Note that the folders are not exposed outside the docker: I will add a parameter to do so later.

**Comment by courville** [comment]
In order to exchange data between host and docker, I added some instructions on the docker page i.e.:
```
docker build -t nova .
mkdir shared
docker run --rm -ti -v $PWD/shared:/shared --entrypoint=/bin/bash nova
cd Video
./gradlew aND
cp /nova/Video/build/outputs/apk/noamazon/debug/*apk /shared
```

**Comment by bronnel** [comment]
> In the docker, the nova folder is located at the root `/nova` and apk built are located `/nova/Video/build/outputs/apk/noamazon/debug` if you built with `./gradlew aND` Note that the folders are not exposed outside the docker: I will add a parameter to do so later.

 @courville  I am not after the built apk, I need the project files , I mean Video, MediaLib , Filecorelibrary folders is what I need access to

BTW successfully built on windows 10 using WSL I can access the folders but cannot import to Android studio, is there a way to do that?
![qqqq](https://user-images.githubusercontent.com/15629916/147935490-f1836eef-9329-4966-8bfa-c51c679dd7a3.jpg)

**Comment by courville** [comment]
Perhaps what you want is not a docker build but to do under windows (not docker) a checkout of the full project using repo and then start a different docker that would perform the build based on the exported host directory. This would allow you to access the files.
Otherwise a simple `docker cp <container id>:/nova ./nova` will do to copy files from docker to host.

**Comment by bronnel** [comment]
@courville Thanks so much, that's what needed to know, I appreciate it.

**Comment by courville** [comment]
What you could do in your case is to use the following `Dockerfile`:
```
FROM debian:bullseye
MAINTAINER Courville Software <software@courville.org>

ENV DEBIAN_FRONTEND noninteractive
ENV USER root

# install build tools
RUN echo "Install Linux build environment"
RUN apt update && apt upgrade --yes --assume-yes
RUN apt install -y nasm ninja-build maven build-essential \
        git wget curl unzip sudo pkg-config \
        python3 python3-pip python3-setuptools python3-wheel \
        openjdk-11-jdk \
        tig vim-tiny less screen

# install openjdk-8-jdk
RUN apt install -y apt-transport-https ca-certificates wget dirmngr gnupg software-properties-common
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key --keyring /etc/apt/trusted.gpg.d/adoptopenjdk-apt-key.gpg add
RUN add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
RUN apt update && apt install -y adoptopenjdk-8-hotspot

# use python3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN apt clean autoclean
RUN pip3 install meson==0.53.2

# download and install repo
RUN curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo > /dev/null
RUN chmod a+x /usr/local/bin/repo

# set proper env variables
ENV ANDROID_SDK_TOOLS=7583922 \
    OS=linux \
    SDK_URL="https://dl.google.com/android/repository"

ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/tools/bin"

ENV NDKVER=21
ENV BUILDTOOLSVER=31

ENV PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin"

# download minimal Android SDK/NDK

RUN echo "Install minimal Android SDK" && \
    wget --quiet --output-document=/opt/android-cmdline.zip ${SDK_URL}/commandlinetools-${OS}-${ANDROID_SDK_TOOLS}_latest.zip && \
    unzip -q /opt/android-cmdline.zip -d /opt && \
    mkdir -p /opt/android-sdk/cmdline-tools && \
    mv /opt/cmdline-tools /opt/android-sdk/cmdline-tools/tools

RUN echo "Install Android NDK" && \
    ndk=$(pkg="ndk;$NDKVER"; sdkmanager --list | grep ${pkg} | sed "s/^.*\($pkg\.[0-9\.]*\) .*$/\1/g" | tail -n 1) && \
    yes | sdkmanager "${ndk}" > /dev/null

WORKDIR /nova

#ENTRYPOINT ["make"]

USER root
```
And prior to building on your windows host using WSL retrieve the full source of nova using (so that you have the files directly on your windows host):
```
mkdir nova
repo init -u https://github.com/nova-video-player/aos-AVP -b nova
repo sync -j4
repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
cd ..
```
Then on the host build/launch the docker and the build that should use the host filesystem (build should be launched in the directory containing the `Dockerfile` and the `nova` folder containing the overall repos):
```
docker build -t nova .
docker run --rm -ti -v $PWD/nova:/nova --entrypoint=/bin/bash nova
cd /nova/Video
./gradlew aND
```

**Comment by courville** [comment]
Let's declare this issue closed for now.

**Comment by bronnel** [comment]
@courville , I have a strange issue , in Ubuntu building from terminal works fine  (without using docker) but I have to enter `export ANDROID_SDK_ROOT=/home/matrix/Android/Sdk ` every time, also inside Android studio's own terminal building works fine but again I have to enter `export ANDROID_SDK_ROOT=/home/matrix/Android/Sdk `
But when I press the make button (the green button ) inside android studio I get this error
![Screenshot from 2022-01-14 14-42-32](https://user-images.githubusercontent.com/15629916/149510334-be037262-70f0-4965-beca-ee339ea3cbb4.png)
![Screenshot from 2022-01-14 14-42-58](https://user-images.githubusercontent.com/15629916/149510342-b8ae6b80-7d6c-45a2-beb3-f27eb987cd5d.png)

can you help me with this issue kindly

here is how project is set up
![Screenshot from 2022-01-14 14-54-08](https://user-images.githubusercontent.com/15629916/149511742-9a86887b-921e-4583-9e42-0508f909f884.png)
![Screenshot from 2022-01-14 14-54-25](https://user-images.githubusercontent.com/15629916/149511746-8587245e-e07f-40ed-bb43-0e0b9575fb44.png)
![Screenshot from 2022-01-14 14-54-31](https://user-images.githubusercontent.com/15629916/149511749-f56dd081-75e0-4998-b713-d400172c1aff.png)
![Screenshot from 2022-01-14 14-54-45](https://user-images.githubusercontent.com/15629916/149511754-127063e0-2fb8-4697-beeb-f7cebaa834f7.png)

**Comment by courville** [comment]
Android studio does not find the NDK.
You need to define before launching Android studio in your shell default configuration file (`$HOME/.zshenv` `$HOME/.bashrc` or whatever shell config file relevant for your config):
```
export ANDROID_SDK_ROOT=/home/matrix/Android/Sdk
export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin"
```
If you are able to build afterwards in the console without specifying the `ANDROID_SDK_ROOT`, it should work too on Android studio that will inherit this variable.

**Comment by bronnel** [comment]
@courville I did the export before launching android studio but ended with same error.
this is the content of `.bashrc` file in my home folder

Note : I did clean install of Ubuntu 20.04 LTS on my HDD from scratch , I started clean , but I have been dealing with this issue for the past three days, when it says `/bin/sh: /ndk-build: No such file or directory`  I don't know why it looks in `/bin/sh` for `ndk-build` since ubuntu uses bash or dash instead of sh shell, this is a shell issue which I don't know how to fix , everything is Ubuntu default I haven't done any modification since the installation.

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
```

**Comment by courville** [comment]
Just add the two lines I provided at the end of the file and check in the console that indeed bash is your shell using `echo $SHELL`

**Comment by bronnel** [comment]
@courville after adding the lines to `.bashrc` the build from console inside android studio does not need specifying `ANDROID_SDK_ROOT`  and it is SUCCESSFUL , but it still fails with the make button with same ndkbuild not found error.
and the output of `echo $SHELL` is:
`/bin/bash
`

**Comment by bronnel** [comment]
@courville , I removed Ubuntu , installed Linux mint , did everything from start to finish , in the built-in console of Android studio everything builds fine but the make button is not working, believe me this issue exists because I spent the last week troubleshooting this issue ,

I followed these steps one by one and it compiles fine but Android Studio can not detect ndk so make button not working and throws ndk-build not found error, I did everything that I can think of 

> @bronnel I am sure you are not the only one. Let me redo a clean build from a clean docker like `docker run -it --name nova debian:bullseye bash` (i.e. using bullseye debian):
> 
> ```
> apt update && apt upgrade --yes --assume-yes
> apt install -y sudo curl wget unzip nasm ninja-build maven build-essential python3 python3-pip python3-setuptools python3-wheel git default-jdk
> update-alternatives --install /usr/bin/python python /usr/bin/python3 1
> curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /usr/local/bin/repo > /dev/null
> sudo chmod a+rx /usr/local/bin/repo
> cd /opt
> ANDROID_SDK_TOOLS=7583922
> OS=linux
> wget --quiet --output-document=/opt/android-cmdline.zip https://dl.google.com/android/repository/commandlinetools-${OS}-${ANDROID_SDK_TOOLS}_latest.zip
> unzip -q /opt/android-cmdline.zip -d /opt
> mkdir -p /opt/android-sdk/cmdline-tools
> mv cmdline-tools android-sdk/cmdline-tools/tools
> export ANDROID_SDK_ROOT=/opt/android-sdk
> export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
> ndk=$(pkg="ndk;21"; sdkmanager --list | grep ${pkg} | sed "s/^.*\($pkg\.[0-9\.]*\) .*$/\1/g" | tail -n 1)
> yes | sdkmanager "${ndk}" > /dev/null
> cd $HOME
> mkdir nova
> cd nova  
> repo init -u https://github.com/nova-video-player/aos-AVP -b nova
> repo sync -j 4
> repo forall -c 'git checkout -t $REPO_REMOTE/$REPO_RREV'
> cd Video
> ./gradlew aND
> ```
> 
> You need to have in your path the proper `ANDROID_SDK_ROOT`
> 
> **EDIT:** now it compiles with ndk 21 (fails with ndk 23). **EDIT 2:** need to install default-jdk to get to complete build

**Comment by bronnel** [comment]
@courville , this is the exact issue here
```

> Task :MediaLib:ndkBuild FAILED
android_ndk is 
/bin/sh: 1: /ndk-build: not found
make: *** [AVP/core.mk:184: native_build_native/libyuv] Error 127

Execution failed for task ':MediaLib:ndkBuild'.
> Process 'command 'make'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

**Comment by courville** [comment]
@bronnel for some reason it is back to the state that it does not find the ndk.
You need to have set a proper `export ANDROID_SDK_ROOT=/opt/android-sdk` and I guess that it is not the path you use in reality (it was `export ANDROID_SDK_ROOT=/home/matrix/Android/Sdk` before in your case).

EDIT: please check that in your `.bashrc` or `.zshrc` or `.profile` you have the right PATH defined i.e.
```
export ANDROID_SDK_ROOT=/opt/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/cmdline-tools/tools/bin
```

**Comment by bronnel** [comment]
@courville , Thanks , I did exactly what you stated, but again it cannot find the ndk, I tried everything under root privilege and still ended up with the same error, I even launched android studio as root and still nothing. I also looked under opt folder to see if the files are actually there and they were definitely there, I'm sure that you are using some different kind of setup which I cannot put my finger on it, However there is only one thing left to do which is kali linux because it uses root by default , maybe that will make a difference , thank you again.

**Comment by courville** [comment]
The solution is not in using another Linux distribution, I would advise to stick with ubuntu since it is the default one used in containers to build apps and recommended by Google. Running as root is also not the right solution. I will redo the steps to find out what is missing later.

**Comment by courville** [comment]
@bronnel couple of tests do be conducted:

- do you confirm that building from a terminal works in your setup?
- could you try to launch android studio directly from command line in a terminal (it would inherit the shell variables this way) and see if you can build (i.e. launching the following command `/opt/android-studio/bin/studio.sh` with the current path)?

**Comment by bronnel** [comment]
@courville  it worked, launching android studio from the terminal finds the skd and ndk nicely
and yes building works in terminal to answer your question.
But does it mean that I have to launch it from terminal every time?
thank you, I appreciate it.

**Comment by bronnel** [comment]
@courville , I tried to launch nova from from windows which I built in Ubuntu , I get this error

```
Execution failed for task ':MediaLib:ndkBuild'.
> A problem occurred starting process 'command 'make''
```

`CreateProcess error=2, The system cannot find the file specified`

I'm very close to do this, I can feel it, for some reason AS does not detect the **ndk** on Windows, this is the only roadblock , can you help

**Comment by courville** [comment]
I never tried to build nova on windows and I guess this will not be that straightforward.
Note that I only have a dusty windows PC somewhere that I only power up if I have no other solution. 
I will not be the one able to help you I am afraid. Sorry.

**Comment by bronnel** [comment]
@courville , I have tried hundreds of solutions across stackoverflow and github google, you name it , all similar cases , non worked so far, the only problem is that android studio does not detect the ndk, thanks, no worries :)
