### ISSUE TITLE
issue with local network and vpn

### ISSUE THREAD

**Issue by pouryapb** [nova-video-player/aos-AVP#527]
### Problem description

Some of the API used in this project is blocked in my country, like TMDB. I can use vpn, no problem but when I use vpn I can't use smb anymore. if the app could use local network for a local smb then I could use the app normally.

### Steps to reproduce the issue

connect to vpn and try using SMB on a local network

### Expected behavior

being able to use smb

### Your phone/tablet/androidTV model

xz premium android 9/ android tv v9

### Operating system version

android 9

### Application version and app store

5.15.26-20210915.1928 from Google play store

**Comment by courville** [comment]
It should be fixed on pre-release 6.xx available on github https://github.com/nova-video-player/aos-AVP/releases.

**Comment by pouryapb** [comment]
Yes, it is fixed in this version. Thank you
