### ISSUE TITLE
[Bug]: Special Characters on movies

### ISSUE THREAD

**Issue by Akeshis** [nova-video-player/aos-AVP#537]
### Problem description

Movies starting with special characters are placed at the end of the list in the media library.
Example: the movie "It" (ça in french)

### Steps to reproduce the issue

Add new movies starting with special character

### Your phone/tablet/androidTV model

Nvidia Shield Pro 2019

### Operating system version

Android

### Application version and app store

6.0.33

**Comment by courville** [comment]
OK, in the sql sort I do apparently it does not sort well the special characters. I need to figure out how to do this efficiently.
@s-stark any idea?

**Comment by courville** [comment]
OK RTFM cf. https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase sqlite has LOCALIZED and UNICODE collations.
