### ISSUE TITLE
MXPlayer has smoother 4k video playback than Nova 

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#54]
I read that for Sony TV to go 4K you have to set the app type as VIDEO:

https://community.sony.co.uk/t5/android-tv/sony-4k-bravia-tv-reports-1080p-resolution-to-apps/td-p/2251639

"Apps compiled as "Application (Video)" have access to hardware 4K video decoding, that is why Youtube, Netflix, etc, play video at 4K. Apps compiled as "Application" have limited access to 1080p video rendering only.
You can see how an app is compiled pressing "action menu" button, chosing "image" and reading if it says "Application" or "Application (video)" on top.
"
If you need beta testing on Sony TV I can do it for you.
4K playback at the moment is almost unusable except on low bitrate files - if it plays it stutters or lags.

**Comment by courville** [comment]
Sorry but I do not quite understand the issue. For me there is the UI and video plane.
Android uses 1080p for UI but does not limit video plane to 1080p and can play 2160p content.
Regarding 4k playback perf, can you please disable passthrough (it could have a bad impact on stuttering since audio drives video playback) and let me know if you are really limited to 1080p?

**Comment by JJD2K** [comment]
Hello
No I am not limited to 1080p - I do not say that.

What they claim in the info that I sent above is - "Apps compiled as "Application (Video)" have access to hardware 4K video decoding"

I am not saying it is a fact - maybe not true - I am trying to help as 4k is going to be the future and it is not working very good in NOVA or ARCHOS.
Very occasional stutter/judder.
Btw judder is sometimes present on 1080p files too - I think it has something to do with mismatching video frame rate and TV refresh rate - I tried also the option to switch refresh rate in NOVA settings - makes no difference.

I am not using audio passthorugh as it is not working in both modes. Mode 2 is worse.
I think only 1 file played ok in mode 1 so I stopped messing around with passthrough.

Thank you very much for your replies.

**Comment by courville** [comment]
For judder, do enable adaptive frame rate in settings.

**Comment by JJD2K** [comment]
It does not make any difference on Sony TV both for NOVA and ARCHOS

Check the latest version of MXPlayer - it plays 4K PERFECTLY smooth - better than any other player - I do not know what decoder they use. The only issue they have is that they do not have buffer too and video stops for few second to load and then continues to play very smooth, but no judder and no frame skipping.

Maybe you can add an option to display an overlay with debug info like in KODI so that we can send you screenshots and details.
Like dropped frames, buffer, codec info, media frame rate, tv frame rate etc.
Would be very nice.

**Comment by courville** [comment]
OK I checked that I can play 4k video (video plane) without any change of app type on sony TV (43EX8096).
I have smooth playback when disabling passthrough when doing local playback from hdd on TV.
All players are using hardware codecs from TV for playback.

**Comment by courville** [comment]
Jellyfish video playback is indeed not as good as for mxplayer. For this specific video it is likely to be linked to the fact that there is no sound track and it has been in the past an issue with the Archos video player that we have inherited.
Let's take another video for benchmarking purposes.

**Comment by JJD2K** [comment]
https://4kmedia.org/life-untouched-hdr-uhd-4k-demo/
Here you are.
Unplayable in Nova - very choppy
Some stutter in KODI
Smooth like butter in MX Player
Smooth in XPMC

**Comment by JJD2K** [comment]
https://4kmedia.org/samsung-x-redbull-see-the-unexpected-hdr-uhd-4k-demo/
Very choppy in Nova
Stutter i MX , but much better
Stutter in XPMC worse than NOVA
Feeze in KODI

**Comment by JJD2K** [comment]
Let me just note that I am not saying NOVA is bad - I am saying it can be BEST if you focus on playback as the UI is already PERFECT - CLEAN and useful - much better than all other tools.

**Comment by courville** [comment]
No problem with your remarks.
I just want to pin point where the issue or improvement point really is.
We are converging.

**Comment by courville** [comment]
My current understanding is that UI plane is 1080p on AndroidTV and video plane and playback can sustain 4k without any modification to Nova.
4k playback performance issue needs to be treated in another thread or let's rename this one.

**Comment by courville** [comment]
Please have a look at buffer discussion there that might be related https://github.com/nova-video-player/aos-AVP/issues/53

**Comment by JJD2K** [comment]
I believe this is a combination of DECODING and buffering - both should be addressed.
I guess most of these players use external code for decoding - can you check what MX Players uses and reuse?
Its latest version really plays better than anything else.

**Comment by JJD2K** [comment]
New beta is much better - I will test more and let you know.
Actually it is better only on some files. The samples above play worse than before.

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-avos/commit/0f265912723c672b37848696363b4dfa9eeca415 and https://github.com/nova-video-player/aos-avos/commit/c12725a8e3105c8d6069af6e6041dad3117f9c9e

**Comment by courville** [comment]
Please try https://github.com/nova-video-player/aos-AVP/releases/tag/v4.12 and report if there is any improvement.

**Comment by JJD2K** [comment]
Hello
Thank you for looking at these issues. Unfortunately the performance is not improved. Files that play smooth in MXPlayer stutter, pause or completely stop in NOVA. If you have any tweaked versions for test let me know.

**Comment by courville** [comment]
Closing the issue based on latest modifications https://github.com/nova-video-player/aos-avos/commit/0f265912723c672b37848696363b4dfa9eeca415 and https://github.com/nova-video-player/aos-avos/commit/c12725a8e3105c8d6069af6e6041dad3117f9c9e that should help with HEVC playback on MTK based devices.
These modifications are available on latest beta on Google Play.
I propose to open a specific new issue to track any problem that are appearing starting v4.14.

**Comment by JJD2K** [comment]
This has to do with AUDIO as I mentioned in the past.
With latest version from store on file that stutters if I switch to PASSTHROUGH mode 2 it plays almost perfect, unfortunately there is no sound.

**Comment by JJD2K** [comment]
Why closed?

**Comment by JJD2K** [comment]
I tested with the latest version from store - indeed it plays smoother and it plays mkv that was not supported in the past. Due to my test above (the one with audio passthrough mode 2) I am almost sure the issue is related to audio. Either there is a bottleneck there or it is not hardware decoded thus overloading the cpu which causes the video stutter.

**Comment by courville** [comment]
Audio cannot overload the CPU. This could be a buffer starvation issue
though.

**Comment by JJD2K** [comment]
I hope you can take a deeper look as mode 2 makes a big difference so it really has to do something with the audio. Also in a file with multiple audio channels, switching to a simpler channel like stereo improves the performance.

**Comment by courville** [comment]
I consider issue closed related to more recent issue.
