### ISSUE TITLE
[FEAT]: Option to toggle play/pause in case a bluetooth headset was disconnected

### ISSUE THREAD

**Issue by alexanderadam** [nova-video-player/aos-AVP#550]
### Description

Maybe the [AntennaPod implementation](https://github.com/AntennaPod/AntennaPod/blob/2524fa0f7605ded2139f3ec6d4337383e6f3006d/core/src/main/java/de/danoeh/antennapod/core/service/playback/PlaybackService.java#L185) helps achieving this.
There's also this [Android developer documentation](https://developer.android.com/reference/android/content/Intent#ACTION_HEADSET_PLUG).

**Comment by courville** [comment]
Good idea, could add as well the `ACTION_MEDIA_BUTTON` in the `BroadcastReceiver` to be complete and link it to `PlayerService`.
