### ISSUE TITLE
[壮举]：希望增加挂载webdav的选项

### ISSUE THREAD

**Issue by cfrock** [nova-video-player/aos-AVP#558]
### Description

之前在ios上一直使用infuse，换了安卓手机之后一直希望有个app可以比infuse有更好的观影体验。使用nova后像发现了新的大陆。但是我习惯于远程观看家中nas里的影片，webdav是经常会用到的，但是nova现在还不支持～强烈希望支持挂在webdav，不但解决了手机观看影片的问题，我的电视也可以摆脱kodi那种非人的操作逻辑了

**Comment by courville** [comment]
Translation:

> I have been using infuse on ios before, and after switching to an android phone, I always hope that there is an app that can have a better viewing experience than infuse. After using nova like discovered a new continent. But I am accustomed to watching videos in my NAS remotely. Webdav is often used, but nova does not support it yet~ I strongly hope to support it on webdav, which not only solves the problem of watching videos on mobile phones, but also can get rid of kodi on my TV. That kind of inhuman logic

On NAS I recommend to use SMB shares or sftp. Webdav is not yet supported cf. #368
I will close the issue since it is a dupplicate of #368
I.e. using Google translate:
在 NAS 上，我建议使用 SMB 共享或 sftp。 Webdav 尚不支持 cf。第368章
我将关闭该问题，因为它与 #368 重复
