### ISSUE TITLE
[FEAT]: Make animation row optional

### ISSUE THREAD

**Issue by Cowboy1968** [nova-video-player/aos-AVP#560]
### Description

Make the Animation row optional

### Additional information

I am OCD and do not like my animated Movies and animated TV shows showing up on their own line in the Animated section.  I prefer to have my Animated Movies in the Movie section and the TV ones in the TV Section.  I realize some people may like this feature which is why I would like to ask it be made optional.

**Comment by courville** [comment]
I understand your point and request but for now I am not in favor of making this option because it means modifying all the loaders (queries to database) based on this options and makes testing of nova very tedious.

**Comment by mjnewton** [comment]
Really disappointed to read this @courville - I have just updated to v6.0.61 and wondered where most of my movies had gone... didn't spot them sitting in a separate Animations row!

For me I too have a strong preference for putting all my movies (whether animated or not, it's not really a distinction I make) in the one place, but for my young kids the separation is proving quite a challenge for them as I haven't been able to explain to them the difference!

Noting what you've said about the knock-on difficulties merging the two categories as things used to be, if you can envisage any way of doing so then I (and my kids!) would be ever so grateful. If there's any way of helping minimise the tedium (donations, helping out etc) please do say.

**Comment by mjnewton** [comment]
As a rather crude (but effective) workaround I have run the following command which removes the 'Animation' genre reference in any of my .nfo files:

`find ~/Films -type f -name "*.nfo" -print0 |xargs -0 sed -i '/<genre>Animation<\/genre>/d'`

If I then execute 'Rescrape all' in Nova > Settings (ensuring 'Process .nfo files' is enabled) it runs through all my films and puts them all (whether animated or non-animated) in the same single Movies category (thus leaving the Animations category empty). I'll need to repeat this every time I add a new animated film but it only takes a few moments. It could of course also be done manually film-by-film but I had a couple of hundred to sort out!

This works perfectly for me but I haven't tested it for @Cowboy1968's situation of working with animated TV Shows as I don't have any and so don't know if they're the same.

**Comment by courville** [comment]
A side note on @mjnewton `find` command, after migrating from v5 to v6 all NFO needs to be regenerated due to the change of media retrieval source for tv shows (tvdb -> tmdb) and addition of new field to track movie collections. It means removing all the NFO files first, rescrape all, then export all again (or just reinstall the app which is easier with no NFO file present).

**Comment by courville** [comment]
@mjnewton, I agree this is of course feasible just tedious.
Are you ready to contribute code? Merge requests or donations are always welcome and motivating.

**Comment by mjnewton** [comment]
> Are you ready to contribute code?

Unfortunately it's not so much being ready but rather being unable!

> Merge requests or donations are always welcome and motivating.

I've got no excuses on the donations front so I've just made one (via GitHub sponsorships but them only supporting recurring payments I set one up and cancelled after the first - let me know if it didn't go through). I know it's not a massive amount but hopefully a token of appreciation which if we all did would, I am sure, make a difference.

**Comment by courville** [comment]
@mjnewton thanks, really appreciated.
Started to work on the implementation. Bare with me it will take some time but we will eventually get there.

**Comment by xrxca** [comment]
So while your at it, could any of the rows be disabled?
For instance, someone who uses their system strictly for movies doesn't need to see TV (and/or Animation).
Personally, my system is a frontend to my recorder, so all I use is the TV row, so it would be nice to turn off the perennially empty movie row.

**Comment by courville** [comment]
@mjnewton done.
@xrxca I already believe there are already too many customization options. Will take a look another time.

**Comment by mjnewton** [comment]
> @mjnewton done.

Just spotted this! Absolutely perfect. Thanks @courville !
