### ISSUE TITLE
[Bug]: F-Droid releases are far behind

### ISSUE THREAD

**Issue by alexanderadam** [nova-video-player/aos-AVP#567]
### Problem description

It would be great to have recent releases available on F-Droid.
This is not only useful for cases where [Google is making some problems](https://github.com/nova-video-player/aos-AVP/releases) but also for folks who don't have access to GPlay, Amazon Appstore or Huawei AppGalery.

### Steps to reproduce the issue

1. look at the [latest Nova release on F-Droid](https://f-droid.org/de/packages/org.courville.nova/#latest)

### Expected behavior

Seeing a recent release

**PS:** I don't know what the exact [Docker problem](https://github.com/nova-video-player/aos-AVP/issues/502#issuecomment-1024658683) is but maybe I can help.

**Comment by courville** [comment]
F-droid releases will be back when v6.0.x will be released on Google Play.
For now due to some build system requirements from F-droid, v5.x of nova cannot be submitted without some changes.
It should be fixed on v6.0.x

**Comment by courville** [comment]
Note to self, update nova yml to clean new openssl prebuilt.

**Comment by courville** [comment]
Let's merge the issue with https://github.com/nova-video-player/aos-AVP/issues/597 and pursue of the current f-droid MR https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10746

**Comment by ChristianCiach** [comment]
F-Droid builds are, once again, a few releases behind :)

Edit: Actually, all app store releases are a few versions behind the github release page..

**Comment by courville** [comment]
@ChristianCiach, current Google Play release is 6.0.81 same as F-Droid one. Github releases are "in the future".
I will publish on F-Droid as the same time as Google Play.
