### ISSUE TITLE
[Bug]: local NFO files

### ISSUE THREAD

**Issue by GrumpyLoneWanderer** [nova-video-player/aos-AVP#575]
### Problem description

Local NFO files not longer scrapping when moved from v5 to v6.

They were created in TinyMediaManager and worked in version 5 and kodi however after upgrading to v6 it won't scrape them, on android tablet or Firestick

### Steps to reproduce the issue

Tried on multiple devices, device running latest version on Google play store still reads them fine. Latest version 6 from github doesn't

### Your phone/tablet/androidTV model

Samsung Galaxy Tab A7

### Operating system version

Android Version 11

### Application version and app store

5.15.26-20210915.1928

**Comment by courville** [comment]
Quick question: do you experience the issue on local storage or SMB network share?

**Comment by courville** [comment]
BTW if this is related to local storage since Android 11 targeting API30 NFO files are not visible on local storage and thus mut be relocated cf. https://home.courville.org/nova_video_player-faq/index.html
> versions later than v6.0.30 targets API31 and due to Android storage restrictions for API30, local NFO/JPG media information files for videos stored on local storage have been moved to nova public application folder located /sdcard/Android/data/org.courville.nova/files/nfoPoster

**Comment by GrumpyLoneWanderer** [comment]
Hi,

SMB share, I saw on reddit someone else had same issue.

Regards
Alastair

**Comment by GrumpyLoneWanderer** [comment]
Hi, the files are located on smb

**Comment by biogaea** [comment]
I can confirm this issue.  
same device (armeabi-v7a, Android 10) --> fresh install NOVA Video Player & restart --> default setting & select "process '.nfo' files" --> index folders to add new content to the library

    When installing NOVA version 5.15.21:
    NOVA will process '.nfo' files and get metadata from '.nfo' files

    When installing NOVA version 6.0.43 and 6.0.46 :
    NOVA will ignore remote '.nfo' files and get metadata online (TMDb)

**Comment by GrumpyLoneWanderer** [comment]
Yea can't seem to get bing mode working either

**Comment by courville** [comment]
In nova v6.x processing of NFO files are disabled by default for the migration path.
Please check that re-enabling NFO processing in settings you still have the issue.

**Comment by GrumpyLoneWanderer** [comment]
Any idea when this will be resolved? moviedb.org does not handle some tv shows well

**Comment by courville** [comment]
Seems that the problem is in `relocateNfoJpgAppPublicDir`
```
D/com.archos.filecorelibrary.FileUtils: relocateNfoJpgAppPublicDir: smb://10.0.2.2/marcshare/fakenas/video/hd/tpb/Thor.Ragnarok.2017.1080p.WEB-DL.X264.AC3-EVO.archos.nfo -> /storage/emulated/0/Android/data/org.courville.nova/files/nfoPoster/marcshare/fakenas/video/hd/tpb/Thor.Ragnarok.2017.1080p.WEB-DL.X264.AC3-EVO.archos.nfo
```

**Comment by courville** [comment]
@GrumpyLoneWanderer, I do not know what basic version of TinyMediaManager does better when dealing with tmdb (apart from a manual editor).
FYI on v6 nova supports Movie collections/sagas which is very basic (no poster/backdrop) in TinyMediaManager but nova does create nfo with the required collections/sagas entries.
In other words with TinyMediaManager these images will be lacking and will create some UI issues.
You can however fix it by adding the missing fields of course (though would involve tedious work).

**Comment by GrumpyLoneWanderer** [comment]
@courville hi, thanks for that. I have tried to manually create no files, use TMM as use an nova export as template all with same result. Could you confirm which field is issue? And which are mandatory

**Comment by GrumpyLoneWanderer** [comment]
@courville I have tried with very basic kodi nfo file manually created in notepad++ it won't load the info, in v5 i had no problems. In v6 it won't load no matter method of creating the nfo file. The problem is nova does not recognise series with more than 2 digits so things like house hunters or megastructures won't get scraped. There is also alot of TV show episode info in moviedb that is not consistent. Plus I have alot of study videos which I can no longer organise

**Comment by GrumpyLoneWanderer** [comment]
I have also tested an exported nfo file from v5 and tried to import into v6 no luck

**Comment by courville** [comment]
Interesting comment about series with more than 99 episodes.
For now you need my patch to get it working back. Will make a release on github soon.

**Comment by GrumpyLoneWanderer** [comment]
@courville supper, thanks :) yea if you use manual nfo files nova v5 recognised series with 4 digits, but when scraping from online it only recognises 2 digits.
