### ISSUE TITLE
[FEAT]: Make stop button command over HDMI-CEC actually close the video instead of pausing

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#578]
### Description

Apparently, when you use HDMI-CEC to control Nova and press the stop button on the remote that comes with the TV rather than the Android remote (like the CCwGTV remote, for example), you actually pause the video rather than closing the video and going back to the episode/movie menu. 

PAUSE on Samsung remote = Pause Nova video
STOP on Samsung remote = Pause Nova video ( should instead close video, as expected)

Here's a picture of the standard Samsung TV remote I use with HDMI-CEC to control my Android boxes. Note the STOP and PAUSE buttons at the very bottom. They do the exact same thing (pause the video) rather than have the STOP button close the video and go back to the movie/tv menu. It would be nice to adhere to the expected behavior. 

![432px-Samsung_Smart_TV_remote](https://user-images.githubusercontent.com/49374058/154873652-15bf3382-4052-479b-b9ec-93b5e138827b.JPG)

### Additional information

N/A

**Comment by courville** [comment]
Indeed in `PlayerController` `KEYCODE_MEDIA_STOP` triggers a pause. Let's wire it to stop.
