### ISSUE TITLE
[FEAT]: Scraping Adult Movies

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#583]
### Description

Is there a way to enable scraping of adult movies or is this just not possible in themoviedb api?

I know there is a way to enable adult movies in the search results on the website, not sure if something similar is available on the api.

**Comment by courville** [comment]
tmdb provides this functionality which is disabled in nova in order to avoid the trouble of changing classification on google play. Google is quite picky around having a search showing some PG++ pictures.
You can enable it, if you want in `MovieScraper3` and `ShowScraper4` in the search queries.
I could make it a hidden option but I would like to avoid this due to Google thorough reviews.

**Comment by mschumacher69** [comment]
Thanks. How to enable it in MovieScraper3 and ShowScraper4?

**Comment by courville** [comment]
Are you ready to rebuild your own version of nova?

**Comment by mschumacher69** [comment]
Oh, I guess not...

If you can make it a hidden option, that would be great.

Would it be that obvious if you add it to the code? In the end Nova is just a player, it is not providing any content. I mean you won't accidentally scrape an adult movie unless you already have it in your library.

You can search for adult movies in Chrome or the Google app after all...

**Comment by morpheasgr** [comment]
@courville How about taking a patcher/addon approach that has to be sideloaded externally? As long as the code on Google Play does not include the feature (think of Grand Theft Auto - Hot Coffee situation as a bad example, the code was in the game files) I think you should be completely in the clear. They should age-restrict web browsers because you can go to PHub with that logic.

**Comment by courville** [comment]
I will think about it. I will make a paid addon ;-P (/me kidding)

**Comment by morpheasgr** [comment]
@courville dude, this is among the best video players available for the android platform right now, you deserve every donation that comes your way. By the way, please take a look at #584 whenever you have time to test the demonstration file I created.

**Comment by courville** [comment]
Do not get your hopes up, for now the feature is disabled by default and has to be enabled at compile time.

I will need to think about the best way to activate it.

**Comment by courville** [comment]
Next release on github will have this hidden option that you can access after enabling nova advanced options by 10 clicks on nova settings->software decoding.

This will never be available on Google Play release.

**Comment by mschumacher69** [comment]
Thanks! Would you consider releasing a self hosted version of Nova that would auto update itself through the app? You know considering Google have been rejecting your releases recently.

That would be the only way I would consider sideloading an external version, because I wouldn't want to have to manually sideload every time there's an update.

**Comment by courville** [comment]
Will update app via fdroid (need to reenable it).

**Comment by mschumacher69** [comment]
Great thanks! Would updating the app through fdroid update the current app that's installed through the play store while keeping the data or would I have to start over from scratch if I install Nova through fdroid?

**Comment by mschumacher69** [comment]
@courville can you please answer my question above?

Thanks

**Comment by courville** [comment]
Using fdroid you would have to reinstall since fdroid in the publication process recompiles from sources and sign the APK. But do not do it now since fdroid APK iOS very very old at the moment.

**Comment by mschumacher69** [comment]
OK thanks, please let me know when I can do it. Would have been nice if I could install 2 instances of the app, one for adult stuff from fdroid and the other one from the play store for regular stuff, do you think this is possible? Maybe if you name the fdroid package differently?
