### ISSUE TITLE
[Bug] Crash on "Change info of all episodes"

### ISSUE THREAD

**Issue by PcFish** [nova-video-player/aos-AVP#587]
Version: 6.046-20220218.2132
Shield TV Pro version with latest update, just did a factory reset so Nova is a fresh install.

It scraped files individually fine, but when I try to batch scrape TV shows it crashes and goes to home.
The files are on my network SMB if that matters

**Comment by courville** [comment]
You are right and it has been reported here https://github.com/nova-video-player/aos-AVP/issues/580
Let's close this one and follow through on this issue.
