### ISSUE TITLE
[Bug]: season poster defaults to series poster when changing series info

### ISSUE THREAD

**Issue by bronnel** [nova-video-player/aos-AVP#589]
### Problem description

When you want to change series info to another series , after the change has finished , season posters are downloaded but are not loaded , series poster is loaded instead for all seasons

### Steps to reproduce the issue

change series info to another series

### Expected behavior

seasons must have their own posters loaded in the view

### Your phone/tablet/androidTV model

LG V50

### Operating system version

Android 10

### Application version and app store

latest

**Comment by bronnel** [comment]
@courville There are more issues when changing series info, like episode stills not being scraped, episode guest stars tag also has conflicts, this needs to be looked at thoroughly and more deeply

**Comment by courville** [comment]
I fixed something lately related to changing tv serie info. It will not cover all of what you saw though.

**Comment by bronnel** [comment]
Thanks @courville

**Comment by bronnel** [comment]
this issue is resolved with these two commits
[fix episode picture](https://github.com/nova-video-player/aos-Video/commit/6ab258a62f87f1fba4202cc8ae4e20248002169b)
[fix season poster](https://github.com/nova-video-player/aos-MediaLib/commit/59b07886f5a41b04479b4ec724998c5221e97305)

**Comment by courville** [comment]
@bronnel, I guess that your fix applies also to the v6 branch: can you please confirm?

**Comment by bronnel** [comment]
@courville , yes definitely works for v6 too, confirmed, I spent 4 days on this one :)

now when changing series info to another , everything works as it should.
