### ISSUE TITLE
Deprecated DetailsOverviewRowPresenter API

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#6]
According to documentation https://developer.android.com/reference/android/support/v17/leanback/widget/DetailsOverviewRowPresenter, it needs to be replaced by FullWidthDetailsOverviewRowPresenter for instance in TvShowFragment.java but creates some UI regressions.

**Comment by ghost** [comment]
Done?

**Comment by courville** [comment]
indeed closed now in api28 branch
