### ISSUE TITLE
[QUESTION]Few things I need know

### ISSUE THREAD

**Issue by 2spider** [nova-video-player/aos-AVP#632]
1. How can I enable dark mode ?
2. How to block videos in some folders from been scanned.
3. I would like to edit library section and select movie source(s) for each label.
4. What's the best way to name and arrange movie directory  ( Movie Folders- Each movie saved in its own folder within the source or
    Flat Folder- All movie files are saved in the Source folder) ?

**Comment by courville** [comment]
1: not implemented yet
2: put a .nomedia file in the folder (see FAQ)
3: not clear to me
4: nova relies on scrape data to present the files in a structured media library way. Thus I would say there is no best structure unless you do file browsing to play files

**Comment by courville** [comment]
Please ask questions on the reddit community page, more suited for this type of interactions.
