### ISSUE TITLE
[Bug]: external player, VLC, unable to play path with space, incorrect path handling

### ISSUE THREAD

**Issue by mo-han** [nova-video-player/aos-AVP#637]
### Problem description

unable to play.
toast msg: `http://localhost:xxxxx/video filename with space.mp4`

### Steps to reproduce the issue

when external player enabled, in my case, which is VLC.
and the video filename has space.

### Your phone/tablet/androidTV model

meizu e3

### Operating system version

android 7

### Application version and app store

v6.0.62

**Comment by ghost** [comment]
Have the same issue. Any update on this?

**Comment by courville** [comment]
Ah fun one... Note that with Just Player it works.
Question: is this thus a bad url handling of vlc?

**Comment by courville** [comment]
From a file browser it does not work with vlc and works with just player.
I thus rule this as a vlc problem for now -> won't fix.

**Comment by ghost** [comment]
Makes sense.
