### ISSUE TITLE
Unable to choose subtitle

### ISSUE THREAD

**Issue by kralcak** [nova-video-player/aos-AVP#643]
When playing local mkv tv show with many subtitle tracks included inside the file I can choose only first 32 subtitle tracks. I can't choose any subtitle files which are stored together with the movie in same directory nor any subtitle which I download from open subtitles. Please change the limit from 32 to at least 50.

**Comment by courville** [comment]
Thanks for reporting.
I do not see obvious hard limit to 25 in the code (yet).
Could you please provide a file with 50 subs for me to test and debug (or at least the exact file name so that I can download it)?

**Comment by courville** [comment]
I checked a 26 subs embedded file and selecting sub 26 works (you need to wait for the buffer flush on current sub read though or seek).

**Comment by moneytoo** [comment]
When I tried a file with 34 subtitle tracks, only 32 showed - https://www.reddit.com/r/NovaVideoPlayer/comments/swrq1g/up_to_32_internal_subtitles_supported/

**Comment by courville** [comment]
@moneytoo this is another issue.
Could you please provide a file (exact file name would do)?

EDIT: I have found one file with 32 subs.

FTR I can change sub track on all the 34 ones (after a seek).

**Comment by courville** [comment]
OK thus for now I will classify the issue as "works for me (tm)".
Please react with more actionable inputs so that I do not close the issue.

**Comment by bladyle** [comment]
Same issue here. I have file with 30+ integrated subtitles and my subtitle is on the storage. I can choose it but it won't show in the list if if there are too many integrated subs.

**Comment by moneytoo** [comment]
Here's a sample with 36 subtitle tracks. I'm unable to select last 4 subtitle tracks (Ukrainian, Vietnamese and Chinese Simplified/Traditional) in Nova 6.0.71.

[mn-sample.zip](https://github.com/nova-video-player/aos-AVP/files/9079793/mn-sample.zip)

**Comment by hongfengfeiyang999** [comment]
> Here's a sample with 36 subtitle tracks. I'm unable to select last 4 subtitle tracks (Ukrainian, Vietnamese and Chinese Simplified/Traditional) in Nova 6.0.71.
> 
> [mn-sample.zip](https://github.com/nova-video-player/aos-AVP/files/9079793/mn-sample.zip)

I am also unable to display external subtitles

**Comment by Unix-Kernel** [comment]
Yeap, I can confirm that the last four subtitles will "not" show/display in the scraped page or when the video is playing, it only shows the first 32-subtitles, all other subtitles after that are not available.

**Comment by allonli** [comment]
this bug still exists in the current version. 2022.10.27

**Comment by wawava** [comment]
this bug still exists in the v6.0.82 release,please fix it

**Comment by wawava** [comment]
> 

maybe 34 is not enough ,i see one video ,it's have 44 subtitles
if you need test ,pelase down the video though bt [v6.0.82 release](magnet:?xt=urn:btih:A26DD97E6F117A89E84645D2C66042C03AFC6EB6)

**Comment by courville** [comment]
I am able to reproduce the issue with @moneytoo mn-sample file on leanback interface.
In avos:
```
av.h:#define SUB_TRACK_MAX		32
```

**Comment by courville** [comment]
Works on mn-sample file. Will be released on github later today as 6.0.83.

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases
