### ISSUE TITLE
[Bug]: can't use Nova as external player for Stremio apk

### ISSUE THREAD

**Issue by eSkRo32** [nova-video-player/aos-AVP#647]
### Problem description

Hi, when using other streaming apk's,
Like Stremio
When I open files with Nova player
Well
The file doesn't play.
But does play when using VLC. 

### Steps to reproduce the issue

Try to open a link with Nova as external player 

### Expected behavior

Nova plays the stream

### Your phone/tablet/androidTV model

Shield TV 2017

### Operating system version

Android 11

### Additional system information

I use Real-debrid with Stremio
Thanks

**Comment by eSkRo32** [comment]
Here's the reddit link where another user Also has this issue

https://www.reddit.com/r/NovaVideoPlayer/comments/v1dnq6/cant_open_realdebrid_links_with_nova_player/

Thx

**Comment by courville** [comment]
Let's follow this in https://github.com/nova-video-player/aos-AVP/issues/628
Will close as duplicate (but indeed valid issue).
