### ISSUE TITLE
Make global play button cycle through tv show airdate

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#65]
Cf. https://www.reddit.com/r/NovaVideoPlayer/comments/azqow3/new_beta_release_of_nova_video_player_v33/

> I thank you for adding the global "PLAY" button for TV shows, however, the button still doesn't take into account the chronological order of aired episodes, for example, I tested one TV show with two files, one file is from the "Specials" season, it is the S00E01, aired on december 12th 2002, the other file is from the first season, it is the S01E01, aired on september 16th 2002, so in this case, the "PLAY" button should start playback with the S01E01 because it was aired before the one in the "Specials" season, instead, the button starts playback with whatever it finds, in this case it starts playback with the S00E01.

I have though one side effect which is when a TV serie for whatever WTF reason is broadcasted (i.e. have airdate) in a random order.
It has been done for https://en.wikipedia.org/wiki/Firefly_(TV_series) (though very unfortunate).
In this non ideal world, there are two possible actions:

1. we stick with episode order and remove s00exx episodes from consideration
2. we go airdate based and leave with these unfortunate non understandable by customer weird induced behavior

I could do a poll but on my side I am in favor of method 1) (open for debate).

**Comment by ghost** [comment]
Solved?

**Comment by courville** [comment]
Solved indeed.
