### ISSUE TITLE
[Bug]: youtube resolution bug on trailers

### ISSUE THREAD

**Issue by Hotboy1987** [nova-video-player/aos-AVP#650]
### Problem description

When I want to play trailers for any movie or series and youtube open ,, it open in very big window and I can't see ant thing ,, that happen after I update from ver 5 to latest build of ver 6

### Steps to reproduce the issue

From ver 5 to ver 6

### Your phone/tablet/androidTV model

Nvidia shield pro 2019

### Operating system version

Android 11

### Application version and app store

6.66

**Comment by courville** [comment]
Thanks for reporting, it is fixed in the code now.
