### ISSUE TITLE
[FEAT]: put the play button at the beginning where it should be

### ISSUE THREAD

**Issue by nhockey** [nova-video-player/aos-AVP#653]
### Description

Why is "play" the fourth option in between "change info"  and "remove from library" I would say in order of things that I use a media player to do is "play" a media file so shouldn't that be first?

### Additional information

Move play back to where it was.

**Comment by courville** [comment]
Strange indeed. I guess you are referring to Android TV interface. Can you please provide a screenshot? This does not happen to me.

**Comment by nhockey** [comment]
Yes, in Android TV. I don't have any way to take a screenshot directly on the TV but I can attach a couple pictures of the TV.

![PXL_20220613_041743346](https://user-images.githubusercontent.com/436149/173279042-897c4b1a-6a60-421c-8b52-2118357035d5.jpg)

![PXL_20220613_041902886](https://user-images.githubusercontent.com/436149/173279017-1c34d0a0-668c-41e8-9959-02aac2ed4aae.jpg)

**Comment by nhockey** [comment]
Yes, in Android TV. I don't have any way to take a screenshot directly on the TV but I can attach a couple pictures of the TV.

Nova v6.0.67 (20220605.1136)

![173279017-1c34d0a0-668c-41e8-9959-02aac2ed4aae](https://user-images.githubusercontent.com/436149/173279858-6edfec05-344f-4c8c-b208-3955710f38ff.jpg)
![173279017-1c34d0a0-668c-41e8-9959-02aac2ed4aae](https://user-images.githubusercontent.com/436149/173279871-323f0b5a-cf39-42a2-a445-9b20d5ff21ca.jpg)

**Comment by nhockey** [comment]
Yes, in Android TV. I don't have any way to take a screenshot directly on the TV but I can attach a couple pictures of the TV.

Nova v6.0.67 (20220605.1136)

![173279042-897c4b1a-6a60-421c-8b52-2118357035d5](https://user-images.githubusercontent.com/436149/173280317-a800c44c-cac1-46b1-b338-da0099f5210e.jpg)
![173279017-1c34d0a0-668c-41e8-9959-02aac2ed4aae](https://user-images.githubusercontent.com/436149/173280320-4f116400-b109-4e8a-bb09-053efa4c553b.jpg)

**Comment by courville** [comment]
Ok thus is happens in the global tv show view and not in the single episode one

**Comment by nhockey** [comment]
Yes, the overview not on individual episodes. The individual episodes have the play button at the beginning as it's been.

**Comment by nhockey** [comment]
Thank you. I look forward to checking out the fix.
