### ISSUE TITLE
[Bug]: Third party player menu doesn't show up properly

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#658]
### Problem description

Third party player menu doesn't show up properly (splitted & at the bottom of the TV screen)

### Steps to reproduce the issue

First activate the option to select a third party player, and then try to play a movie.
The menu will appear at the bottom of the screen. When the player you want doesn't appear at first sight because you have a long list of possibilities, you have to scroll down "invisibly" (just by earing the sound in the menu) till the end, and then scroll up. After this workaround, the menu will finally appear correctly.

### Expected behavior

Menu with different players should show up properly at the center of the screen from the beginning

### Your phone/tablet/androidTV model

Freebox Pop

### Operating system version

Android 9

### Application version and app store

6.0.70 from github (but already present in all previous versions, including v 5.XX)

**Comment by courville** [comment]
This is an android "feature". The menu is from Android framework outside of nova jurisdiction...

**Comment by phhusson** [comment]
What TV model is it? Is it a 1080p model?

**Comment by courville** [comment]
Checked on nvidia shield both with a 4k and 1080p UI and 10 players (but still on a 4k TV...), the android selection menu shows now cropping and we can scroll through the full list.

**Comment by mitch133** [comment]
> What TV model is it? Is it a 1080p model?

Nope, it's a Samsung 4K one (UE50KU6000)

**Comment by mitch133** [comment]
> Checked on nvidia shield both with a 4k and 1080p UI and 10 players (but still on a 4k TV...), the android selection menu shows now cropping and we can scroll through the full list.

Ok, meaning that with future Android 10 upgrade for the Freebox it will finally work fine?

**Comment by phhusson** [comment]
Ok, I misunderstood the issue, I got it now thanks to @courville 's guidance

And err bad news, no it's not fixed in Android 10 on Player Pop. I'll look at it.

Edit: There it's fixed. It'll be in next Android 10 beta, and I'll add you then to the beta @mitch133

**Comment by mitch133** [comment]
Thanks @phhusson ! I'm already in for the beta (Thibaut added me a month ago if I'm right), but still waiting to receive it ;)

**Comment by phhusson** [comment]
@mitch133 there you go, you should have it now

**Comment by mitch133** [comment]
I just got it indeed, thanks! One question, where can I report bugs relative to this beta?

**Comment by phhusson** [comment]
The same place you asked to join that beta
