### ISSUE TITLE
[FEAT]: add subtitle format

### ISSUE THREAD

**Issue by JellyVlad** [nova-video-player/aos-AVP#660]
### Description

add subtitle format ASS

**Comment by MarcoRavich** [comment]
https://github.com/nova-video-player/aos-AVP/issues/128

**Comment by courville** [comment]
Indeed, closing as duplicate.

**Comment by MarcoRavich** [comment]
> Indeed, closing as duplicate.

Yup, but still needed by *many* users...

**Comment by ffwell** [comment]
> Indeed, closing as duplicate.

In fact, picture, sound and subtitle are all important elements for playback effect. There is nothing wrong with adding ass subtitle and inner subtitle support.
