### ISSUE TITLE
[FEAT]: Implement a "working" passthrough mode

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#662]
### Description

The actual experimental passthrough mode is not very stable and desynchronizes a bit audio and video.
Would it be possible to have a new one (Kodi and Plex ones work fine) ? Or a not so experimental one ?

**Comment by yaswanth127** [comment]
Yes that feature would be a great addition to the player which is now experimental

**Comment by phhusson** [comment]
This is a bug in Freebox Player Pop, keep it in Freebox's bug tracker
