### ISSUE TITLE
[FEAT]: Hope to add WEBDAV and NFS support

### ISSUE THREAD

**Issue by loongwar** [nova-video-player/aos-AVP#663]
### Description

Files on nas are shared via WEBDAV or NFS, and it will be more convenient to add these two protocols to use.

**Comment by courville** [comment]
webdav part is also reported here https://github.com/nova-video-player/aos-AVP/issues/368 and nfs here https://github.com/nova-video-player/aos-AVP/issues/544
Thus closing as duplicate.
