### ISSUE TITLE
[FEAT]: Search on ID when not found 

### ISSUE THREAD

**Issue by Quaap70** [nova-video-player/aos-AVP#669]
### Description

I understand that the official release in the google play store now uses TMDB. I had Nova scrape my SMB network share again, to create the new database. But I notice that, although most series are now better recognized, other local series are no longer recognized at all.. while known to both TVDB and TMDB. 

Another users feature request (last year before the change) was therefore to be able to search by TMDB ID (then TVDB)     when the title search does not give the expected result. This would indeed be a welcome addition.

### Additional information

Example of local TV series not found by Nova:

https://www.themoviedb.org/tv/27969-unit-13

Example episode file name:
Unit 13 - S01E02 Grazyna's Baby.mp4

**Comment by Cowboy1968** [comment]
I too would love this feature

Thank You

**Comment by courville** [comment]
Thanks for the valid report. I confirm the issue. I propose to first fix the incorrect scrape instead of implementing a new feature. The show should be scraped correctly.

**Comment by courville** [comment]
OK little update, indeed https://www.themoviedb.org/tv/27969-unit-13 is present but without poster and backdrop and no information. Nova thus declares it invalid.
To get it scraped, you need to fill out themoviedb info (contribute?).
Providing tv show id will not help int his case.
```
2022-07-08 15:31:27.399 4041-4443/org.courville.nova I/okhttp.OkHttpClient: {"page":1,"results":[{"backdrop_path":null,"first_air_date":"1996-10-12","genre_ids":[18],"id":27969,"name":"Unit 13","origin_country":["NL"],"original_language":"nl","original_name":"Unit 13","overview":"","popularity":5.387,"poster_path":null,"vote_average":9,"vote_count":1}],"total_pages":1,"total_results":1}
```
And I agree that tvdb has a proper entry https://thetvdb.com/series/unit-13

**Comment by Quaap70** [comment]
@courville No problem, I understand.  One problem at a time. Thanks!

**Comment by Quaap70** [comment]
@courville  OK I have completed the missing data for this series on TMDB (as far as images of a series from 1996 can still be found according to TMDB's standards in terms of size ). The series is now indeed recognized correctly, but the Trakt data for episodes already watched is not loaded. Is it because I can't find an image for the individual episodes?
