### ISSUE TITLE
[Bug]: Nova arm64-8a.apk cant be install on arm cortex a55

### ISSUE THREAD

**Issue by shanestonk** [nova-video-player/aos-AVP#683]
### Problem description

I cant install the app arm64-8a-api-21+.apk on my android tv 10 but can install the armeabi .apk version.

my cpu 

Amlogic S905C2 preliminary specifications:

CPU – Quad-core Cortex-A55 up to 2.0 GHz
GPU – Arm Mali-G31MP2 with support for OpenGL ES 3.2, Vulkan 1.0/1.1, and OpenCL 2.0

Architecture | Armv8-A (Harvard)

Extensions | Armv8.1 extensionsArmv8.2 extensionsCryptography extensionsRAS extensionsArmv8.3 (LDAPR instructions only)
-- | -
A64, A32, and T32 instruction sets

Video
Decoding – AV1 up to 4Kp120, 10-bit H.265, VP9, AVS2 up to 4Kp75, H.264 4Kp30
Encoding – 1080p60 H.265/H.264
HDR – HLG/HDR10/ 10+ Dolby vision, TCH PRIME

https://developer.arm.com/Processors/Cortex-A55

https://www.cnx-software.com/2022/02/04/amlogic-s905c2-quad-core-cortex-a55-processor-digital-tv-tuners-cas/

### Steps to reproduce the issue

Download the apk from nova https://github.com/nova-video-player/aos-AVP/releases

and try install the arm64-8a.apk version on android tv 10

### Expected behavior

Android package installer will said app cant be install.

### Your phone/tablet/androidTV model

Xiaomi tv q1e 55

### Operating system version

Android tv 10

### Application version and app store

6.0.71

**Comment by shanestonk** [comment]
https://stackoverflow.com/questions/46318682/apk-with-only-arm64-v8a-binaries-will-not-install

**Comment by shanestonk** [comment]
https://issuetracker.google.com/issues/37134362?pli=1

**Comment by phhusson** [comment]
Your device's Android only support 32 bits. That's the case of the vast majority of Android TV devices (the only known exception is nVidia Shield with 3GB RAM)
