### ISSUE TITLE
Set as external player for jellyfin

### ISSUE THREAD

**Issue by jesumguy** [nova-video-player/aos-AVP#701]
### Problem description

Jellyfin app set to use external player, NOVA can be selected  with "just once". It works perfectly fine. However when attempting to set NOVA as external player "always", nothing happens. Clarification, clicking the "always" button does nothing. The pop up closes. Clicking play brings the external player selection pop up back up and NOVA can be successfully selected with "just once", but "always" does nothing. 

Perhaps a clue. Instead of saying "always" (like it does with any other player) it instead says "Set to Always Open".  No idea if this is actually a bug, or intended. But NOVA is the only player exhibiting this behavior for me. Love the way NOVA handles .ass! 

### Steps to reproduce the issue

Repeat

### Your phone/tablet/androidTV model

Onn 4k uhd

### Operating system version

Android 10

### Application version and app store

Current version

### Additional system information

Directly connected to lg c1 oled, which passes audio to sony av.

**Comment by Pentaphon** [comment]
Why not just use Nova instead of Jellyfin? I tried Jellyfin and I find Nova way faster to use. If you can't get Nova to work with Jellyfin you might wanna try mpv-android as that is amazing for subtitles.

**Comment by jesumguy** [comment]
Firstly I don't feel this is the right place to discuss all the details of my ordeal, however, you asked. I have the UI and mixed content folder structure customized to my liking in Jellyfin. I have tried kodi and others, and don't like the way content is presented to the user in the ui. There's no way that I can see to mimic that presentation in NOVA. I have tried mpv, and just player. Mpv wouldn't allow audio passthrough, I tried the various mpv.conf instructions to no avail. The dev of mpv said it doesn't handle that correctly and recommended exoplayer. Just (video) Player works nicely however it for some reason fails to be recognized as existing when one episode ends and the next begins, no other player exhibited that issue when used as external player for Jellyfin. Ultimately I really like the way NOVA deals with .ass subs and would prefer to use it as the external player. I've tried various libvlc based players. They all had an issue, ass subs caused frame stutters with HW enabled, but without HW enabled wouldn't play 4k. It's been a long ordeal.

**Comment by Pentaphon** [comment]
Ok just checking. Hope you get your issue dealt with.

**Comment by jesumguy** [comment]
Thanks.

**Comment by courville** [comment]
Should be fixed by commit in https://github.com/nova-video-player/aos-AVP/issues/1095
