### ISSUE TITLE
[Bug]: Subtitles are Not Detected 

### ISSUE THREAD

**Issue by RuthlessRuler** [nova-video-player/aos-AVP#702]
### Problem description

So I just DDLed a Show and the internal subtitles (subs inside the mkv files) are not showing up on Nova.

If I use MX Player, then the subs shows up correctly for available languages.

Video is from -  Westworld (2016) Season 3 S03 (1080p x265 HEVC 10bit AAC 7.1 Silence)

### Steps to reproduce the issue

1. Start playing any episode
2. Click on subtitles button

### Expected behavior

All available subtitles shows up and user can select them

### Your phone/tablet/androidTV model

Poco X3 Pro

### Operating system version

Android 12

### Application version and app store

6.0.71

**Comment by moneytoo** [comment]
The file contains only PGS subtitle tracks but PGS isn't supported: #47

**Comment by RuthlessRuler** [comment]
Okay. Didn't knew about it. 
Will be tracking the mentioned Issues.

Thanks alot.
