### ISSUE TITLE
[Bug]: In rare cases, scrape returns a completely different title

### ISSUE THREAD

**Issue by efokin73** [nova-video-player/aos-AVP#713]
### Problem description

When searching for the title of a movie in Russian, in rare cases, a completely different movie with a dissimilar title is returned

### Steps to reproduce the issue

Set up a search in TMDB in Russian
Add the following file to the library
Крёстный отец 3 (1990).avi - it founds [Чудеса (1989)](https://www.themoviedb.org/movie/25074) - but there is [Крёстный отец 3 (1990)](https://www.themoviedb.org/movie/242-the-godfather-part-iii)
If you search on the TMDB site, then only the desired movie is found, but the application somehow gives out this other option

### Expected behavior

If there is an exact match by title, that particular movie should be returned

### Your phone/tablet/androidTV model

Xiaomi Mi Box S

### Operating system version

Android 9

### Application version and app store

6.0.71 from Google Play

**Comment by mitch133** [comment]
Happens to me as well, for example with Wonder (2017) and The Lion King (2019). Reports me Wonder Woman (2017) and some other stuff related to the Lion King (2019). In both cases, the reported movie is from the same year and shares some words with the title. Don't know if it helps. Deleting the description and seeking manually solves the issue, but it has to be done for every mistaken description.

**Comment by Pentaphon** [comment]
> The Lion King (2019)

I always leave names formatted as The.Lion.King.2019.mkv and it never makes a mistake. Same naming format when you get stuff from torrent sites.

**Comment by courville** [comment]
Thanks for sharing the examples: I can indeed reproduce. I will look into it.

**Comment by courville** [comment]
Damn, it turns out that I use Levenshtein distance to discriminate search results for tv shows but not for movies... This explains the behavior since it picks the first result and not the closest string match. I will add this feature for movies too.

**Comment by courville** [comment]
This should do it in next release (checked that it works with @mitch133 file names at least).

**Comment by courville** [comment]
Please reopen if issue persists.

**Comment by mitch133** [comment]
Works for me with 6.0.83, thank you.

I still have one file not being scraped. It's : "Les Aventures De Tintin (S01E13) - Tintin Au Pays De l'Or Noir (1992)"

I have to remove the beginning of the filename (Les... E13) in order to find the description.
It might be due to its long name, but as it works for the other 20 episodes I'm still a bit surprised.

Not a big deal in the end, but for you to know
