### ISSUE TITLE
v3.4 feedback

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#72]
You are on the right track! Congratulations!

1. Playback is much smoother than before - unfortunately there is still stutter, but much less! 
It is almost as smooth as MX Player.

2. Thank you for keeping movies, tv show row optional - I was very disappointed when I saw the interface initially. Going inside another view with TV shows is just another useless click and that grid  view is somehow ugly. Just  a remark here - when you tick the boxes for TV/MOVIES row the SHOW BY GENRE etc items are gone - They were available before.

3. Network is working

I will test more and let you know, but generally you are on the right track!
Thank you!

If you need something specific tested let me know.

**Comment by courville** [comment]
Thanks for the feedback.

**Comment by JJD2K** [comment]
Unfortunately there are quite a lot of issues with the UI. Hope it is because it is a development version.
For example entering a TV show with 2 seasons displayed the 2 seasons 2 times one after another - 1,2 then 1,2 again -  4 rows.
After that it soft crashed - exited while trying to browse.
Very often clicks are not registered - e.g on main screen trying to enter an item the click is registered (I do not remember how I see this but I think there is some sort of effect on the icon), but nothing happens. Clicking second time works.

P.S. This happens quite often so you will be able to reproduce it, The effect is that the thumbnail flashes mildly, but it is not opened.
