### ISSUE TITLE
[Bug]: Nova doesn't unscrap information related to deleted files

### ISSUE THREAD

**Issue by mitch133** [nova-video-player/aos-AVP#722]
### Problem description

Nova doesn't unscrap information about deleted files in library (over SMB) after a new scrap at launch

### Steps to reproduce the issue

Make a copy of an existing movie, naming it "xxx V2.mkv" for example
Delete the original (V1) file
Launch Nova, wait for scrap, and go to your movie.
2 files are still identified for the same movie. The deleted one cannot be located, but still appears

### Expected behavior

Nova should automatically unscrap deleted files in library

### Your phone/tablet/androidTV model

Freebox Pop

### Operating system version

Android 10

### Application version and app store

6.0.74 from github & 6.0.75 from Google Play

**Comment by Pentaphon** [comment]
I can confirm this with 6.0.74

**Comment by courville** [comment]
OK I reproduce and I know where it comes from. Will try to deploy a new version curing the database.
See https://github.com/nova-video-player/aos-AVP/issues/719

**Comment by courville** [comment]
OK I think I have a version that should cure this regression even for devices in the field. Could you please test is 6.0.77 does the job? It is available here: https://github.com/nova-video-player/aos-AVP/releases/tag/v6.0.77
Note that playback speed is re-enabled but should not cause stuttering if speed is not changed from 1.0x.

**Comment by mitch133** [comment]
Hello, thanks for the feedback and this new version. I will be able to test it next Tuesday.

**Comment by mitch133** [comment]
Problem solved here with this new 6.0.77 version. Thx

**Comment by ghost** [comment]
Can confirm v.6.0.76 has this same issue too (not removing info once deleted) on FireTV (Fire OS 7.6.0.8). Downloaded from the official Amazon App Store.
