### ISSUE TITLE
[Bug]: can’t sign into trackt, black window opens v6.0.74 on Shield

### ISSUE THREAD

**Issue by HDGuy** [nova-video-player/aos-AVP#723]
### Problem description

Exactly as in title, I go to log into Trakt and all I get is a black square that opens up full screen, no browser.

### Steps to reproduce the issue

Try to log in to Trakt.

### Your phone/tablet/androidTV model

Nvidia Shield Pro 2019

### Operating system version

Android 11

### Application version and app store

Latest hot fix 4

**Comment by courville** [comment]
OK sadly, I tried on my side and I am able to connect with nvidia shield.
Are you using any adblocker (e.g. pihole)?

**Comment by HDGuy** [comment]
Yup. That’s probably it. I’m using AdGuard DNS. It worked recently for some reason but it seems to be pretty spotty.

Please check the Framerate matching topic I started in April. Still having problems with 29.97 even though no other apps have problems with it.

**Comment by courville** [comment]
Please let me know what you did for adguard, I will add it to the faq https://home.courville.org/nova_video_player-faq/index.html (there is already something for pihole that could help).

For the framerate matching I will have a look.

**Comment by HDGuy** [comment]
Turned it off. Lol


But once you’re logged in Trakt works fine with it on, at leas it does for me.

Strangely I have no problem logging into Trakt on other apps with it on, it could be just the browser component of Nova that’s having the issue.
