### ISSUE TITLE
[Bug]:  multichannel PCM decoding doesn't work on option 2 of audio passthrough option

### ISSUE THREAD

**Issue by branches78** [nova-video-player/aos-AVP#731]
### Problem description

The new multichannel PCM decoding implementation available in the recent 6.0.75 stable version doesn't work.

The feature should work when option 2 is selected in audio passthrough.

I tested a Dolby TrueHD video on an AndroidTV/GoogleTV device without Dolby TrueHD passthrough support and I though it was going to be decoded as multichannel PCM, instead, no audio was output and the video played fast.

Turning OFF passhtrough decodes the codec to PCM with no problem.

### Steps to reproduce the issue

1) Open Nova
2) Go to settings to make sure option 2 is selected in audio passthrough
2) Look for the video
3) Hit play

### Expected behavior

Audio codecs not supported for passthrough on a given device should be decoded as PCM or multichannel PCM.

### Your phone/tablet/androidTV model

Realme 4K Stick with Google TV

### Operating system version

Android 11

### Application version and app store

6.0.75 from Play Store

**Comment by mitch133** [comment]
How do you connect your sound receiver? Optical (SPDIF)? If yes, in that case, it is normal you don't get any sound.

I opened this ticket couple of days ago:

https://github.com/nova-video-player/aos-AVP/issues/721

**Comment by branches78** [comment]
> How do you connect your sound receiver? Optical (SPDIF)? 

I forgot to mention that the device is connected directly to the AV receiver which has TrueHD decoding.

**Comment by courville** [comment]
Hi, thanks for reporting. Your issue is different from the others ones (see https://www.reddit.com/r/NovaVideoPlayer/comments/ydse0k/nova_vid%C3%A9o_6075/).
Note that 6.0.78 is out reverting to previous behavior with an option to check receiver codec capabilities which obviously does work in your case.

I would be interested in what your AV receiver/TV really reports in terms of codecs capabilities through looking at the output of `adb logcat` logs searching for the string `isEncoded` like `adb logcat | grep "isEncoded: hdmi RX supports"`.

Would you be able to provide this information?

**Comment by branches78** [comment]
Hello, it's been a while since my last reply on this topic and I have the reason why this is happening:

I recently purchased the new Onn 2023 Google TV box, it has Android 12 and I tested Dolby TrueHD with Nova, turns out Dolby TrueHD with or without Dolby Atmos was getting decoded to PCM correctly, something that the Realme Stick can't do, therefore I have two hypothesis:

1) The Realme stick lacks a Dolby Audio license which is something available in the Onn device and it appears the Nova app doesn't currently decodes Dolby TrueHD to PCM, therefore, the decoding is done by the Dolby Audio license instead.

2) Android 11 could be erroneously reporting to the Nova app that Dolby TrueHD is supported on the Realme stick when it's not, hence the reason why there is no sound when video is playing and the option in settings to force passthrough doesn't seem to be working either.

The rest of Dolby and DTS codecs are playing correctly thanks to the latest security patches applied to all my devices but I consider Android 11 the worst version I've ever tested 🤮

I don't think you need to do anything here other than to wait for Android 12 to arrive on the Realme stick so I can confirm any of my two hypothesis.

Thank you for your attention.

**Comment by branches78** [comment]
Closing this bug since the only solution is to play Dolby TrueHD videos with a Dolby Audio or Dolby Atmos license.
