### ISSUE TITLE
Nova video player does not play mp3 files

### ISSUE THREAD

**Issue by claudiubo** [nova-video-player/aos-AVP#734]
Nova video player does not play mp3 files

**Comment by Pentaphon** [comment]
It's called a video player for a reason. This player is about playing videos on your TV or touch-device, especially over a home network. You should use a server-based local music option like http://www.subsonic.org or a streaming music player like https://github.com/vfsfitvnm/ViMusic

**Comment by claudiubo** [comment]
Thank you for your answer!

I would like to have a single payer for all media , not one for movies, one for photos, one for songs and so on.
Seems like VLC fits the bill.

**Comment by Pentaphon** [comment]
VLC is fine but I personally think it is best to use different apps for different media. I use Nova for playing video on my TV, mpv for playing movies on my phone, ViMusic for playing music on my phone, and Simple Gallery for photos.

**Comment by courville** [comment]
Nice set of open-source apps.

For now nova is not intended to be a music player. I understand the request but it will not be met short term.
Once upon a time there was Archos music player (sharing some codebase of course) for this purpose.

Thus closing this issue for now.
