### ISSUE TITLE
[Bug]: Video stutters every 4-5 minutes

### ISSUE THREAD

**Issue by mschumacher69** [nova-video-player/aos-AVP#736]
### Problem description

Since 6.0.75, every time I play a video, it starts fine, then every 4-5 min, it skips around 10 sec and starts stuttering until I rewind. This keeps happening every 4-5 min and I have to rewind every time it happens to fix it.

### Steps to reproduce the issue

Just play a video on 6.0.75 or 6.0.76 and wait 4-5 min until it skips 10 seconds and starts stuttering.

### Expected behavior

Video should play smoothly without stuttering.

### Your phone/tablet/androidTV model

Chromecast with Google TV (4K)

### Operating system version

Android TV 12

### Application version and app store

6.0.76 from GitHub

**Comment by mschumacher69** [comment]
@courville any ideas here?

**Comment by courville** [comment]
Not yet, I will test on actual sabrina hardware to reproduce. I do not see any connection on the recent modifications I made so far.

**Comment by mschumacher69** [comment]
Great, thanks for your reply!

**Comment by courville** [comment]
OK, I launched the a video and so far so good (plays from SMB share 1080p).
For clarification sake, when it starts stuttering, does it keep stuttering afterwards or it gets back to non stuttering (to be sure I do not miss it while doing something else in the background)?

**Comment by mschumacher69** [comment]
Hey, thanks for trying to replicate this!

Are you trying on 6.0.76 or 6.0.80? Because I updated to 6.0.80 today and played 4 1080p episodes without a hitch, so I don't know what you changed but the issue doesn't seem to be there any longer on 6.0.80!

**Comment by courville** [comment]
I am using 6.0.80. Perhaps 6.0.76 had still some experimental speed control messing up the playback at 1.0x.
I am glad that it seems fixed with 6.0.80.
Let's close the issue for now and reopen if need be.
Thx

**Comment by mschumacher69** [comment]
@courville this is happening again, not every 4-5 minutes like before, but it happens 2-3 times per 45-60 min playback.
