### ISSUE TITLE
Nova V6.0.75 More Recognized DTS Audio Tracks

### ISSUE THREAD

**Issue by Philofil92** [nova-video-player/aos-AVP#737]
### Problem description

I'm on Android TV 11 on a TCL 65C825 TV! Then I don't go through the HDMI or P/dif port, but like many, I simply plug my hard drive into the USB2 port of the TV and for the DTS tracks to be detected by the TV until now, it was necessary that I enable "Passthought Mode 2" in Nova preferences for it to work and on 6.0.75 it doesn't work anymore!!! It's not too bad since I went back to 6.0.71 to make it work again! So, there is something different between these 2 versions!

I tested the 6.0.76 update, the problem is the same, so I reverted to version 6.0.71 which works correctly

### Steps to reproduce the issue

Any movie with "DTS audio" track

### Expected behavior

Correct player of any "Audio DTS" track

### Your phone/tablet/androidTV model

TCL 65C825

### Operating system version

Android TV 11 

### Application version and app store

Nova Video Player 6.0.75

### Additional system information

Mediateck MT9615

**Comment by courville** [comment]
Hi, thanks for reporting, it should be fixed on 6.0.78 github pre-release.
See https://www.reddit.com/r/NovaVideoPlayer/comments/ydse0k/nova_vid%C3%A9o_6075/

> This is interesting since in this version implements a check of the audio receiver capabilities before enabling passthrough and reverting to multichannel PCM if the receiver doesnot support the codec (this enables not to force passthrough if codec is not supported).In order to troubleshoot the issue, could you please get adb logcat logs of the app trying to isolate "isEncoded: hdmi RX supports" string and report back what is listed (cf. https://github.com/nova-video-player/aos-AVP/wiki/Debugging) ?It might be an issue in my implementation or your device not declaring the codec (though supporting it in reality for some royalties considerations).
> 
> Please detail what type of audio receiver (TV brand, sound bar, etc.).

I would welcome the output of `adb logcat` logs searching for the string `isEncoded` like `adb logcat | grep "isEncoded: hdmi RX supports"`

**Comment by Philofil92** [comment]
Thank you! I just updated to 6.0.78 and DTS detection works again by activating Passtrought Audio Mode 2 and Force Audio Passtrought. I answered you on https://www.reddit.com/r/NovaVideoPlayer/, but as I told you, English is not my natural language, I have a little trouble... Also, I don't know if it's better to post on https://www.reddit.com/r/NovaVideoPlayer/ or https://github.com/nova-video-player/aos-AVP/issues
