### ISSUE TITLE
[Bug]: cannot use nova as external player on Android 12

### ISSUE THREAD

**Issue by Tellivision** [nova-video-player/aos-AVP#745]
### Problem description

On Chrome Cast/Google TV 4K since android 12 Nova player can not be used as a external player, app dont even see Nova Player it doesnt show up as a option. After a look at the apk it does not have a V3 signature (android 9+). This would be my guess why it cant be seen by other apps.

### Steps to reproduce the issue

Update Chome Cast 4K to Android 12

### Expected behavior

Apps will not see Nova as External player.

### Your phone/tablet/androidTV model

ChromeCast/Google TV 4k

### Operating system version

Android 12

### Application version and app store

Newest Nova from git hub.

**Comment by courville** [comment]
Indeed:
```
apksigner verify --verbose build/outputs/apk/noamazon/release/Video-arm64-v8a-API_21+-release.apk
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Verified using v4 scheme (APK Signature Scheme v4): false
```
Adding missing:
```
enableV3Signing = true
enableV4Signing = true
```

**Comment by Tellivision** [comment]
> Indeed:
> 
> ```
> apksigner verify --verbose build/outputs/apk/noamazon/release/Video-arm64-v8a-API_21+-release.apk
> Verifies
> Verified using v1 scheme (JAR signing): true
> Verified using v2 scheme (APK Signature Scheme v2): true
> Verified using v3 scheme (APK Signature Scheme v3): false
> Verified using v4 scheme (APK Signature Scheme v4): false
> ```
> 
> Adding missing:
> 
> ```
> enableV3Signing = true
> enableV4Signing = true
> ```

Great! Please keep me updated I will also keep an eye out on releases! Thanks!

**Comment by courville** [comment]
Could you please try if this experimental build solves your issue: https://drive.google.com/file/d/1QzWksWwcM4A2spdPXOH9RqO7dGcoeNQ4/view?usp=sharing

**Comment by Tellivision** [comment]
Man I was really hoping it would solve the issue (lol it did not) it so wierd even Archos shows up.........

**Comment by courville** [comment]
@Tellivision can you please let me know from which app you are using nova as external video player?
EDIT: FTR, nova is proposed as application to open most videos on multiple file browser that I tested on Google Chromecast (sabrina)

**Comment by Tellivision** [comment]
Purple Player is the app that Im using.

**Comment by courville** [comment]
Seems to be a purple player issue.
