### ISSUE TITLE
[Bug]: SMB connection ends after 16/17min when using Just Player as an external player

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#754]
### Problem description

I originally posted this in the justplayer bug report:
"I have a very specific error using Nova Video Player with just player as the one actually playing the files. This issue does not occur when I start SMB videos from the Just Video Player itself, but when starting them from NOVA player.

After 16-17min (every time) the video stops playing with the following error: "java.net.ConnectException: Failed to connect to localhost/127.0.0.1:42057".

This error occurs on the Samsung Tab A7 tablet."

And got the following answer: 
"This looks really like Nova Video Player stops (or Android suspends the app) streaming/proxying video. I'm not sure what's the suspend policy when launching apps handling some intents but maybe it posting ongoing notification would help Nova. I'm afraid there's not much Just Player can do."
Link: https://github.com/moneytoo/Player/issues/373#issuecomment-1329634398

### Steps to reproduce the issue

Start any video over Nova Player using Judtplayer.

### Your phone/tablet/androidTV model

Samsung Galaxy Tab A7

### Operating system version

Android 12

**Comment by ghost** [comment]
It seems me posting here was unnecessary, as I seem to have fixed it. Apparently, Nova was not allowed to run in the background by the OS. I did not expect that Nova was feeding justplayer the stream in the background.

**Comment by phhusson** [comment]
Ok thanks for the report. So how did you fix it?

Worst case we probably can have JustPlayer do a foreground service bind to us to keep us alive

**Comment by courville** [comment]
Perhaps we need to have a notification while playing not to be killed. I will implement it.

**Comment by ghost** [comment]
> Ok thanks for the report. So how did you fix it?
> 
> Worst case we probably can have JustPlayer do a foreground service bind to us to keep us alive

The NOVA app was actively restricted as a background process in the samsung android OS. I now changed it to unrestricted and will later try if it also happens when the app is in 'automatic/balanced mode' (There is unrestricted, automatic and restricted modes on my tablet). I am not sure if the OS itself decided to restrict the app or not. Can't imagine me actively restricting Nova though.

 So I'm unsure if there really needs to be action taken especially since I dislike notifications that keep apps alive. Maybe it could be optional though if there's need for such a feature?

**Comment by courville** [comment]
FYI, I do not reproduce on pixel device, must be a specific samsung behavior.

**Comment by phhusson** [comment]
I think it's possible that Android automatically switches that mode (the "this app has been unused" notifications)... Anyway, we can probably check the value of that setting, to tell the user to switch it on when enabling external player

**Comment by ghost** [comment]
> FYI, I do not reproduce on pixel device, must be a specific samsung behavior.

It was also only occuring on my tablet. Neither my Oneplus, nor my pixel showed this behaviour, so it definitely is Company/OS specific.

**Comment by ghost** [comment]
Update: changing the setting fixed it for most of the cases, but the issue still happens eventually.
