### ISSUE TITLE
[Bug]: Can't access SMB share as a guest on Android TV

### ISSUE THREAD

**Issue by bladyle** [nova-video-player/aos-AVP#755]
### Problem description

As title says cant access SMB from Unraid server on Android TV. I have tried on my phone and there was no problem. Also from file explorers on the TV smb share is also available. 

### Steps to reproduce the issue

Nova Video Player (on android TV) -> Network & Files ->Network ->SMB/Network shortcut

### Your phone/tablet/androidTV model

Sony X900H

### Operating system version

Android TV OS 10

**Comment by bladyle** [comment]
Success when switched to Legacy interface, so I guess it's interface problem on the new interface?

**Comment by courville** [comment]
This is surprising that the legacy interface behaves differently: I will investigate.
Could you please detail what SMB server you are using and which SMB version it serves?

**Comment by bladyle** [comment]
Samba on the server is: Samba version 4.17.3 and used protocol is: SMB3_11. 
I think the problem is with Guest mode and option Shared folders under network. 
On my phone I have option to add new index folder under Shared folders menu and there is only address requirement.
On the TV I have to use Network shortcuts menu and from there it is required to add address of the server and login information. Maybe a guest check mark or something like that will fix this issue?

**Comment by mschumacher69** [comment]
Have you tried entering Guest as username and leaving the password blank? This works for me.

**Comment by bladyle** [comment]
> Have you tried entering Guest as username and leaving the password blank? This works for me.

No because as I know guest login mean blank credentials. Actually if I write guest or random name it show connected but can't see the content on the SMB.

**Comment by courville** [comment]
@bladyle while I figure out the difference between leanback and phone/tablet UI (`SmbListingFragment`, `SmbServerCredentialsDialog` vs. `BrowserBySmb`, `SMBServerCredentialsDialog`), could you please confirm that standard guest login without password works also on your side?
And could you confirm that on the legacy interface you used the "add SMB share by network URI"?

**Comment by bladyle** [comment]
Yes on legacy interface I has working using "add SMB share by network URI".
Guest login is working this way, I can access my files that are publicly shared (no user/pass required) with only smb ip adress.

**Comment by mschumacher69** [comment]
> No because as I know guest login mean blank credentials. Actually if I write guest or random name it show connected but can't see the content on the SMB.

For me it only works when I enter Guest as username and leave the password blank.

**Comment by courville** [comment]
FTR there is a difference between guest login and empty credential login with SMB it seems.

**Comment by courville** [comment]
@bladyle, could you please check this experimental build and let me know if it helps in your case?
https://drive.google.com/file/d/1PcLYn609NY7bkMm12GS1V4dmW9pPFzYR/view?usp=sharing

**Comment by bladyle** [comment]
I have installed this version but on top my current one. Don't want to uninstall mine to loose the library but with this version still cant access the menu under network - Shared folders (SMB)

**Comment by courville** [comment]
@bladyle, thanks for the feedback. BTW there is no need to uninstall your current release: apk is meant to install on top.

**Comment by courville** [comment]
OK this should hopefully do it (tested ok on my side), please check and report if this build works on your side: https://drive.google.com/file/d/1oBwSGHRJ7ri36wx_MclHsvxTtn06G54Q/view?usp=sharing

**Comment by bladyle** [comment]
Yes it's working now via the menu "Browse a network share" and entering only host IP (w/o user and pass)
