### ISSUE TITLE
[Bug]: Finishing with just player does not mark video as watched

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#758]
### Problem description

After finishing a video with just player as an external player the videos do not get marked as watched.

While watching a video and going back to Nova the current spot on the video gets carried over though.

### Steps to reproduce the issue

see above 

### Your phone/tablet/androidTV model

Any device (in my case Samsung Tab A7, Pixel 7)

### Operating system version

12

**Comment by courville** [comment]
I thought I checked this one but perhaps on AndroidTV and not phone interface (TBC). I can reproduce.
Note to self: add JustPlayer in `ExternalPlayerResultListener`

**Comment by courville** [comment]
OK issue is that at end of a video, justplayer returns `position` 0 and an extra data with `end_by : playback_completion` that needs to be interpreted.

**Comment by ghost** [comment]
Fix seems to work flawlessly, thanks!
