### ISSUE TITLE
希望增加webdav的挂载方式，

### ISSUE THREAD

**Issue by Dashan-IZ** [nova-video-player/aos-AVP#761]
### Description

希望增加webdav的挂载方式，

### Additional information

希望增加webdav的挂载方式，

**Comment by Dashan-IZ** [comment]
希望增加webdav的挂载方式，这个太有必要了，

**Comment by Dashan-IZ** [comment]
期待期待

**Comment by wowdd1** [comment]
+1

**Comment by courville** [comment]
Supplicate of https://github.com/nova-video-player/aos-AVP/issues/368
