### ISSUE TITLE
AList surppot[FEAT]: 

### ISSUE THREAD

**Issue by hyboyxo** [nova-video-player/aos-AVP#783]
### Description

May it surpport alist with adding alist address like "dubi.tk","https://dubi.tk".

### Additional information

TVBox surpport this feature.

**Comment by phhusson** [comment]
No idea what that is, and dubi.tk isn't in our native alphabet so it's going to be hard. Could you give more information?

**Comment by hyboyxo** [comment]
Thanks for reply。
Do you know about alist? https://github.com/alist-org/alist,it can dir the onedrive ,gooledrive,aliyundrive and so much other netdisks.some apks like tvbox(https://github.com/FongMi/TV,or other tvbox ),they can just add the alist url(for example,https://dubi.tk/,you can open the link and see the folders and files,just browse the filemanagers ),and play the video files in the player.just like the smb:// or nfs:// or webdav.
Just for referring.


















At 2022-12-25 16:43:53, "Pierre-Hugues HUSSON" ***@***.***> wrote:

No idea what that is, and dubi.tk isn't in our native alphabet so it's going to be hard. Could you give more information?

**Comment by wowdd1** [comment]
+1

**Comment by hyboyxo** [comment]
refer to "https://github.com/alist-org/alist/" please

**Comment by bryan-y-apollox** [comment]
You can take a look at this Lib: `com.github.thegrizzlylabs:sardine-android`, it's designed to operate WEBDAV.
And you can debug with this webdav API: 
http://alist.xiaoya.pro

url: http://alist.xiaoya.pro
path: dav
username: guest
password: guest_Api789

**Comment by luoxin1981** [comment]
+1

**Comment by courville** [comment]
@bryan-y-apollox with nova 6.1.1, I have tried to connect to your alist server but failed: is this server still active?
Please try with latest nova pre-release on your side.

**Comment by courville** [comment]
Let's follow progress there https://github.com/nova-video-player/aos-AVP/issues/368

**Comment by wisinfun** [comment]
Need this function very much
@courville https://github.com/alist-org/alist/

**Comment by courville** [comment]
@wisinfun, my understanding was that alist was supported through webdav support that has been added.

**Comment by phhusson** [comment]
Yes, NOVA's webdav support has been developed with alist.

It could have broken since then, but we'd need an actual bug report for it.

**Comment by happy-func** [comment]
When alist enables ssl, nova cannot connect normally regardless of whether it chooses webdav or webdavs. If alist turns off ssl, nova chooses webdav to connect normally
