### ISSUE TITLE
[Bug]: External subtitle .srt doesn't work in Just Player when using SMB.

### ISSUE THREAD

**Issue by samuraisword0** [nova-video-player/aos-AVP#788]
### Problem description

External subtitle .srt doesn't work in Just Player when using SMB.

### Steps to reproduce the issue

All external subtitle file not work when using external player, specifically when using SMB.

### Your phone/tablet/androidTV model

All Devices

### Operating system version

All versions

**Comment by moneytoo** [comment]
Is Nova passing the subtitles using the MX Player API (#140)?

**Comment by samuraisword0** [comment]
> Is Nova passing the subtitles using the MX Player API (#140)?

It's seemed to be a common problem for Nova that can't pass through external subtitle for all external players if the external subtitle was in local network storage. 

Just player can load external subtitle from local network storage when using Solid Explorer. 

And, MX Player also can load external subtitle from local network storage when uses "Local Network" feature in Mx player itself or same as Just Player by using Solid Explorer. 

Solid Explorer can load external subtitle for all external player from SMB without problems. 

I hope you can find a way to fix this problem and make Nova play external subtitle for all external players when use SMB just like Solid Explorer.

**Comment by courville** [comment]
Fair request pending for too long time: let's close this issue and follow in https://github.com/nova-video-player/aos-AVP/issues/140
