### ISSUE TITLE
希望webdav支持

### ISSUE THREAD

**Issue by yuanwenbing** [nova-video-player/aos-AVP#799]
### Description

希望webdav支持，特别喜欢这个播放器。界面特别舒服，但特别需要webdav

**Comment by wowdd1** [comment]
+1

**Comment by mjnewton** [comment]
Is this a duplicate of https://github.com/nova-video-player/aos-AVP/issues/761?

**Comment by InitialXKO** [comment]
> 

It's obvious, what an essential feature forgotten.
