### ISSUE TITLE
[Bug]: External subtitles not listed in the subtitles selection list

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#802]
### Problem description

If the show has many 20 or more integrated subtitles, the external subtitles file is not listed in the subtitles selection list and can not be loaded.
The external subtitles file is listed on the INFO page though.

### Steps to reproduce the issue

Play a show with 20+ integrated subs and use the UP arrow to go to the subtitles selection window. Your external subtitles will not be listed and you can not load them,

### Your phone/tablet/androidTV model

SONY ANDROID TV

### Operating system version

AndroidTV 8

### Application version and app store

latest version - all versions

**Comment by JJD2K** [comment]
I just tested another movie with just 2 integrated English subtitles and an external SRT file and the SRT file is also not displayed in the list and can not be selected.

Please fix this awful MAJOR CORE functionality bug.

**Comment by j0hntoken** [comment]
This problem does exist

**Comment by courville** [comment]
@JJD2K, is your first report related to https://github.com/nova-video-player/aos-AVP/issues/617 and closed issue https://github.com/nova-video-player/aos-AVP/issues/643 (not yet released)?

Regarding latest comment it seems to happens in your case without many subtitle files.

I have just tested on latest github release a video file with 29 embedded subs and 3 external srt subs located on a SMB share on Android TV nvidia shield and I can select all subs in the interface and display them.

I propose that we focus on a reproducible use case on my end: i) only using nova (no external player), ii) video file on SMB share as well as the external subtitles files. Please share a reproducible setup.
Close also any related issue to avoid confusion and parallel tracks of investigation.

**Comment by JJD2K** [comment]
Hello
I do not want to mislead you, I think that SRT file was damaged. I used another SRT file and it worked.
I will test your latest fix and report back.

**Comment by j0hntoken** [comment]
> @JJD2K, is your first report related to #617 and closed issue #643 (not yet released)?
> 
> Regarding latest comment it seems to happens in your case without many subtitle files.
> 
> I have just tested on latest github release a video file with 29 embedded subs and 3 external srt subs located on a SMB share on Android TV nvidia shield and I can select all subs in the interface and display them.
> 
> I propose that we focus on a reproducible use case on my end: i) only using nova (no external player), ii) video file on SMB share as well as the external subtitles files. Please share a reproducible setup. Close also any related issue to avoid confusion and parallel tracks of investigation.
I have such a file, but how should I send it to you? The file size is 30GB

**Comment by j0hntoken** [comment]
@courville I have such a file, but how should I send it to you? The file size is 30GB

**Comment by courville** [comment]
Exact file name so that I can find it somewhere.
But please test with latest github release AND check that it is not a pgs embedded subs that nova does not support (yet).

**Comment by JJD2K** [comment]
Hello
I've sent you many files via email in the past.
Sent you another example on your email
The file name that I sent you has 32 subtitles and the external subtitles are not listed.

I am testing with the latest version from the App store on Sony TV on samba share.

**Comment by j0hntoken** [comment]
It has been confirmed that the embedded Blu-ray sup subtitle cannot be displayed

**Comment by j0hntoken** [comment]
In China, we call it soft subtitle

**Comment by wwwjava** [comment]
I confirm the issue, just the same as JJD2K:
https://zamunda.net/banan?id=718213&hit=1&t=movie
[Backpackers.2022.SPA+ENG.1080p.NF.WEBRip.DDP5.1.x264-TEPES](https://zamunda.net/download_go.php?id=718213)

The best player so far for my Sony TV, Android 9. I use it 6 months now, play movies every single day, SMB folder of my PC.
VLC from within Windows shows the same .srt file with no problem

**Comment by courville** [comment]
@wwwjava thx for sharing the file but unfortunately I get an error trying to get to zamunda.
My guess though is that the file contains embedded sub that is PGS format that nova does not support (yet).
I.e. internal subtitle, not external subtitle issue.

**Comment by wwwjava** [comment]
Some update: all of the integrated subtitles works fine. Maybe there is so many.
So, I removed all the integrated subtitles (with Videoproc converter) and this worked. Now NOVA player let me choose and load external subtitles. No problem with files containing 3-4-5 integrated subtitles. Cannot tell witch is the limit.

**Comment by courville** [comment]
@wwwjava just to be clear, in the unpublished on google play github release, I removed the 32 sub tracks limit on nova and pushed it to 64. Thus with https://github.com/nova-video-player/aos-AVP/releases it "should" work.

**Comment by wwwjava** [comment]
Thanks, will try to install it.

**Comment by wwwjava** [comment]
Installed and working like a charm.

**Comment by wdisk2020** [comment]
> It has been confirmed that the embedded Blu-ray sup subtitle cannot be displayed

I hope it will support the embedded Blu-ray sup subtitles soon.

**Comment by JJD2K** [comment]
Thank you very much, this issue is finally fixed!

**Comment by JJD2K** [comment]
@courville 
Unfortunately this issue is back. I sent you sample files on your email.
The file has 34 integrated subtitles yet it does not work. Regression?

**Comment by JJD2K** [comment]
@courville 
This issue is fixed with your latest official release.
