### ISSUE TITLE
[FEAT]: Mega Support

### ISSUE THREAD

**Issue by TommyTran732** [nova-video-player/aos-AVP#804]
### Description

It would be great to have support for cloud storage providers, specifically Mega as it supports E2EE. I noticed that Infuse has support for this, so it would be great if Nova can support it too.

**Comment by phhusson** [comment]
Are you aware of a generic library (preferably a native library) that support various cloud providers properly? https://github.com/nova-video-player/aos-AVP/issues/783 mentions https://github.com/alist-org/alist which looks interesting, but it doesn't support streaming from mega (it starts by downloading the whole file before serving it. it does support streaming  for other protocols)

**Comment by TommyTran732** [comment]
No unfortunately. I wonder how Firecore does it... hm...

**Comment by bryan-y-apollox** [comment]
You can take a look at this Lib: `com.github.thegrizzlylabs:sardine-android`, it's designed to operate WEBDAV.
And you can debug with this webdav API:
http://alist.xiaoya.pro/

url: http://alist.xiaoya.pro/
path: dav
username: guest
password: guest_Api789

PS: webdav definitely supports streaming. I can watch video(30GB size) through webdav with Infuse.

**Comment by phhusson** [comment]
I can't connect to your webdav. However I managed to launch a webdav server locally, that should be enough.

**Comment by courville** [comment]
Let's follow progress there https://github.com/nova-video-player/aos-AVP/issues/368
