### ISSUE TITLE
Disque dur externe/Carte SD Manage_external_storage

### ISSUE THREAD

**Issue by Philofil92** [nova-video-player/aos-AVP#806]
### Description

Bonjour à tous, c'est une restriction du système à partir d'android 11 et android tv 11, si l'on a bien accès en lecture (fort heureusement!)é sur un disque dur externe ou carte SD, malheureusement, il n'est plus possible de "supprimer un fichier à partir de la bibliothèque Nova", ni de copier un fichier, car les droits ont été limités par le système à partir d'android 11! 

Par exemple, on sélectionne le fichier à effacer, on le supprime, celui-ci disparaît de la base de donnée bibliothèque Nova, mais le fichier réapparait quelques secondes plus tard avec sa fiche, comme si rien ne s'était passé... 

SI l'on pouvait revalider la fonction "supprimer un fichier", ce serait formidable !

### Additional information

J'ai consulté le net...j'ai trouvé un article ou il mentionnait ce problème avec une aide pour les développeurs...

"https://developer.android.com/training/data-storage/manage-all-files"

**Comment by Philofil92** [comment]
Je rajoute une petite information, qui peut peut être servir pour une solution !

Android 11 a apporté des modifications concernant l'autorisation d'accès au stockage externe.

https://developer.android.com/about/versions/11/privacy/storage

IME, les modes requestlegacystorage ne fonctionnent PAS correctement. Les applications doivent être mises à jour pour utiliser le stockage étendu ou, dans certains cas, "l'accès à tous les fichiers".

Si vous utilisez des ROM personnalisées, elles autoriseront souvent des options pour désactiver ces nouvelles exigences (modes "accorder toutes les autorisations")
3
Avatar de membre
niveau 2
SEVASTIANISBACK
·
il y a 6 m.

Vous pouvez utiliser un éditeur APK et ajouter <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" /> dans le fichier AndroidManifest.xml (au même endroit où d'autres autorisations de ce type sont écrites). Je l'ai fait avec des applications auxquelles je voulais donner accès pour utiliser tous les fichiers de mon appareil et cela a fonctionné, donc cela pourrait fonctionner pour contourner ce bogue. Je n'ai pas de stick Realme 4K donc je ne peux pas tester ça.

**Comment by courville** [comment]
Bonjour cf. https://github.com/nova-video-player/aos-AVP/issues/336 manage external storage n'est pas autorisé sur le google play store pour des lecteurs multimédias (sauf vlc...).
J'ai une option dans nova qui le supporte mais ce n'est pas la version qui sera disponible sur les stores.
Désolé.

**Comment by Philofil92** [comment]
Bonjour, et bien, c'est bien dommage...car retirer mon disque dur de ma TV, puis le mettre sur un PC pour supprimer la vidéo que je viens de voir est pénible alors que la fonction "Suppression" est disponible sur Nova, le minimum est de pouvoir écrire et lire sur un support externe!!! J'ai une préférence pour les systèmes qui offre une certaine liberté aux utilisateurs...c'est pour cela que je déteste tout ce qui est "Apple", mais je vois qu'au fil du temps Android va dans une certaine mauvaise direction au fil des versions, bon! pas le choix, on va donc faire avec! 
Merci du retour
Cordialement
