### ISSUE TITLE
[FEAT]Disable auto scan media on device

### ISSUE THREAD

**Issue by coolllman** [nova-video-player/aos-AVP#808]
### Description

Problem: when i download video on shield tv from torrent to external usb hdd, nova auto scan media and add this video in library. Bug: when i rename this video or change destination, nova don't let me add this video in library (i'm delete previous auto scan video from library), only re-install or reset data nova help with this problem.
Please add any option to disable auto scan or fix the bug.

**Comment by courville** [comment]
Can you please elaborate on how you rename or move the file? If this is with an Android tool, it should notify Android system media library.  Note that nova is in sync with Android media library. Thus if something is wrong then Android is off too.

**Comment by coolllman** [comment]
Sorry, i try with another filemanager, and all works, thank you

**Comment by coolllman** [comment]
Total commander issue not nova

**Comment by courville** [comment]
Thx for the confirmation
