### ISSUE TITLE
jcifsng: add mechanism to inject samba discovery result into netbios/IP resolution cache

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#81]
jcifsng has now its proper caching.
nova out of band discovery has nat transversal support not supported by jcifsng resolver.
Make jcifsng of discovery result.
Potentially build own resolver and expose to jcifsng.

**Comment by nnoury** [comment]
discovery plugged in new cache
removed remaining legacy jcifs fork
jcifsng branches rebased on top of last nova
https://github.com/nova-video-player/aos-FileCoreLibrary/blob/jcifsng/src/jcifs/netbios/UdpDiscovery.java

**Comment by courville** [comment]
https://github.com/AgNO3/jcifs-ng/issues/163

**Comment by courville** [comment]
Not needed afterall.
