### ISSUE TITLE
[Bug]: No file access after upgrading to Android 11

### ISSUE THREAD

**Issue by jabb01** [nova-video-player/aos-AVP#810]
### Problem description

A problem occured after I upgraded my Philips TV (55OLED854) to Android 11:

No longer access to files on an external USB drive. The drive has a lot of folders and subfolders with videofiles. All folders are shown, but when I open any folder I get the message “Empty folder”.

I checked permissions for Nova Player, and can’t see any problem there.

The internal Philips media player has no problem accessing the files.

### Steps to reproduce the issue

Open any folder on external drive (Seagate Backup Plus 8TB drive).
All folder appears empty.

### Your phone/tablet/androidTV model

Philips 55OLED854

### Operating system version

Android 11

### Application version and app store

6.0.93

**Comment by courville** [comment]
If folders are empty, it means that there are no files from external drive imported in Android Media Library (not nova's one but internal Android system one). On nvidia shield since Android 11 you need to enable external drives scan in Android settings. I do not know if such an option exists on Philips TVs...

**Comment by jabb01** [comment]
Thanks.
Unfortunately, no such option can be found in Android settings on the Philips TV.
The strange thing is that when I insert a 32GB USB flash drive, Nova can access and play all media files in all directories.

**Comment by jabb01** [comment]
I still think there's something in Nova that prevents accessing the files on the Seagate Backup Plus 8TB drive on Android 11.
I installed the FX File Explorer on the TV, and this app can read all files on the drive and play video files in it's integrated player.

**Comment by jabb01** [comment]
Could this be a solution:
https://support.google.com/googleplay/android-developer/answer/10467955?hl=en

**Comment by courville** [comment]
> Could this be a solution: https://support.google.com/googleplay/android-developer/answer/10467955?hl=en

This will not help since nova is not granted this permission when publishing on Google Play (see other issues about this).

**Comment by courville** [comment]
> Thanks. Unfortunately, no such option can be found in Android settings on the Philips TV. The strange thing is that when I insert a 32GB USB flash drive, Nova can access and play all media files in all directories.

If it works with a 32GB USB flash drive, this means that the content of the drive is well indexed by Android framework and nova can thus have access to this information from Android Media Library. If through file browsing, nova can see the files on the flash drives, this means that nova has the right privileges to see external usb storages as well. This indicates that everything is fine on the Philips TV.
However it does not explain the failure on the seagate hdd so far.
Android 11 will only grant visibility of multimedia files to nova (limitation for multimedia player except the lucky vlc and a limitation that does not impact file managers like FX File explorer).
Failure on seagate hdd would indicate that the multimedia files have not been indexed properly by Android framework (not nova).
The Android framework indexer could crash when analyzing your hdd on a corrupted file interrupting the overall indexing process leading to non visible files for nova (an adb logcat at hdd insertion would be a good start to see if this hypothesis is correct).
One other try would be to reformat your drive, drop a couple of multimedia files and retest.

**Comment by jabb01** [comment]
Many thanks for your explanation.
I will try to reformat the hdd and then try again.

**Comment by jabb01** [comment]
I fixed the problem without reformatting.
I found a .nomedia file on it which I deleted, and I also renamed the hdd.
All is fine now :-)

**Comment by courville** [comment]
Hem ok .nomedia means Android does not index the folder and nova does not see the file since only multimedia files are made available to nova due to Android storage privacy restrictions (imposed when publishing on google play for multimedia player). Case closed.
