### ISSUE TITLE
[Bug]: The latest version(v6.0.95) wont start on  android 12

### ISSUE THREAD

**Issue by ReddotCleaner** [nova-video-player/aos-AVP#816]
### Problem description

the latest version(v6.0.95) wont start on  android 12. It got stucked on start page.
![image](https://user-images.githubusercontent.com/34325738/216803567-6ba5d9f6-ccaa-43b3-a024-aea743b6e846.png)

### Steps to reproduce the issue

just update to v6.0.95,  start app.

### Expected behavior

stuck on start.

### Your phone/tablet/androidTV model

mi 10T

### Operating system version

android 12

### Application version and app store

v6.0.95

**Comment by courville** [comment]
Could you please try to reboot your mi 10T and see if the problem still occurs?

**Comment by ReddotCleaner** [comment]
> Could you please try to reboot your mi 10T and see if the problem still occurs?

It works after reboot, thanks.

**Comment by courville** [comment]
Cool, known issue listed in FAQ BTW.
Thanks for the confirmation.
