### ISSUE TITLE
[Bug]: Broken network access on FireTV devices for Time Capsule SMB1

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#819]
### Problem description

Nova v6.0.95 (20230204.1344) on Fire OS (Fire TV devices) now has broken network access to SMB shares. Was working with previous version.

### Steps to reproduce the issue

Simply open the app on Fire TV devices and no media on network share can be accessed. The library was working with previous versions of the same app. Tried uninstalling and installing, same problem.

This happens on Fire Cube 4K Gen 2 (Fire OS 7.6.2.4) and Fire Stick 4K Max (Fire OS 7.6.1.4). One device is wired, the other WiFi.

Before uninstalling, tried clearing cache and data; same problem. Upon re-install, tried adding SMB share again, and while it shows up, it cannot be accessed.

### Expected behavior

Access SMB share as usual (like all previous versions did without a problem).

### Your phone/tablet/androidTV model

Fire Cube 4K 2nd Gen

### Operating system version

Fire OS 7.6.2.4

### Application version and app store

v6.0.95 (20230204.1344) on Amazon Appstore

### Additional system information

Share is SMBv1

**Comment by courville** [comment]
Thanks for reporting. Could you please detail which SMB server you are using?
This might be a fix https://github.com/AgNO3/jcifs-ng/commit/2bbc749e84ff104e76808dc61c2cde2e5ecd2a04
Apparently latest jcifs-ng upstep could break some SMBv1.
Will integrate latest jcifs and publish a release.

EDIT: on synology SMB1 still works. Can you please disclose which SMBv1 server you use?

**Comment by courville** [comment]
See https://github.com/nova-video-player/aos-FileCoreLibrary/commit/dbf4707bb0c1ee1f28fd1fd0e27df156190d4ba7

**Comment by ghost** [comment]
Using Apple Time Capsule as SMBv1 share. Worked perfectly until this version.

**Comment by courville** [comment]
@Molasar49 ok thank you for your comment.
Could you please check if this build https://drive.google.com/file/d/1-HoPfztgctk7Kro1lHJt1dY-W5MxWYai/view?usp=sharing solves the issue on your side?

**Comment by courville** [comment]
@Molasar49 were you able to test the build shared?

**Comment by ghost** [comment]
Testing right this moment... will post back in a few minutes.

**Comment by ghost** [comment]
Working. Can confirm that SMBv1 access to TIme Capsule is working. Thanks!

**Comment by courville** [comment]
Thanks for the testing and feedback: I will deploy a new release with this fix.

**Comment by courville** [comment]
Fun fact: mbechler fixed an issue that I filled based on logs of crashes seen in the field that turned out to be your issue.
