### ISSUE TITLE
F-Droid fails to pick new versions

### ISSUE THREAD

**Issue by ClockGen** [nova-video-player/aos-AVP#820]
F-droid failed to pick recent versions, it's stuck at 6.0.81:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.courville.nova.yml#L805.  

However there's a new tag in F-Droid specific repo:
https://github.com/nova-video-player/aos-Fdroid/releases/tag/v6.0.95_c600095.  

Not sure why, but it seems `versionCode` and `versionName` in build.gradle has been changed to non-literal:  
https://github.com/nova-video-player/aos-Video/blob/0e354886ad565f34ba2ec95e339353e3c28f74af/build.gradle#L131  
They need to be literal and not generated or referenced from anywhere else for f-droid scanner to pick them up.

Can you please change it back and tag the aos-Fdroid repo again?

**Comment by courville** [comment]
Oh thanks for the heads up on this one. I will indeed fix it. Regression comes from realigning all ABI to same version part of Google Play migration to bundle releases.

**Comment by courville** [comment]
Blind fix pushed https://github.com/nova-video-player/aos-Fdroid/releases/tag/v6.0.96_c600096
Let's see if F-Droid picks it up.

**Comment by ClockGen** [comment]
It was picked up and built fine in the last buildcycle:
https://monitor.f-droid.org/builds/log/org.courville.nova/600096#site-footer
Thanks for the fix.

**Comment by courville** [comment]
Cool thanks for the notice. I am glad that the fix complied with F-Droid CI requirements (which logic is not always obvious to my simple mind).

**Comment by courville** [comment]
Reopened since to fix Android TV requirement to use `archivesBaseName`, `versionCode`and `versionName` are not literal anymore.

**Comment by mzhboy** [comment]
f-droid stop picking up new version again, current f-droid version is 6.2.95 (602095)

**Comment by courville** [comment]
I have not tagged recent versions until ready for release (soon).
