### ISSUE TITLE
[Bug]: Issue Scraping Japanese TV show

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#839]
### Problem description

I have the show 'Soko ga shiritai' using normal naming conventions. The show is listed on tmdb https://www.themoviedb.org/tv/81034 but Nova is unable to find the show.

I'm simply wondering what the issue is here. Other Japanese shows like Gaki no Tsukai or Kodoku no Gurume are no issue: https://www.themoviedb.org/tv/72974

### Steps to reproduce the issue

Try searching for soko ga shiritai in Nova.

### Your phone/tablet/androidTV model

Any

### Operating system version

Any

**Comment by ghost** [comment]
The issue seems to be that due to nova's settings it will only search for English language shows for example. However, switching to japanese does not remove the issue.

Edit: Any chance for a solution which is less language specific? My collection is language-wise all over the place, literally.

**Comment by courville** [comment]
Nova searches for locale language and english results but submit the file name title to tmdb that should take it in a language agnostic way. I do not know why it does not capture your use case.

Nevertheless, I have reworked the whole ISO639 and languages supported for scraping. Please give a try to latest nova pre-release (6.2.19) and report if there is any improvement.

**Comment by ghost** [comment]
Thanks for the update. For the show above the situation sadly is still the same. Trying to get the info for it I'm unable to find the show at all via nova.

**Comment by courville** [comment]
Just to be sure to test the same, can you please provide me with the exact file name that you are using that fails?
What I try to understand is if the regex logic I use to determine that the file processed is a tv show is failing with the specific file name used.

**Comment by ghost** [comment]
Just for clarification: filename itself and then manually searching for a show is basically the same, right? I tried basically everything that made sense for me when trying to search for the show, so just the name 'Soko ga Shiritai', capitalized and not-capitalized, I tried with and without episode numbers (s01e03 etc) and including dates. I'm not able to find the show at all, doesn't matter what info language I set within Nova.

One thing I noticed is that it says it can't find the 'movie', this is just a general message and does not depend on the search parameters including episode numbering, right?

Looking up the show on tmdb it is listed as documentary, could that in any way be an issue?

Edit: the filename is 'Soko ga Shiritai - s01e03'

**Comment by courville** [comment]
On tmdb [Soko ga Shiritai](https://www.themoviedb.org/tv/81034) is listed to have only one season and one episode. Perhaps this is the reason why s01e03 is not found. I will check if this assumption is correct looking at debug logs.

**Comment by ghost** [comment]
That should not be an issue. Oftentimes I include special episodes as for example non-existing episode 13 in a season of 12 episodes and Nova still adds it without any episode information. Also searching for s01e01 in Nova still gives me no result.

Edit: also, changing the info language for either tv or movies also changes the other, intended? If yes, we don't need them as separate options

**Comment by courville** [comment]
OK clear now: the show is discarded by nova because it has no poster and no banner on tmdb and do not pollute the positive results displaying show results without image.
I could in case of an empty search add these too...

**Comment by ghost** [comment]
That would be nice, or after the first search result a button allowing a wider search or something like that? Because maybe there is a result but it's not fitting, but a wider search for the show would yield a result. I'd certainly prefer coverless entries in my library than missing shows completely.

**Comment by courville** [comment]
Please test https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.21 that includes latest correction that should address your issue.

**Comment by ghost** [comment]
It works!

Is there any way to add my own poster?
