### ISSUE TITLE
[Bug]: I can't play the video when using WebDAV

### ISSUE THREAD

**Issue by Darkxc9** [nova-video-player/aos-AVP#867]
### Problem description

When using Realdebrid WebDAV, the videos are not played .. The server was tested on Fx File Explorer, it works successfully, I hope the bug is resolved.

### Steps to reproduce the issue

![Screenshot_٢٠٢٣٠٤٠٦_٠٦٥٢٣٦_Nova Video Player](https://user-images.githubusercontent.com/87947125/230269481-98d687a5-3ce0-4b38-8288-cfa7e5b11797.jpg)
![Screenshot_٢٠٢٣٠٤٠٦_٠٦٤٧٠٨_Nova Video Player](https://user-images.githubusercontent.com/87947125/230269496-044057d8-4f71-435f-a3e2-b170dca7137a.jpg)

### Your phone/tablet/androidTV model

Android

### Operating system version

13

### Application version and app store

Google Play version 6.1.6-20230404.2327

**Comment by courville** [comment]
Let's follow progress on this issue here: https://github.com/nova-video-player/aos-AVP/issues/1018 and close this one
