### ISSUE TITLE
[Bug]: Can't connect to local WebDav

### ISSUE THREAD

**Issue by zwoggel** [nova-video-player/aos-AVP#874]
### Problem description

Hello,

I have recently set up a simple webDav server based on Apache on my local Archlinux NAS because SMB is giving me some speed issues with high bit rate videos.
Unfortunately I can't connect to the server using NOVA on my nVidia Shield.
In the connect dialog I choose "webdav" (there is no ssl involded), enter the local IP, port and path with a leading "/" (username and password are empty because not needed) and after confirming I get a message at the bottom of the screen saying "You must specify a remote address" and nothing else happens.
I have successfully connected to the server with Infuse running on an Apple TV and also with the X-Plore file manager on the Shield.

Could you please investigate? I'm quite certain I have entered all values correctly but maybe I missed something.

### Steps to reproduce the issue

see problem description

### Your phone/tablet/androidTV model

nVidia Shield Pro 2019

### Operating system version

Android 12

**Comment by zwoggel** [comment]
Ah, one more thing: I'm using NOVA v6.1.6 from github.

**Comment by mason1kwok** [comment]
me too

**Comment by courville** [comment]
@zwoggel, from your description it seems that nova does not handle webdav without credentials. I will investigate.

**Comment by courville** [comment]
@zwoggel, it turns that anonyous login on webdav requires the user to input "anonymous" as username to login (use whatever password). I checked that it works on a synology NAS.

**Comment by zwoggel** [comment]
@courville ah, sounds reasonable. I will try when I'm back home again and get back to you.

**Comment by zwoggel** [comment]
@courville it works when using the username "anonymous". This bug can be closed. Thanks for the help!
