### ISSUE TITLE
android10 say stopped to work

### ISSUE THREAD

**Issue by nico92GitHub** [nova-video-player/aos-AVP#875]
Hello Dev
under Android 10, stopped working, once just after the first start, then I was able to play a video without problem and crashed a second time in the window that shows the videos present on my K108 tablet.
My Netguard allows Nova to connect to the net and I set the battery without any constraint.
After the first crash, I uninstalled XPlayer and Dub Audio Player, rebooted.
Too bad, I like your project very much. If you can help me
nicolas

Hello Dev
sous android 10, a cessé de fonctionner, une fois juste après le premier start, puis j'ai pu lire une vidéo sans problème et planté une deuxième fois dans la fenêtre qui montre les vidéos présentes sur ma tablette k108.
mon netguard autorise nova à se connecter sur le net et j'ai paramétré la batterie sans aucune contrainte.
après le premier plantage, j'ai désinstallé xplayer et dub audio player, rebooté.
dommage, votre projet me plaît beaucoup. si vous pouvez m'aider...

**Comment by courville** [comment]
It would be nice to get a log of the crash using `adb logcat`on your tablet cf. https://github.com/nova-video-player/aos-AVP/wiki/Debugging to investigate.

**Comment by nico92GitHub** [comment]
Accuracy of the problem:
The "nova has stopped working" error only occurs when I run nova without doing anything.
When I launch nova via "open with" there are no errors and the video plays normally and I have access to the parameters and other settings.

Ok, ADB is installed on my machine and I have already copied commands (which worked well) without understanding anything about it. Like:
./adb start-server
./adb.exe devices
./adb -d shell appops set com.catchingnow.tinyclipboardmanager SYSTEM_ALERT_WINDOW allow;
./adb -d shell pm grant com.catchingnow.tinyclipboardmanager android.permission.READ_LOGS;
./adb shell am force-stop com.catchingnow.tinyclipboardmanager;

But, the instructions given in the link are beyond me, I don't know what to do ;(
If you can send me the ADB commands (like the ones I copied above) to pass to get a log of this error, that would be great!

**Comment by nico92GitHub** [comment]
I don't know why, but I don't encounter any more errors when launching NOVA, so everything is fine now.
Thank you for your contact,
nico
