### ISSUE TITLE
[FEAT]: Unable to read IOS file. Please add support

### ISSUE THREAD

**Issue by lubaohua** [nova-video-player/aos-AVP#876]
### Description

I really like NOVA. He has excellent poster wall functionality, but it is currently unable to read my IOS files

**Comment by courville** [comment]
Hi, when you are referring to IOS files, do you mean video shot from an iphone?
Please provide sample so that we can progress on the issue.

**Comment by lubaohua** [comment]
Ant-Man.and.the.Wasp.Quantumania.2023.WEBRip.x264.ios

**Comment by lubaohua** [comment]
It's in this format

**Comment by phhusson** [comment]
I've asked some people noone has ever heard of that. Can you provide us with a downloadable link?

**Comment by lubaohua** [comment]
magnet:?xt=urn:btih:12183b3a947e15808473b215752289fdddd5de63

**Comment by phhusson** [comment]
That's an iso, not ios.

**Comment by courville** [comment]
Closing as duplicate of https://github.com/nova-video-player/aos-AVP/issues/450

**Comment by lubaohua** [comment]
Oh okay, I made a mistake. Where can I add support

**Comment by ghost** [comment]
Iso is not really a video file, but a disk image to be burned on disk or mounted as a virtual drive. While some players can handle iso o doubt it's worth it for nova. Mount the iso as a drive and then rip it to an mkv file instead.

**Comment by lubaohua** [comment]
Do you want Nova to recognize ISO format? Many players support playing ISO format videos directly
