### ISSUE TITLE
[Bug]: message `api.OpenSubtitles.org is deprecated, please implement REST API from OpenSubtitles.com`

### ISSUE THREAD

**Issue by alexanderadam** [nova-video-player/aos-AVP#883]
### Problem description

When downloading subtitles the message `api.OpenSubtitles.org is deprecated, please implement REST API from OpenSubtitles.com` appears during play

### Steps to reproduce the issue

1. download subtitles

### Expected behavior

no warning message

### Your phone/tablet/androidTV model

-

### Operating system version

-

### Additional system information

I guess it's related to [this upstream issue](https://trac.opensubtitles.org/projects/opensubtitles).

**PS:** as usual, thank you so much for working on Nova and I'm sorry that I'm opening [so many issues](https://github.com/nova-video-player/aos-AVP/issues/created_by/alexanderadam) 🫣

**Comment by courville** [comment]
Thanks, this is related to https://github.com/nova-video-player/aos-AVP/issues/852
EOL is expected EOY and not now...
Just tested on my end and it is still working.
Will get on it soon.

**Comment by alexanderadam** [comment]
Ah, i missed this. I'll close this issue then.
