### ISSUE TITLE
[Bug]: Nova fails to automatically scrape info

### ISSUE THREAD

**Issue by Unix-Kernel** [nova-video-player/aos-AVP#887]
### Problem description

Nova no longer obtains info automatically. I have to manually select the "get info".

I have not made any changes to the network, to Nova, or any devices anywhere. 

I was watching a series and after it completed I browsed into another folder to start another one but when it went to obtain the info for it, Nova failed and returned to the top of the folder file-list. 

I have cleared the cache and restarted the device twice, then tested with other series/folders but Nova fails to automatically scrape the info unless I manually select it. I also tried from another smb-shared folder on a different system in the network with same results. 

The first series that it failed to scrape, it will not download the info even after I manually select it, however, the other series/folders info it will download the poster but only after I manually select them. Somehow, that one series has caused a glitch/bug that is preventing Nova from automatically fetching the "info" for anything. Along with this issue, when I first try to access/open Nova and/or browse to a folder and select an episode, it scans for a minute or so and then automatically goes back to the previous screen similar to what it does after it fails to scrape/download the info, then exists to the folder list or previous screen. Apparently, both issues seem to be connected/associated.

I also have the same version of Nova installed on a 2nd-device identical to this one with no issues scraping and downloading info automatically. I tested on several of the same folders that failed on this device except the first folder that started causing this.

I'm thinking that my only option/solution is to "clear the data" for Nova.

### Steps to reproduce the issue

Access or open any tv-series in any folder and fails to automatically fetch media info.

### Expected behavior

Automatically fetch/download "info".

### Your phone/tablet/androidTV model

Firestick 4K

### Operating system version

Fire OS 6.2.7.7 (NS6277/3033)

### Application version and app store

5.15.26

**Comment by courville** [comment]
Hi, could you please use a recent version of nova (v6.x) and reproduce the issue?
It would help to get `adb logcat` logs (check wiki debugging session).
Perhaps check that you are not in private mode as well (should not be the case).

**Comment by Unix-Kernel** [comment]
Everything seems to be working again without having to clear the data. 

All I did was after exiting the other Nova on the 2nd-device, I came back to this one to recheck my preferences to compare them with my saved screenshots of all the settings in case I had to do a "clear data" and then I browsed to the folders one last time and they started automatically scrapping and downloading the info for each file I selected. It also had saved the info for some of the previous folders where they had failed. 

I also tested from the other smb-folder on the other network-system and it worked without problems. The other issue of exiting back to the previous screen is also gone. Whatever the issue was, appears to have been temporary.

I prefer the older version of NVP since I rely solely on the information from "TheTVDB" for both Nova and offline. 

If the issue had not resolved on its own, I would have cleared the data for Nova or reinstalled the same version.
However, I do have 6.x installed in two separate instances of Nox-emulator and MEmu-emulator for testing purposes.

Thanks for the quick response. You may close this ticket.

**Comment by Unix-Kernel** [comment]
> Hi, could you please use a recent version of nova (v6.x) and reproduce the issue? It would help to get `adb logcat` logs (check wiki debugging session). Perhaps check that you are not in private mode as well (should not be the case).

I’m posting this as a reference in case someone else comes across this issue with older versions of Nova that uses TVDB for scraping.

Ok, so I was able to replicate the issue in Nox-emulator with the problematic files from that particular tv-series.

I tested with different versions of Nova from 5.15.16 to 6.0.10 (final version I had that uses TVDB). They all crashed trying to scrape the files for that particular series; no other files/series are causing this issue.

I did not have versions between (6.0.11 - 6.0.13 to test with), however, I did have a copy of version 6.0.14 which starts using TMDB and it was able to scrape the files from that tv-series without any issues, so it seems that all older versions of Nova that uses TVDB for tv-series will crash when trying to scrape that one particular series. 

I copied that folder to a 2nd server with same results to make sure that it had nothing to do with the first server. 

The files are still playing with no issues in 5.15.16 in the Firestick-4K but will not scrape them due to the TVDB scraping conflict/bug.

BTW, I also tested this tv-series using files from two other release groups with the same results which means that it is not the actual file(s) causing the issue but Nova trying to scrape this particular series from TVDB which causes both issues I described earlier in the Firestick. 
They crashed in all versions of Nova up to 6.0.10 but scrape fine starting with 6.0.14 which uses TMDB.

The name of the series is: Will Trent.

I have watched many series and this is the first time I have come across this bug.

**Comment by courville** [comment]
@linuxlad, nova v5 is so old and there has been so many fixes since that you should really not use it anymore.
I understand your point about tvdb but all major apps are migrating to tmdb due to policy changes about tvdb.
Please refer to https://github.com/nova-video-player/aos-AVP/issues/402
