### ISSUE TITLE
[FEAT]: Switch audio track on device without keyboard (e.g. smart TV)

### ISSUE THREAD

**Issue by lianee** [nova-video-player/aos-AVP#896]
### Description

For subtitles, pressing the up arrow on keypad brings up a dialog allowing to switch subtitles, but I found no way to change audio track.
The [shortcut page](https://github.com/nova-video-player/aos-AVP/wiki/Keyboard-shortcuts) tells that #/A is used to switch audio track, but there is no such key on my remote (and I'm sure almost all smart TVs)

I found some almost related requests #590 and #843 but no positive answers to them.

Please add a way to switch audio tracks using a limited remote control.

**Comment by phhusson** [comment]
When there are multiple audio tracks, the audio tracks are shown when
doing keypad up right next to the list of subtitle tracks

**Comment by lianee** [comment]
Oh, thanks a lot, I didn't know of that option (and it is a little hidden)
This is perfect like that.
