### ISSUE TITLE
这个播放器不支持加载MKV格式视频内已封装存在了的字幕吗？

### ISSUE THREAD

**Issue by iqingtongqi** [nova-video-player/aos-AVP#898]
如题，很多MKV格式电影资源内封的外挂字幕直接不加载的，只能再去用这个播放器的字幕下载功能检索下载，有点奇怪
还是我的手机有问题，只有我遇到了这个问题？看大家都没有反映过这个问题🥲

**Comment by courville** [comment]
It does not support yet PGS but other format should be fine (see https://github.com/nova-video-player/aos-AVP/issues/47)
