### ISSUE TITLE
[FEAT]: scraping non-English TV shows

### ISSUE THREAD

**Issue by LumiaJ** [nova-video-player/aos-AVP#906]
### Description

I have found that it is difficult to recognize accurate information when scraping non-English TV shows. The results obtained from clicking to retrieve information are similar to searching for Chinese content on an English website. Can you add something like "?language=zh-CN" to the TMDB data package during the search, where the language can be customized? This would help increase the accuracy of scraping TV shows.

**Comment by courville** [comment]
Hi, reading https://developer.themoviedb.org/docs/languages it seems that only ISO_639-1 code is supported.
Scraper uses default locale 2 letters ISO to match tmdb expectations.
Perhaps I misread something.
Language use to scarpe can be changed in nova's settings in Posters & descriptions section by selecting TV show or Movies entry.

**Comment by LumiaJ** [comment]
可能我用了翻译，导致意思不太准确。
我又测试了一下，发现对于非英文的剧集，刮削的时候会默认只搜索电影里的内容，而不是选择剧集。我在nova中使用手动搜索之后出现的内容，只有我在tmdb的网站上搜索后显示的内容里，电影分类的内容，并不显示剧集的内容

Perhaps I used a translation, which caused the meaning to be inaccurate.
I tested it again and found that for non English episode, when scraping, it defaults to only searching for the content in the movie, rather than selecting the episode. The content that appears after manual search in Nova, only the content that appears after I search on the TMDB website, including the movie category content, does not display the content of the episode

**Comment by courville** [comment]
Could you please provide the exact filename that caused this behavior for me to try to reproduce?

**Comment by courville** [comment]
@LumiaJ let's close this issue and follow the progress in https://github.com/nova-video-player/aos-AVP/issues/1129 where I have a fundamental question for interpreting the ISO639-1 language codes to support Traditional Chinese in TMDb.
Please review and help there.
