### ISSUE TITLE
[FEAT]: Can you add a display language selection setting?

### ISSUE THREAD

**Issue by JasmineYong** [nova-video-player/aos-AVP#915]
### Description

My TV box system only supports English, the APP automatically recognizes the language and cannot set Chinese display

**Comment by courville** [comment]
You should be able to select nova language in Android settings->applications->nova. And then enforce scraping and subs language in nova settings itself. But perhaps it will not work in your case since you have a non standard Android.

**Comment by courville** [comment]
I understand the need and I think this issue is the same: https://github.com/nova-video-player/aos-AVP/issues/1235
Let's close this one and follow progress on the other issue.
