### ISSUE TITLE
[FEAT]: Will vobsub subtitle support be added?

### ISSUE THREAD

**Issue by kerwin-uy** [nova-video-player/aos-AVP#919]
### Description

VobSub subtitle support when playing videos

**Comment by branches78** [comment]
Isn't this already supported?

Then one still not supported is PGS subtitles.

**Comment by kerwin-uy** [comment]
It's weird, it doesn't work on my tablet (Lenovo Y700), but works on my other devices. I also tried using a different app on the same tablet and the vobsubs work there.

**Comment by courville** [comment]
vobsubs are supported and in a new way now also (side effect of pgs support added).
