### ISSUE TITLE
playeractivity on phone/tablet: button bar makes the video and control shift

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#92]
Two issues:
- launch video playback portrait and touch screen, controls appears and shifts video up
- launch video playback portrait wait for button bar to disappear, rotate anti-clock wise (bottom of phone on the left) touch screen to have button bar appear, volume bar is shifted with gap too far on the right

**Comment by courville** [comment]
It is present on nova+api28

**Comment by courville** [comment]
This behavior only happens with phones with a notch. When disabling it in developer option, there is no issue.

**Comment by JJD2K** [comment]
then just ignore it :)
