### ISSUE TITLE
[Bug]: v6.2.18 refuses to play videos over SMBJ, and crashes to previous Season menu

### ISSUE THREAD

**Issue by Pentaphon** [nova-video-player/aos-AVP#923]
### Problem description

@courville As the title says. Not sure if you can see my crash logs, if any. 

### Steps to reproduce the issue

1) Upgrade from v6.2.17 to v6.2.18 with a single SMBJ share
2) Try to play video by going to "all tv shows" > show > season whatever episode whatever page, hit the play button, it then crashes back to the list of seasons. The screen flashes and the circle in the top right corner spins and it goes back to the seasons list. 
3) Did a clean install, redid library with the same SMBJ process, still can't play video

Might be something wrong with SMBJ 12.2? 

### Expected behavior

Videos should just play as normal 

### Your phone/tablet/androidTV model

Onn 4K 

### Operating system version

Android 11 Stock

### Application version and app store

v6.2.18 Github v7

**Comment by courville** [comment]
Thanks for the quick report. I will have a look.

**Comment by courville** [comment]
Can you please check the new release on GitHub (second try) to see if this is related?

It fixes a NPE I saw earlier.

**Comment by Pentaphon** [comment]
> Can you please check the new release on GitHub (second try) to see if this is related?
> 
> It fixes a NPE I saw earlier.

Fixed! My videos play perfectly again! Although I will say v6.2.17 has 2 annoying issues:

1)  where if you play videos sequentially, like a tv show with many episodes, it will sometimes stop before playing the next video with a black screen and when you back out of it and try to play the video manually, it brings up a "cannot play video" toast over and over for about 20-30 seconds until finally it plays successfully.  I will let you know if I continue to see the issue in https://github.com/nova-video-player/aos-AVP/issues/835

2) https://github.com/nova-video-player/aos-AVP/issues/910

Not sure what is going on there but maybe v6.2.18 will fix it?

Also unrelated but what is the difference between binge mode and folder mode? The black screen issue happens on both modes.

**Comment by courville** [comment]
I will try to reproduce the issue with playing in series episodes. I cannot reproduce it with short videos in folder mode so far. It must be some issues reusing smbj contexts not valid anymore.

The binge mode enables to play tv show episodes sequentially even if they are not located in the same folder.

**Comment by Pentaphon** [comment]
> The binge mode enables to play tv show episodes sequentially even if they are not located in the same folder.

@courville can you add this to https://home.courville.org/nova_video_player-faq/index.html?

I had a bunch of people ask me this and nowhere to point them to.
