### ISSUE TITLE
[Bug]: v6.2.19 panic

### ISSUE THREAD

**Issue by KyleSanderson** [nova-video-player/aos-AVP#928]
### Problem description

08-26 18:11:38.882 11777 11777 E AndroidRuntime: FATAL EXCEPTION: main
08-26 18:11:38.882 11777 11777 E AndroidRuntime: Process: org.courville.nova, PID: 11777
08-26 18:11:38.882 11777 11777 E AndroidRuntime: java.lang.NoSuchMethodError: No static method isExternalStorageManager()Z in class Landroid/os/Environment; or its super classes (declaration of 'android.os.Environment' appears in /system/framework/framework.jar!classes2.dex)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at com.archos.filecorelibrary.FileUtils$$ExternalSyntheticApiModelOutline0.m(SourceFile:0)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at com.archos.mediacenter.video.browser.PermissionChecker.checkAndRequestPermission(SourceFile:102)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at com.archos.mediacenter.video.leanback.MainActivityLeanback.onResumeFragments(SourceFile:66)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onPostResume(SourceFile:322)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.Activity.performResume(Activity.java:7373)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3822)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3873)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:211)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6769)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-26 18:11:38.882 11777 11777 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

### Steps to reproduce the issue

Launch the application.

### Your phone/tablet/androidTV model

Firestick 4K Max

### Operating system version

9

**Comment by Pentaphon** [comment]
This is probably what I just got when I installed it. When you try to open Nova, it crashes to homescreen before the app has a chance to load.

**Comment by courville** [comment]
Thanks for reporting: I will fix it today.

**Comment by courville** [comment]
Fixed by https://github.com/nova-video-player/aos-Video/commit/86389de3de758d4cbe330ee17165e49e2e54962c
Will publish a 6.2.20 soon.

**Comment by courville** [comment]
6.2.20 is out please check that it is ok on your side and reopen the issue otherwise.

**Comment by KyleSanderson** [comment]
Confirmed to launch now - thank you
