### ISSUE TITLE
honor the phone notch in playeractivity

### ISSUE THREAD

**Issue by courville** [nova-video-player/aos-AVP#93]
This might interfere with the controls.
On phones with a notch in landscape with top of the phone on the left where the notch is located, for now the video is not centered when playing. It is noticeable.

**Comment by JJD2K** [comment]
These notches will be gone soon - who will watch a video while an annoying notch is on screen? If you buy a phone with notch you know it is not good for full-screen video - why add a workaround? I think they have embedded option to go into a smaller viewport mode - below the notch.
Anyway I think wasting time on such stuff is just pointless. I beleive they will give up those notches in upcoming models.
