### ISSUE TITLE
[Bug]: cannot get info for video files

### ISSUE THREAD

**Issue by kemege** [nova-video-player/aos-AVP#949]
### Problem description

NOVA fails to find the information of any video, even from the button in the video details page.

### Steps to reproduce the issue

1. Fresh install the application.
2. Access a SMB device, and add one of the folders to the library.
3. NOVA then starts scanning the folder, but no video show up in the Movie, TV, or Anime.
4. Choose any video, and in the detail page, get the information through the button manually.
5. The search (The keyword seems properly extracted, like "Fall 2022") showed no result.

### Expected behavior

movies and dramas should show up in the desired sections, and we should be able to see some search results from the details page.

### Your phone/tablet/androidTV model

XGIMI H3S

### Operating system version

Android 9

### Application version and app store

6.2.18

### Debug logs

The OS installed on the device seems to disabled ADB debugging, and prevent users from enabling it, so currently I've found no way to collect such logs.

**Comment by courville** [comment]
Could you please try on latest 6.2.25 (6.2.18 has been removed for issues from github) and let me know your scrape language (or locale) used?

**Comment by kemege** [comment]
> Could you please try on latest 6.2.25 (6.2.18 has been removed for issues from github) and let me know your scrape language (or locale) used?

Thanks for the reply. I've just tried 6.2.25, but still got the same result.
I also have tried to set the scrape language to Chinese and English (in the options pane of the app), but that does not make any difference.
In the search page, I did not notice anything about network errors, so perhaps I should exclude the possibility that my device cannot access TMDB?

**Comment by courville** [comment]
I am so far unable to reproduce unfortunately your non scrape behavior on SMB after a fresh nova install on the devices and simulator so far. I could help getting logs but I noticed your comment about not being able to enable adb.

Could you please:
1) let me know your device exact default language so that I mimic your setup more accurately
2) detail your SMB server specification (SMB level, brand etc.)
3) check if the issue is present in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.17

Thank you

**Comment by courville** [comment]
And can you please detail also your SMB server specification (SMB level, brand etc.)?

**Comment by kemege** [comment]
> I am so far unable to reproduce unfortunately your non scrape behavior on SMB after a fresh nova install on the devices and simulator so far. I could help getting logs but I noticed your comment about not being able to enable adb.
> 
> Could you please:
> 
>     1. let me know your device exact default language so that I mimic your setup more accurately
> 
>     2. detail your SMB server specification (SMB level, brand etc.)
> 
>     3. check if the issue is present in https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.17
> 
> 
> Thank you

Thank you very much for your reply and kind help. 
The SMB part is all fine, and NOVA can read and write information without error.
After some further investigation, the reason for the problem turns out to be the DNS from the ISP, which gives invalid results for api.themovidb.org, and it can be fixed by setting up a person DNS which corrects the invalid data.
