### ISSUE TITLE
[Bug]: Opensubtitles setting doesn't save the password

### ISSUE THREAD

**Issue by branches78** [nova-video-player/aos-AVP#955]
### Problem description

As the title states, the password is not getting saved in the Opensubtitles section in settings, which causes not being able to download any subtitle.

### Steps to reproduce the issue

1. Go to settings
2. Scroll down to Opensubtitles setting
3. Enter email and password
4. Hit save
5. When I go to a video description and attempt to search for a subtitle, a message at the bottom appears stating that the credentials are wrong or something.

### Your phone/tablet/androidTV model

Homatics Box R 4K Plus and Onn 2023

### Operating system version

Android 12

### Application version and app store

v6.2.25 from github

**Comment by courville** [comment]
I tried with 6.2.25 and with opensubtitles (login+password, not email as login), it works on my side indicating saving password should work.
In the https://github.com/nova-video-player/aos-AVP/issues/852 evolution, I will implement a login check in credential dialog (which does not exist currently).

-> please try to use your opensubtitle username as login and not email used for opensubtitles registration.

**Comment by branches78** [comment]
I found something odd:

My report was based only on the Onn 2023 though I didn't enter the username but the email address, however, on the Homatics Box R 4K Plus I didn't enter the credentials and the app let me download subtitles anyway, though I still saw the notification at the bottom stating that I had to enter the credentials to be able to download subtitles but the app let me download them anyway.

Can you check what's going on?

I'm gonna try to send a video from both devices.

**Comment by branches78** [comment]
So I enter the username on the Onn 2023 and it doesn't work, it doesn't let me download subtitles, meanwhile on the Homatics Box I'm always able to download subtitles without the credentials as you can see in the below video:

https://drive.google.com/file/d/1Rm13EMvDCTrkUJ-nRnStghQZYuPM67kp/view?usp=sharing

**Comment by branches78** [comment]
I reset the app on the Onn and now it's the same as on the other device, subtitles can be downloaded without credentials when they are supposed to be entered to be able to download subtitles.

**Comment by courville** [comment]
Opensubtitles a couple of years back facing load issues on their backend made it mandatory to input credentials to download subs. Now, this restriction has been removed pending more drastic evolution for end of year (XML-RPC -> REST API change with quotas). This is why now even without credentials, you can download subs.

**Comment by branches78** [comment]
Thank you for clarifying this, I guess you can close this bug report unless you need to keep it open.
