### ISSUE TITLE
[FEAT]: update app description and mention WebDAV

### ISSUE THREAD

**Issue by stokito** [nova-video-player/aos-AVP#956]
### Description

Please mention WebDAV in the app description.
I searched for a player with WebDAV support in FDroid but didn't found the app. While SMB, DLNA are mentioned the DAV is not.
Maybe some other features arwn't mentioned too.

Also it may be useful to support mDNS autodiscovery for webdav servers in local network. But it's anyway not used widelly yet so this is not important

**Comment by courville** [comment]
Good point, webdav(s) is a recent addition: I will update the store descriptions.

**Comment by courville** [comment]
Now I have win a special app description review on google play by Google... hope it will be ok.

**Comment by stokito** [comment]
Thank you, I also added the Nova to list of WebDAV players https://github.com/WebDAVDevs/awesome-webdav#android-players

Currently the Nova is the only open source video player.
Thank you for your work
