### ISSUE TITLE
[Bug]: Option hide subtitles default not work

### ISSUE THREAD

**Issue by coolllman** [nova-video-player/aos-AVP#957]
### Problem description

Option hide subtitles default not work, subtitles always enabled on last builds, last working build 6.2.17

### Steps to reproduce the issue

Option hide subtitles default on and try any videos

### Your phone/tablet/androidTV model

Shield tv 2019 pro

### Operating system version

Android 11

### Application version and app store

V6.2.26

**Comment by courville** [comment]
This might be a regression due to putting "none" fist in sub tile. Will look into it.

**Comment by courville** [comment]
Please test and reopen if nok with https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.31

**Comment by coolllman** [comment]
All work great now, thank you!!!
