### ISSUE TITLE
[Bug]: v6.2.27 release candidate 点击首选项就闪退

### ISSUE THREAD

**Issue by gzxiexl** [nova-video-player/aos-AVP#958]
### Problem description

点击首选项就报错闪退

### Steps to reproduce the issue

点击首选项

### Expected behavior

报错 退出

### Your phone/tablet/androidTV model

华为matepad pro11

### Operating system version

鸿蒙4.0

### Application version and app store

v6.2.27 release candidate

**Comment by gzxiexl** [comment]
![Screenshot_20230923_200316_com.huawei.android.launcher.jpg](https://github.com/nova-video-player/aos-AVP/assets/40417977/ca63d402-6416-41e0-9aec-b987047c5ff4)

**Comment by courville** [comment]
Ok my bad. Pulled out the release for a "try again" later today. Thanks for reporting

**Comment by courville** [comment]
https://github.com/nova-video-player/aos-AVP/releases/tag/v6.2.28 available.
