### ISSUE TITLE
Google Play Public Release - missing

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#96]
On the releases page you write - Google Play Public Release, but those are not present on google play. Only the initial version is there.

**Comment by courville** [comment]
Two versions are on google play: the old one and when you subscribe to the beta you have access to the latest SMB1 (not SMB2 with jcifs-ng) one.

**Comment by JJD2K** [comment]
I did not understand this, and I see no way for subscribing to beta on the Android TV store - maybe you do not upload those to the TV store which I was referring to. On the TV store is the initial version only.

**Comment by courville** [comment]
Activation URL for beta release is this one: https://play.google.com/apps/testing/org.courville.nova
