### ISSUE TITLE
Realdebrid webdav on nova player 

### ISSUE THREAD

**Issue by zaraki75** [nova-video-player/aos-AVP#963]
### Problem description

[Bug]: I added my realdebrid as webdav on novaplayer... It seems novaplayer cant play the videos. And it doesn't download them as a single video file... it starts downloading the whole realdebrid webdav... iam using latest version and i tried many versions

### Steps to reproduce the issue

mentioned above 

### Your phone/tablet/androidTV model

Realme X2

### Operating system version

Android 11

**Comment by courville** [comment]
Let's follow progress on this issue here: https://github.com/nova-video-player/aos-AVP/issues/1018 and close this one
