### ISSUE TITLE
[FEAT]: why does the player have not speed player???

### ISSUE THREAD

**Issue by thesexday** [nova-video-player/aos-AVP#973]
### Description

every player has speed play , like 2X , 3X  play speed, but nova video player has not.

**Comment by PacoBell** [comment]
Duplicate of [#10](https://github.com/nova-video-player/aos-AVP/issues/10)

It's already been implemented, although it only goes up to 2.00x, so there's still room for improvement.

**Comment by courville** [comment]
Indeed duplicate of https://github.com/nova-video-player/aos-AVP/issues/10
Note that for now limitation is to 2x because of buffering constraints.
