### ISSUE TITLE
v4.0 new Google Play beta release - Not starting on Sony TV

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#98]
This version does not start on Sony TV
I was dumb enough to clear the cache and data too :) - same result
The last stable version is 3.2. I installed also 3.4, but it had bugs and was lagging so I reverted to 3.2

**Comment by courville** [comment]
OK, I trust that your Sony TV is running Android 7: I will disable tv channels for Android 7 (API too low).

**Comment by courville** [comment]
Activation URL for beta release is this one: https://play.google.com/apps/testing/org.courville.nova

**Comment by courville** [comment]
Please try this one out https://github.com/nova-video-player/aos-AVP/releases/tag/v4.1
