### ISSUE TITLE
[Bug]: Black bars are grayed out on Chromebook

### ISSUE THREAD

**Issue by JGomsss** [nova-video-player/aos-AVP#980]
### Problem description

The black bars are grayed out on Chromebook regardless of crop mods

![image](https://github.com/nova-video-player/aos-AVP/assets/28355812/87762952-07a7-46ca-95ae-3ee9b7b54158)

### Steps to reproduce the issue

Launch any video and switch display modes to see the format bars

### Your phone/tablet/androidTV model

HP Chromebook x360 12

### Operating system version

Android 11 on ChromeOS 119

### Application version and app store

version 6.2.31-20231010.2009

**Comment by courville** [comment]
Reminds me of https://github.com/nova-video-player/aos-AVP/issues/270
Thanks for pointing this out, I will investigate.

**Comment by courville** [comment]
I do not have a chromebook with me but I tried a "blind fix". Could you please report if this apk https://drive.google.com/file/d/1_san7zKO2xM82TMkwtrykZV4bQAkkufY/view?usp=sharing fixes the issue?

**Comment by JGomsss** [comment]
> I do not have a chromebook with me but I tried a "blind fix". Could you please report if this apk https://drive.google.com/file/d/1_san7zKO2xM82TMkwtrykZV4bQAkkufY/view?usp=sharing fixes the issue?

I get a crash every time I play a video

**Comment by courville** [comment]
My bad: here is a revert build, https://drive.google.com/file/d/1AGRDkj_by5V9B_4-KpTDI2kPmxNj3UuJ/view?usp=sharing assuming you are running x86_64 (let me know if you have another arch).
I guess, a proper fix will wait that I get a chromebook to check the fix before blindly sharing.

**Comment by JGomsss** [comment]
No problem, I had already reverted to the previous version.
Indeed, I am on an x86_64 architecture.
I remain available for other tests

**Comment by courville** [comment]
Here is another build that I tested to work on my side on a chromebook: https://drive.google.com/file/d/1OC7nTTe6sk_skEMRxkLgpsCEUmtRC1ky/view?usp=sharing (x86_64).

**Comment by JGomsss** [comment]
I tested with different videos and for all crop modes and it works correctly
