### ISSUE TITLE
Clarify fdroid anti-feature mark

### ISSUE THREAD

**Issue by ghost** [nova-video-player/aos-AVP#982]
Fdroid says the app tracks or reports your activity. Why's that?

**Comment by courville** [comment]
Nova relies on external video scraping service such as themoviedb to obtain video information/posters/banners that might collect filenames. These services are also not open-source. Apart from this external service (and trakt if you enable it), Nova does not collect any other information.
Please check https://home.courville.org/nova_video_player-faq/privacy.html for more details.
Note that the crash logs reported to sentry backend is not active on f-droid releases.
