### ISSUE TITLE
[Bug]: webdav - pause playback and resume will skip the current playback and progress is lost

### ISSUE THREAD

**Issue by Senorsen** [nova-video-player/aos-AVP#985]
### Problem description

When using the WebDAV protocol, if I pause the playback for a while (a few seconds or minutes), and then resume the playback, it often "skip" the current playback after several seconds (although its progress is in the middle of the video), and play the next video/episode (because I enable the "episode mode" so it automatically plays the next episode). It looks like that the app assumes the current file is "finished/ended", because this file is marked as "already played" and doesn't have the playback progress information any more.

If I adjust the buffer in the hidden setting menu, like to 500mb, the issue is not gone, it is just postponed.

The video file is not very big - just some 1080p h264 24fps files and the bitrate is < 10mbps.

When using the SMB protocol, it seems no such issue, but the performance is really bad (another problem and it is not related to this issue), cannot playback some 4k videos.

### Steps to reproduce the issue

Use the WebDAV protocol, pause the playback for a while (a few seconds or minutes), and then resume.

### Expected behavior

The app should continue the playback normally until it is really finished.

### Your phone/tablet/androidTV model

TCL FFALCON 85R675C armeabi-v7a

### Operating system version

Android 11 (TV)

### Application version and app store

version 6.0.29 from github, org.courville.nova-2576098-6.2.29-20230924.1809-universal-release.apk

### Additional system information

The Android TV is a "nice" TV with HDR/DolbyVision/4k 144 support, with 4G RAM and MT9653 CPU.
Synology NAS: 6.2.3, with an intel cpu (i think there's no performance bottleneck)
Network: 
* The Android TV supports WIFI 6, connects to an ASUS RT-AX86U Pro (AX5700 router) and their distance is close enough (only a few meters in the living room), and the internet speed test on this TV gives about ~400mbps result, so I assume the LAN speed should be at lease this level or even better.
* The NAS is using a wired connection, tried its embedded 1G port, and an external USB 2.5G port, but no difference.

**Comment by Senorsen** [comment]
Seems similar to #920, the results are similar - progress lost

**Comment by courville** [comment]
I think this is a duplicate, that needs indeed attention (I can reproduce but failed so far to fix it). Let's close this issue and follow progress here https://github.com/nova-video-player/aos-AVP/issues/674
It is not specific to webdav.

**Comment by Senorsen** [comment]
Hi @courville, I have read #674 but maybe it's not a completely same scenario - in this case I just paused for a few seconds or minutes without screensaver / blank screen. Please correct me if i'm wrong

**Comment by Senorsen** [comment]
In terms of webdav - i'm not sure, but when using smb I didn't have this particular issue, when resume the playback after 10+minutes pausing. But as you know the smb performance is extremly bad in the nova player...

**Comment by courville** [comment]
> In terms of webdav - i'm not sure, but when using smb I didn't have this particular issue, when resume the playback after 10+minutes pausing. But as you know the smb performance is extremly bad in the nova player...

Thanks for the complementary information.
Please note that now nova has 2 smb implementation and using smbj instead of jcifs-ng it is much faster.
To switch from legacy jcifs-ng implementation to smbj, you need to activate "use faster SMB implementation" in nova settings.
