### ISSUE TITLE
Friendly advice - Please focus on Android TV

### ISSUE THREAD

**Issue by JJD2K** [nova-video-player/aos-AVP#99]
Of course it is your decision what to do but let me point just few things.

1. I have many friends with Android TV and they all loved Archos(even then) , but as playback was not fluent they switched to KODI, VLC and MXPlayer

- Jitter on HD and 4k
- Most 4k can not be played - lots of frame skips

2. There are zillions of players for phones and just few for TV

3. Archos user interface was way better than any other tool 
-KODI - awful interface and way of organizing things
-VLC - has playback issues can not obtain media info
-MXPlayer - very smooth playback, but does not support network and must be invoked via a File Explorer

4. Focusing on new user interface features makes the tool worse by introduces useless bugs, while it still can not play properly lots of content.

Overall I think that if you focus on performance and make it on par with MXPlayer, Nova will be the best Android TV player out there. If you keep paying attention on supporting phones and their dumb notches and hardware that is not dedicated for decoding video you will just waste time and add code which will make the player even slower.

Of course this is just my humble opinion, but everyone is still expecting to see an all-in-one player that can be used on an Android TV.

Do not get me wrong - I like your player a lot and appreciate the effort that you have put in it, but I believe that you are heading in the wrong direction.

**Comment by courville** [comment]
Thanks for the detailed feedback.
